"use strict";

function createPinterestClient({apiBase,clientCredentials,saveConnection,getConnection,parseExpiry,fetchImpl=fetch,now=()=>Date.now()}={}){
  for(const[name,value]of Object.entries({apiBase,clientCredentials}))if(typeof value!=="string"||!value)throw new TypeError(`${name} is required`);
  for(const[name,fn]of Object.entries({saveConnection,getConnection,parseExpiry,fetchImpl,now}))if(typeof fn!=="function")throw new TypeError(`${name} must be a function`);
  const expiresSoon=conn=>{const expires=Date.parse(conn?.token_expires_at||"");return Number.isFinite(expires)&&expires-now()<=120000};
  async function refresh(conn){if(!conn?.refresh_token)throw Object.assign(new Error("Pinterest connection expired. Please reconnect Pinterest."),{status:401,code:"PINTEREST_RECONNECT_REQUIRED"});const body=new URLSearchParams({grant_type:"refresh_token",refresh_token:conn.refresh_token}),response=await fetchImpl(`${apiBase}/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${clientCredentials}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:body.toString()}),data=await response.json().catch(()=>null);if(!response.ok||!data?.access_token)throw Object.assign(new Error("Pinterest connection could not be renewed."),{status:401,code:"PINTEREST_REFRESH_FAILED"});await saveConnection(conn.user_id,"pinterest",{accessToken:data.access_token,refreshToken:data.refresh_token||conn.refresh_token,tokenExpiresAt:parseExpiry(data.expires_in),metadata:{scope:data.scope||conn.metadata?.scope||null,tokenType:data.token_type||conn.metadata?.tokenType||null}});return getConnection(conn.user_id,"pinterest")}
  async function request(conn,endpoint,options={}){let active=expiresSoon(conn)?await refresh(conn):conn;for(let attempt=0;attempt<2;attempt++){const response=await fetchImpl(`${apiBase}${endpoint}`,{...options,headers:{Authorization:`Bearer ${active.access_token}`,Accept:"application/json","Content-Type":"application/json",...(options.headers||{})}}),text=await response.text();let data=null;try{data=text?JSON.parse(text):{}}catch{}if(response.ok){if(!data||typeof data!=="object")throw Object.assign(new Error("Pinterest returned an invalid response."),{status:502,code:"PINTEREST_INVALID_RESPONSE"});return data}if(attempt===0&&response.status===401){active=await refresh(active);continue}throw Object.assign(new Error(`Pinterest request failed (${response.status}).`),{status:response.status,code:"PINTEREST_REQUEST_FAILED"})}throw Object.assign(new Error("Pinterest authentication failed after token refresh."),{status:401,code:"PINTEREST_AUTH_FAILED"})}
  return Object.freeze({request});
}

module.exports=Object.freeze({createPinterestClient});
