const express = require('express');
const session = require('express-session');
const path = require('path');
const { google } = require('googleapis');
const { createClient } = require('@supabase/supabase-js');
const app = express();
app.set('trust proxy', 1);
app.use(express.json());
app.use(session({ secret: process.env.SESSION_SECRET || 'dev_secret', resave:false, saveUninitialized:false, cookie:{httpOnly:true,sameSite:'lax',secure:true} }));
app.use(express.static(path.join(__dirname,'public')));
const supabase = (process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {auth:{persistSession:false}}) : null;
const META_GRAPH_VERSION='v20.0', PINTEREST_API_BASE='https://api.pinterest.com/v5', GOOGLE_ADS_API_VERSION=process.env.GOOGLE_ADS_API_VERSION || 'v24';
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','landing.html')));
app.get('/login',(req,res)=>res.sendFile(path.join(__dirname,'public','login.html')));
app.get('/signup',(req,res)=>res.sendFile(path.join(__dirname,'public','signup.html')));
app.get('/dashboard',(req,res)=>res.sendFile(path.join(__dirname,'public','dashboard.html')));
app.get('/demo',(req,res)=>res.sendFile(path.join(__dirname,'public','dashboard-demo.html')));
app.get('/privacy',(req,res)=>res.sendFile(path.join(__dirname,'public','privacy.html')));
app.get('/terms',(req,res)=>res.sendFile(path.join(__dirname,'public','terms.html')));
app.get('/data-deletion',(req,res)=>res.sendFile(path.join(__dirname,'public','data-deletion.html')));
app.get('/api/public-config',(req,res)=>res.json({supabaseUrl:process.env.SUPABASE_URL||'', supabaseAnonKey:process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||''}));
async function userId(req){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t||!supabase)return null;const {data,error}=await supabase.auth.getUser(t);return error?null:data?.user?.id||null;}
async function ensureUser(id){if(supabase&&id) await supabase.from('users').upsert({id},{onConflict:'id'});}
async function saveConn(uid,platform,payload){if(!supabase||!uid)return;await ensureUser(uid);const row={user_id:uid,platform,access_token:payload.accessToken||null,refresh_token:payload.refreshToken||null,account_id:payload.accountId||null,account_name:payload.accountName||null,metadata:payload.metadata||{},connected:true,updated_at:new Date().toISOString()};const ex=await supabase.from('platform_connections').select('id').eq('user_id',uid).eq('platform',platform).maybeSingle();if(ex.error)throw new Error(ex.error.message);if(ex.data?.id){const {error}=await supabase.from('platform_connections').update(row).eq('id',ex.data.id);if(error)throw new Error(error.message);}else{const {error}=await supabase.from('platform_connections').insert(row);if(error)throw new Error(error.message);}}
async function getConn(uid,platform){if(!supabase||!uid)return null;const {data,error}=await supabase.from('platform_connections').select('*').eq('user_id',uid).eq('platform',platform).eq('connected',true).maybeSingle();if(error)throw new Error(error.message);return data;}
async function status(uid,platform){const db=await getConn(uid,platform).catch(()=>null);return {connected:!!(db?.access_token||db?.refresh_token),source:db?'database':'none',connectedAt:db?.updated_at||null};}
function reqMeta(){if(!process.env.META_APP_ID||!process.env.META_APP_SECRET||!process.env.META_REDIRECT_URI)throw new Error('Missing Meta env');}
app.get('/auth/meta',(req,res)=>{try{reqMeta();const uid=req.query.user_id;if(!uid)return res.redirect('/dashboard?error=missing_user_id');const state=Math.random().toString(36).slice(2);req.session.metaOAuthState=state;req.session.oauthUserId=uid;const p=new URLSearchParams({client_id:process.env.META_APP_ID,redirect_uri:process.env.META_REDIRECT_URI,state,response_type:'code',scope:'ads_read'});res.redirect(`https://www.facebook.com/${META_GRAPH_VERSION}/dialog/oauth?${p}`)}catch(e){res.status(500).send(e.message)}});
app.get('/auth/meta/callback',async(req,res)=>{try{reqMeta();const{code,state,error,error_description}=req.query;if(error)return res.redirect('/dashboard?meta_error='+encodeURIComponent(error_description||error));if(!state||state!==req.session.metaOAuthState)throw new Error('Invalid OAuth state');const uid=req.session.oauthUserId;if(!uid)throw new Error('Missing user session');const url=new URL(`https://graph.facebook.com/${META_GRAPH_VERSION}/oauth/access_token`);url.searchParams.set('client_id',process.env.META_APP_ID);url.searchParams.set('redirect_uri',process.env.META_REDIRECT_URI);url.searchParams.set('client_secret',process.env.META_APP_SECRET);url.searchParams.set('code',code);const r=await fetch(url);const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error?.message||'Meta token failed');await saveConn(uid,'meta',{accessToken:d.access_token,metadata:{expiresIn:d.expires_in||null}});res.redirect('/dashboard?meta_connected=1')}catch(e){res.redirect('/dashboard?meta_error='+encodeURIComponent(e.message))}});
function reqGoogle(){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET||!process.env.GOOGLE_REDIRECT_URI||!process.env.GOOGLE_DEVELOPER_TOKEN)throw new Error('Missing Google env');}
function gClient(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI)}
app.get('/auth/google',(req,res)=>{try{reqGoogle();const uid=req.query.user_id;if(!uid)return res.redirect('/dashboard?error=missing_user_id');const state=Math.random().toString(36).slice(2);req.session.googleOAuthState=state;req.session.oauthUserId=uid;res.redirect(gClient().generateAuthUrl({access_type:'offline',prompt:'consent',state,scope:['https://www.googleapis.com/auth/adwords']}))}catch(e){res.status(500).send(e.message)}});
app.get('/auth/google/callback',async(req,res)=>{try{reqGoogle();const{code,state,error}=req.query;if(error)return res.redirect('/dashboard?google_error='+encodeURIComponent(error));if(!state||state!==req.session.googleOAuthState)throw new Error('Invalid OAuth state');const uid=req.session.oauthUserId;if(!uid)throw new Error('Missing user session');const {tokens}=await gClient().getToken(code);await saveConn(uid,'google',{accessToken:tokens.access_token,refreshToken:tokens.refresh_token||null,metadata:{scope:tokens.scope||null,expiryDate:tokens.expiry_date||null}});res.redirect('/dashboard?google_connected=1')}catch(e){res.redirect('/dashboard?google_error='+encodeURIComponent(e.message))}});
function reqPin(){if(!process.env.PINTEREST_CLIENT_ID||!process.env.PINTEREST_CLIENT_SECRET||!process.env.PINTEREST_REDIRECT_URI)throw new Error('Missing Pinterest env');}
function pinBasic(){return Buffer.from(`${process.env.PINTEREST_CLIENT_ID}:${process.env.PINTEREST_CLIENT_SECRET}`).toString('base64')}
app.get('/auth/pinterest',(req,res)=>{try{reqPin();const uid=req.query.user_id;if(!uid)return res.redirect('/dashboard?error=missing_user_id');const state=Math.random().toString(36).slice(2);req.session.pinterestOAuthState=state;req.session.oauthUserId=uid;const p=new URLSearchParams({response_type:'code',client_id:process.env.PINTEREST_CLIENT_ID,redirect_uri:process.env.PINTEREST_REDIRECT_URI,scope:'ads:read',state});res.redirect(`https://www.pinterest.com/oauth/?${p}`)}catch(e){res.status(500).send(e.message)}});
app.get('/auth/pinterest/callback',async(req,res)=>{try{reqPin();const{code,state,error,error_description}=req.query;if(error)return res.redirect('/dashboard?pinterest_error='+encodeURIComponent(error_description||error));if(!state||state!==req.session.pinterestOAuthState)throw new Error('Invalid OAuth state');const uid=req.session.oauthUserId;if(!uid)throw new Error('Missing user session');const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:process.env.PINTEREST_REDIRECT_URI});const r=await fetch(`${PINTEREST_API_BASE}/oauth/token`,{method:'POST',headers:{Authorization:`Basic ${pinBasic()}`,'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.message||d.error||'Pinterest token failed');await saveConn(uid,'pinterest',{accessToken:d.access_token,refreshToken:d.refresh_token||null,metadata:{scope:d.scope||null,expiresIn:d.expires_in||null}});res.redirect('/dashboard?pinterest_connected=1')}catch(e){res.redirect('/dashboard?pinterest_error='+encodeURIComponent(e.message))}});
app.get('/api/unified/status',async(req,res)=>{const uid=await userId(req);const meta=await status(uid,'meta'),google=await status(uid,'google'),pinterest=await status(uid,'pinterest');res.json({meta:meta.connected,google:google.connected,pinterest:pinterest.connected,tiktok:false,tiktokStatus:'pending_verification',sources:{meta:meta.source,google:google.source,pinterest:pinterest.source}})});
app.get('/api/debug/connections',async(req,res)=>{try{const uid=await userId(req);if(!uid)return res.status(401).json({error:'Not authenticated'});const {data,error}=await supabase.from('platform_connections').select('platform,connected,metadata,updated_at').eq('user_id',uid).order('updated_at',{ascending:false});if(error)throw error;res.json({connections:data||[]})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/tiktok/status',(req,res)=>res.json({connected:false,status:'pending_verification'}));
if(process.env.VERCEL!=='1')app.listen(process.env.PORT||3000,()=>console.log('AdsTable live auth flow running'));
module.exports=app;
