"use strict";
const fs=require("node:fs"),path=require("node:path"),test=require("node:test"),assert=require("node:assert/strict");
const root=path.join(__dirname,".."),contract=JSON.parse(fs.readFileSync(path.join(root,"contracts/shopify/e10-t5c7-integrated-navigation.json"),"utf8")),doc=fs.readFileSync(path.join(root,"docs/E10_T5C7_INTEGRATED_NAVIGATION_ACCEPTANCE.md"),"utf8"),plan=fs.readFileSync(path.join(root,"codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md"),"utf8");
test("first use is currency and verified-account gated before Funnel",()=>{assert.deepEqual(contract.first_use_sequence,["verified_shopify_session","currency_selection","platform_connection_and_verified_account","conditional_klaviyo_email_monthly_plan_cost","funnel"]);assert.equal(contract.default_route,"funnel");assert.match(doc,/browser route\/query kapıları atlatamaz/)});
test("one official navigation connects every product surface",()=>{assert.deepEqual(contract.navigation,["funnel","dashboard","ad_analysis","attribution_differences","platforms","settings"]);assert.equal(contract.separate_global_shell,false);assert.equal(contract.separate_mobile_navigation,false);assert.equal(contract.funnel_table_is_global_route,false)});
test("typed handoffs preserve context without silent coercion",()=>{assert.deepEqual(contract.handoffs.dashboard_to_funnel,["completed_day_time_range","comparison","filters","currency","data_sources","active_ad_account"]);assert.deepEqual(contract.handoffs.attribution_to_funnel,["completed_day_time_range","platform","currency","active_ad_account"]);assert.match(contract.unsupported_context,/no_silent_coercion/);assert.match(contract.settings_change,/invalidate/)});
test("OAuth return is canonical and allowlisted",()=>{assert.equal(contract.oauth_return.canonical_route,"platforms");assert.equal(contract.oauth_return.allowlisted_target_only,true);assert.equal(contract.oauth_return.standalone_dashboard_or_login,false);assert.equal(contract.oauth_return.caller_return_url,false)});
test("responsive accessibility and safety are acceptance gates",()=>{assert.equal(contract.acceptance.mobile_minimum_width_px,320);assert.equal(contract.acceptance.global_horizontal_overflow,false);assert.equal(contract.acceptance.keyboard_and_focus,true);for(const rule of["duplicate_admin_shell","multiple_active_accounts","open_redirect"])assert.ok(contract.forbidden.includes(rule))});
test("plan closes T5-C and advances through offline T6-A",()=>{assert.match(plan,/E10-T5-C7 — `Done` — Integrated navigation\/acceptance/);assert.match(plan,/E10-T5-C output\/display ürün sözleşmesi `Done`/);assert.match(plan,/E10-T6-A — `Done \/ PASS`/);assert.match(plan,/E10-T6-B — `Blocked \/ BLOCKED_BOOTSTRAP_ENV`/)});
