"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const{ACTIONS,planVerifiedLifecycleEvent,executeLifecyclePlan}=require("../src/shopify/privacy-lifecycle");
const base={authority:"shopify_verified_webhook",shop_id:"shop-1",event_id:"event-1",occurred_at:"2026-09-08T13:00:00.000Z"};
test("uninstall and access loss disable access before removing tokens",()=>{for(const event of["uninstall","access_revoked"]){const plan=planVerifiedLifecycleEvent({...base,event});assert.deepEqual(plan.actions,["disable_access","remove_shop_tokens","record_retention_decision"]);assert.equal(Object.isFrozen(plan.actions),true)}});
test("privacy topics require verified authority and scoped customer subject",()=>{assert.deepEqual(planVerifiedLifecycleEvent({...base,event:"customers_redact",subject_ref:"opaque-subject"}).actions,["delete_customer_personal_data","record_deletion_evidence"]);assert.throws(()=>planVerifiedLifecycleEvent({...base,authority:"browser",event:"shop_redact"}),/UNVERIFIED/);assert.throws(()=>planVerifiedLifecycleEvent({...base,event:"customers_redact"}),/CUSTOMER_SUBJECT_REQUIRED/);assert.throws(()=>planVerifiedLifecycleEvent({...base,event:"uninstall",subject_ref:"forged"}),/CUSTOMER_SUBJECT_FORBIDDEN/)});
test("shop redaction revokes authority and tokens before personal-data deletion",()=>{assert.deepEqual(ACTIONS.shop_redact,["disable_access","remove_shop_tokens","delete_shop_personal_data","record_deletion_evidence"])});
test("executor is single-claim ordered and returns redacted evidence",async()=>{const calls=[];const plan=planVerifiedLifecycleEvent({...base,event:"shop_redact"});const operations=Object.fromEntries(plan.actions.map(action=>[action,async()=>calls.push(action)]));const result=await executeLifecyclePlan(plan,{event_store:{claim:async()=>true,complete:async value=>calls.push(`complete:${value.action_count}`)},operations});assert.deepEqual(calls,[...plan.actions,"complete:4"]);assert.deepEqual(result,{contract_version:"e10-t4-v1",event:"shop_redact",status:"completed",action_count:4,access_disabled:true,tokens_removed:true,production_values_exposed:false});assert.doesNotMatch(JSON.stringify(result),/shop-1|event-1|opaque/)});
test("replay and missing destructive operations fail closed",async()=>{const plan=planVerifiedLifecycleEvent({...base,event:"uninstall"});await assert.rejects(()=>executeLifecyclePlan(plan,{event_store:{claim:async()=>false,complete:async()=>{}},operations:{}}),/REPLAYED/);await assert.rejects(()=>executeLifecyclePlan(plan,{event_store:{claim:async()=>true,complete:async()=>{}},operations:{disable_access:async()=>{}}}),/remove_shop_tokens/)});
