"use strict";
const crypto=require("node:crypto"),test=require("node:test"),assert=require("node:assert/strict");
const{exchangeAndPersistShopToken}=require("../src/shopify/token-exchange");
const{registerShopifyAuthRoutes,bearerToken}=require("../src/routes/shopify-auth-routes");
const secret="test-secret-not-production",client="client-id";
function jwt(){const h=Buffer.from(JSON.stringify({alg:"HS256",typ:"JWT"})).toString("base64url"),p=Buffer.from(JSON.stringify({aud:client,dest:"https://store.myshopify.com/",iss:"https://store.myshopify.com/admin",sub:"u",sid:"s",nbf:990,exp:1100})).toString("base64url");return`${h}.${p}.${crypto.createHmac("sha256",secret).update(`${h}.${p}`).digest("base64url")}`}
test("token exchange persists encrypted material and returns redacted evidence",async()=>{let persisted;const result=await exchangeAndPersistShopToken({session_token:jwt(),auth_config:{client_id:client,client_secret:secret,now_seconds:1000},tenant_resolver:async()=>({status:"active",shop_domain:"store.myshopify.com",shop_id:"shop-1",workspace_id:"work-1"}),exchange_client:{exchange:async()=>({access_token:"sensitive-access-token",expires_at:1100,scope:"read_orders",token_type:"online"})},token_store:{put:async value=>{persisted=value;return{shop_id:"shop-1",encrypted:true}}}});assert.equal(persisted.access_token,"sensitive-access-token");assert.deepEqual(result,{contract_version:"e10-t3b-v1",status:"active",shop_id:"shop-1",workspace_id:"work-1",expires_at:1100,reauthorization_required:false});assert.doesNotMatch(JSON.stringify(result),/sensitive|scope|token_type/)});
test("exchange and persistence contracts fail closed",async()=>{const base={session_token:jwt(),auth_config:{client_id:client,client_secret:secret,now_seconds:1000},tenant_resolver:async()=>({status:"active",shop_domain:"store.myshopify.com",shop_id:"s",workspace_id:"w"}),token_store:{put:async()=>({shop_id:"s",encrypted:true})}};await assert.rejects(()=>exchangeAndPersistShopToken({...base,exchange_client:{exchange:async()=>({access_token:"short",expires_at:1100,scope:"",token_type:"online"})}}),/TOKEN_EXCHANGE_CONTRACT_FAILED/);await assert.rejects(()=>exchangeAndPersistShopToken({...base,exchange_client:{exchange:async()=>({access_token:"sensitive-access-token",expires_at:1100,scope:"read_orders",token_type:"online"})},token_store:{put:async()=>({shop_id:"s",encrypted:false})}}),/TOKEN_PERSISTENCE_FAILED/)});
test("auth routes are thin and never accept session token from query",async()=>{const routes={};const app={get:(path,handler)=>{routes[path]=handler}};registerShopifyAuthRoutes(app,{verify_install_callback:q=>({shop_domain:q.shop,state:q.state}),consume_install_state:async()=>({ads_table_user_id:"u"}),complete_install:async()=>{},authenticate_embedded:async({session_token})=>{assert.equal(session_token,"header.token");return{workspace_id:"w"}}});assert.deepEqual(Object.keys(routes),["/auth/shopify/callback","/api/shopify/session"]);assert.equal(bearerToken("Bearer header.token"),"header.token");assert.throws(()=>bearerToken("header.token"),/SHOPIFY_SESSION_REQUIRED/);let output;await routes["/api/shopify/session"]({query:{session_token:"attacker"},get:()=>"Bearer header.token"},{status:()=>({json:value=>{output=value}})},assert.fail);assert.deepEqual(output,{status:"active",workspace_ready:true,reauthorization_required:false})});
