"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),test=require("node:test");
const {verifyGitHubActionsOidc}=require("../security/github-actions-oidc");
const {createHandler,AUDIENCE}=require("../api/e10-activation-preflight");
const {run,ENDPOINT}=require("../scripts/e10-t6c-remote-preflight");
function token(claims){const {publicKey,privateKey}=crypto.generateKeyPairSync("rsa",{modulusLength:2048});const header=Buffer.from(JSON.stringify({alg:"RS256",kid:"test"})).toString("base64url"),body=Buffer.from(JSON.stringify(claims)).toString("base64url"),signature=crypto.sign("RSA-SHA256",Buffer.from(`${header}.${body}`),privateKey).toString("base64url");return{value:`${header}.${body}.${signature}`,jwk:{...publicKey.export({format:"jwk"}),kid:"test"}};}
test("OIDC verifier binds exact repository workflow environment event audience and time",async()=>{const now=2_000_000_000_000,claims={iss:"https://token.actions.githubusercontent.com",aud:AUDIENCE,repository:"fyilanli-oss/ads-table-dev",ref:"refs/heads/main",event_name:"workflow_dispatch",environment:"Production",workflow_ref:"fyilanli-oss/ads-table-dev/.github/workflows/e10-t6c-production-activation.yml@refs/heads/main",run_id:"123",run_attempt:"1",iat:now/1000-1,exp:now/1000+300},signed=token(claims),fetchImpl=async()=>({ok:true,json:async()=>({keys:[signed.jwk]})});assert.deepEqual(await verifyGitHubActionsOidc(signed.value,{audience:AUDIENCE,fetchImpl,now:()=>now}),{run_id:"123",run_attempt:"1"});for(const field of ["aud","repository","ref","event_name","environment","workflow_ref"]){const altered=token({...claims,[field]:"wrong"});await assert.rejects(()=>verifyGitHubActionsOidc(altered.value,{audience:AUDIENCE,fetchImpl:async()=>({ok:true,json:async()=>({keys:[altered.jwk]})}),now:()=>now}),/OIDC_/);}});
test("OIDC verifier also permits the exact read-only readiness workflow",async()=>{const now=2_000_000_000_000,claims={iss:"https://token.actions.githubusercontent.com",aud:AUDIENCE,repository:"fyilanli-oss/ads-table-dev",ref:"refs/heads/main",event_name:"workflow_dispatch",environment:"Production",workflow_ref:"fyilanli-oss/ads-table-dev/.github/workflows/e10-t6c-production-readiness.yml@refs/heads/main",run_id:"124",run_attempt:"1",iat:now/1000-1,exp:now/1000+300},signed=token(claims);assert.deepEqual(await verifyGitHubActionsOidc(signed.value,{audience:AUDIENCE,fetchImpl:async()=>({ok:true,json:async()=>({keys:[signed.jwk]})}),now:()=>now}),{run_id:"124",run_attempt:"1"});});
test("server endpoint is POST-only fail-closed and returns injected redacted preflight",async()=>{const result={contract_version:"e10-t6c-activation-preflight-v1",ready:true,values_or_lengths_exposed:false,provider_contact:false,production_contact:false};const handler=createHandler({verify:async token=>{if(token!=="jwt")throw new Error("bad")},preflight:()=>result});const invoke=async(method,authorization)=>{let body="";const res={setHeader(){},end(value=""){body=value;}};await handler({method,headers:{authorization}},res);return{status:res.statusCode,body:JSON.parse(body)}};assert.equal((await invoke("GET","")).status,405);assert.equal((await invoke("POST","")).status,401);assert.deepEqual(await invoke("POST","Bearer jwt"),{status:200,body:result});assert.deepEqual(await invoke("POST","Bearer bad"),{status:403,body:{status:"AUTHORIZATION_REJECTED"}});});
test("workflow client exchanges Actions OIDC and accepts only ready redacted contract",async()=>{const result={contract_version:"e10-t6c-activation-preflight-v1",ready:true,values_or_lengths_exposed:false,provider_contact:false,production_contact:false};const calls=[],fetchImpl=async(url,options)=>{calls.push({url,options});return calls.length===1?{ok:true,json:async()=>({value:"jwt"})}:{ok:true,json:async()=>result}};await run({env:{ACTIONS_ID_TOKEN_REQUEST_URL:"https://actions.invalid/token",ACTIONS_ID_TOKEN_REQUEST_TOKEN:"request"},fetchImpl});assert.match(calls[0].url,new RegExp(`audience=${encodeURIComponent(ENDPOINT)}`));assert.equal(calls[1].url,ENDPOINT);assert.equal(calls[1].options.headers.Authorization,"Bearer jwt");await assert.rejects(()=>run({env:{},fetchImpl}),/ACTIONS_OIDC_UNAVAILABLE/);});
