"use strict";
const fs=require("node:fs"),path=require("node:path"),test=require("node:test"),assert=require("node:assert/strict");
const root=path.join(__dirname,".."),matrix=JSON.parse(fs.readFileSync(path.join(root,"contracts/shopify/e10-t5b-minimum-scope.json"),"utf8")),plan=fs.readFileSync(path.join(root,"codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md"),"utf8");
test("Shopify intake is limited to the two platform attribution values",()=>{assert.deepEqual(matrix.first_slice_scopes,[]);assert.equal(matrix.scope_decision,"deferred_until_shopify_output_contract_and_official_api_revalidation");assert.equal(matrix.candidate_shopify_surface,"Admin GraphQL shopifyqlQuery over ShopifyQL sales schema");assert.equal(matrix.candidate_scope,"read_reports");assert.equal(matrix.candidate_only_not_requested,true);assert.deepEqual(matrix.dimensions,["platform"]);assert.deepEqual(matrix.outputs.map(x=>x.output),["platform_purchase_count","platform_sales_value"]);for(const output of matrix.outputs){assert.match(output.meaning,/Shopify-attributed/);assert.match(output.candidate_shopify_mapping,/ShopifyQL sales schema/);assert.equal(output.resource,null);assert.deepEqual(output.fields,[]);assert.equal(output.scope,null);assert.equal(output.provenance,"shopify_reported_attribution")}});
test("totals, refunds, metadata, PII and broad scopes remain outside intake",()=>{for(const scope of["read_all_orders","read_customers","write_customers","read_customer_events","write_pixels"])assert.ok(matrix.forbidden_first_slice_scopes.includes(scope));assert.equal(matrix.pii_policy,"no_customer_pii");for(const output of["total_purchase_count","total_sales","refund_value","shop_currency","shop_timezone"])assert.equal(matrix.excluded_outputs.find(x=>x.output===output).ui_semantics,"out_of_scope")});
test("overlap display is diagnostic only and never changes Funnel totals",()=>{assert.equal(matrix.presentation.surface,"shopify_native_attribution_comparison_overlap_diagnostic");assert.deepEqual(matrix.presentation.backend_computed,["purchase_difference","sales_difference"]);assert.equal(matrix.presentation.overlap_semantics,"potential_signal_not_duplicate_proof_no_automatic_deduction");assert.equal(matrix.presentation.funnel_total_included,false);assert.equal(matrix.presentation.revenue_input,false)});
test("plan closes T5B without claiming an API or scope",()=>{assert.match(plan,/E10-T5-A\/B ve E10-T5-C1\/C2\/C3 `Done`; parent T5-C `In progress`/);assert.match(plan,/scope, resource ve field kararı ertelendi/);assert.match(plan,/production query yapmadı/)});
test("execution plan is a single readable source for UI and Shopify mapping semantics",()=>{for(const decision of["Resmi Shopify embedded shell: **Zorunlu**","Resmi App Bridge: **Zorunlu**","Özel AdsTable CSS component framework: **Yasak**","Iframe/yabancı-site hissi: **Acceptance failure**"])assert.match(plan,new RegExp(decision.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(plan,/AdsTable'ın iç normalize isimleridir; Shopify API field adı değildir/);assert.match(plan,/shopifyqlQuery.*read_reports/)});
test("T5B display and T5C sequencing are explicit",()=>{for(const column of["Provider Purchase","Shopify-attributed Purchase","Purchase Difference","Provider Sales","Shopify-attributed Sales","Sales Difference"])assert.match(plan,new RegExp(column));assert.match(plan,/overlap sinyali kesin duplicate kanıtı veya otomatik deduction değildir/);assert.match(plan,/E10-T6.*E10-T7.*E10-T8.*E10-T9.*E10-T10.*E11.*E12[\s\S]*yeni uygulama paketi\/PR açılamaz/)});
