"use strict";

const fs=require("node:fs"),path=require("node:path"),test=require("node:test"),assert=require("node:assert/strict");
const plan=fs.readFileSync(path.join(__dirname,"..","codex-input","AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md"),"utf8");
const section=plan.slice(plan.indexOf("### E10-T5-A ürün/UI karar freeze'i"),plan.indexOf("## 15. E11 — Funnel API"));

test("E10 T5A mandates official Shopify components and rejects iframe imitation",()=>{assert.match(section,/güncel ve resmi Shopify UI component sistemine bağlanır/);assert.match(section,/özel AdsTable component karşılığı üretilmez/);assert.match(section,/iframe hissi/);assert.match(section,/özel toolbar\/dropdown\/filter modal\/toggle.*taşınmaz/)});
test("toolbar date comparison and filters are frozen without frontend organic",()=>{assert.match(section,/Time Range → Comparison → Filters/);assert.match(section,/Today.*Yesterday.*Last 7 Days.*This Month/);assert.match(section,/No comparison.*Previous period.*Previous year.*Custom/);assert.match(section,/`Paid`, `Organic`.*frontend filter\/segment değildir/);assert.match(section,/Unattributed.*otomatik `Organic` olmaz/)});
test("funnel and table share backend state and preserve capability hierarchy",()=>{assert.match(section,/aynı backend query\/compare sonucunun iki.*renderer/);for(const hierarchy of ["Campaign → Ad Set → Ad","Campaign → Ad Group → Ad","Campaign → Asset Group","Campaign → Campaign Message","Flow → Flow Message"])assert.match(section,new RegExp(hierarchy));assert.match(section,/Eksik `Ad Group`, `Ad` veya parent uydurulmaz/)});
test("metric vocabulary reflects the approved business meaning",()=>{assert.match(section,/`Sales = satış değeri`/);assert.match(section,/`Spend = reklam harcaması`/);assert.match(section,/`Revenue = Sales - Spend`/);assert.match(section,/aynı değer hem Revenue hem Profit olarak iki kez sunulmaz/);assert.match(section,/`Margin` ilk dilimde kaldırılır/)});
test("provenance and approved T5 A/B/C sequence remain explicit",()=>{for(const family of ["Shopify-reported attribution","provider-reported attribution","AdsTable-calculated","Unattributed"])assert.match(section,new RegExp(family));assert.match(section,/E10-T5-A — Done — Shopify kuralları/);assert.match(section,/E10-T5-B — Done — Shopify'dan ne alınacak, nasıl gösterilecek/);assert.match(section,/E10-T5-C — Product decision required — Shopify'a ne verilecek, nasıl gösterilecek/)});
test("downstream Funnel API and UI cannot reopen the parked frontend Organic model",()=>{assert.match(plan,/E11-T4:[\s\S]*?Parked GA4 Organic capability backend'de korunur fakat Shopify Funnel response'unda Paid\/Organic\/Blend segmenti açılmaz/);assert.match(plan,/E11-T5:[\s\S]*?UI'ya Paid etiketi veya Organic çıkarımı taşınmaz/);assert.match(plan,/Shopify Funnel API `Paid`, `Organic` veya `Blend` UI segmenti üretmez/);assert.match(plan,/E12-T7:[\s\S]*?parked Organic frontend hierarchy\/filter olarak render edilmez/)});
