"use strict";
const crypto=require("node:crypto"),test=require("node:test"),assert=require("node:assert/strict");
const{verifyInstallCallback,consumeInstallState,verifySessionToken,authenticateEmbeddedRequest}=require("../src/shopify/embedded-auth");
const secret="test-secret-not-production",client="client-id";
function jwt(overrides={}){const header={alg:"HS256",typ:"JWT"},payload={aud:client,dest:"https://store-one.myshopify.com/",iss:"https://store-one.myshopify.com/admin",sub:"user-1",sid:"session-1",nbf:1990,exp:2100,...overrides};const encoded=[header,payload].map(v=>Buffer.from(JSON.stringify(v)).toString("base64url"));return `${encoded[0]}.${encoded[1]}.${crypto.createHmac("sha256",secret).update(encoded.join(".")).digest("base64url")}`}
function callback(overrides={}){const query={code:"opaque-code",shop:"store-one.myshopify.com",state:"nonce",timestamp:"2000",...overrides};const message=Object.keys(query).sort().map(key=>`${key}=${query[key]}`).join("&");return{...query,hmac:crypto.createHmac("sha256",secret).update(message).digest("hex")}}
test("install callback requires authentic HMAC and canonical shop",()=>{assert.deepEqual(verifyInstallCallback(callback(),{client_secret:secret}),{authority:"shopify_verified_callback",shop_domain:"store-one.myshopify.com",state:"nonce"});assert.throws(()=>verifyInstallCallback({...callback(),shop:"attacker.myshopify.com"},{client_secret:secret}),/INVALID_INSTALL_HMAC/);assert.throws(()=>verifyInstallCallback(callback({shop:"attacker.example.com"}),{client_secret:secret}),/myshopify.com/)});
test("install state is consumed once and bound to shop and AdsTable user",async()=>{let used=false;const store={consume:async state=>{if(used||state!=="nonce")return null;used=true;return{shop_domain:"store-one.myshopify.com",ads_table_user_id:"ads-user-1",expires_at:2100}}};assert.deepEqual(await consumeInstallState({state_store:store,state:"nonce",shop_domain:"store-one.myshopify.com",now:2000}),{shop_domain:"store-one.myshopify.com",ads_table_user_id:"ads-user-1"});await assert.rejects(()=>consumeInstallState({state_store:store,state:"nonce",shop_domain:"store-one.myshopify.com",now:2000}),/INVALID_OR_EXPIRED/)});
test("session token verification binds signature audience time destination issuer and user",()=>{assert.deepEqual(verifySessionToken(jwt(),{client_id:client,client_secret:secret,now_seconds:2000}),{authority:"shopify_verified_session",shop_domain:"store-one.myshopify.com",shopify_user_id:"user-1",session_id:"session-1",expires_at:2100});assert.throws(()=>verifySessionToken(jwt({aud:"other"}),{client_id:client,client_secret:secret,now_seconds:2000}),/INVALID_SESSION_CLAIMS/);assert.throws(()=>verifySessionToken(jwt({exp:1900}),{client_id:client,client_secret:secret,now_seconds:2000}),/EXPIRED_OR_EARLY/);assert.throws(()=>verifySessionToken(`${jwt()}x`,{client_id:client,client_secret:secret,now_seconds:2000}),/INVALID_SESSION_SIGNATURE/)});
test("embedded auth resolves authority server-side and requires active tenant",async()=>{const context=await authenticateEmbeddedRequest({session_token:jwt(),config:{client_id:client,client_secret:secret,now_seconds:2000},tenant_resolver:async()=>({status:"active",shop_domain:"store-one.myshopify.com",shop_id:"shop-1",workspace_id:"workspace-1"})});assert.deepEqual(context,{contract_version:"e10-t3a-v1",authority:"shopify_verified_session",shop_id:"shop-1",workspace_id:"workspace-1",shopify_user_id:"user-1",expires_at:2100});await assert.rejects(()=>authenticateEmbeddedRequest({session_token:jwt(),config:{client_id:client,client_secret:secret,now_seconds:2000},tenant_resolver:async()=>null}),/SHOP_REAUTHORIZATION_REQUIRED/)});
