"use strict";
const fs=require("node:fs"),path=require("node:path"),test=require("node:test"),assert=require("node:assert/strict");
const {spawnSync}=require("node:child_process");
const source=fs.readFileSync(path.join(__dirname,"../scripts/e10-t6c-vercel-activation.sh"),"utf8");
const readinessPath=path.join(__dirname,"../scripts/e10-t6c-vercel-auth-readiness.sh");
test("activation operator requires separate development and production-deploy approvals before contact",()=>{assert.match(source,/E10_T6C_CONFIRMATION_INVALID/);assert.match(source,/E10_T6C_PRODUCTION_DEPLOY_APPROVAL_REQUIRED/);assert.match(source,/E10-T6C-APPROVE-PRODUCTION-DEPLOY/);assert.match(source,/VERCEL_AUTH_UNAVAILABLE/);assert.ok(source.indexOf("E10_T6C_PRODUCTION_DEPLOY_APPROVAL_REQUIRED")<source.indexOf("VERCEL_AUTH_UNAVAILABLE"));assert.ok(source.indexOf("VERCEL_AUTH_UNAVAILABLE")<source.indexOf("vercel@59.16.0 link"));});
test("operator preflights before one flag write and production deploy",()=>{const pre=source.indexOf("e10-t6c-activation-preflight.js"),write=source.indexOf("env add SHOPIFY_EMBEDDED_PROVIDER_OAUTH_ENABLED production"),deploy=source.indexOf("deploy --prod");assert.ok(pre>0&&write>pre&&deploy>write);assert.equal((source.match(/env add SHOPIFY_EMBEDDED_PROVIDER_OAUTH_ENABLED/g)||[]).length,1);assert.match(source,/trap cleanup EXIT/);});
test("auth readiness check is redacted, local-only, and fail-closed",()=>{
  const unavailable=spawnSync("bash",[readinessPath],{env:{PATH:process.env.PATH},encoding:"utf8"});
  assert.equal(unavailable.status,2);
  assert.equal(unavailable.stdout,"");
  assert.equal(unavailable.stderr,"VERCEL_AUTH_UNAVAILABLE\n");
  const available=spawnSync("bash",[readinessPath],{env:{PATH:process.env.PATH,VERCEL_TOKEN:"never-print-this"},encoding:"utf8"});
  assert.equal(available.status,0);
  assert.equal(available.stdout,"VERCEL_AUTH_AVAILABLE\n");
  assert.equal(available.stderr,"");
  assert.doesNotMatch(available.stdout+available.stderr,/never-print-this/);
  const readinessSource=fs.readFileSync(readinessPath,"utf8");
  assert.doesNotMatch(readinessSource,/\b(curl|npx|vercel)\b/);
});
