'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');
const op=require('../operator/e2-t6-v3');const store=require('../operator/state-store');const {parseArgs}=require('../scripts/e2-t6-v3-operator');const matrix=require('../artifacts/dataset-v2-acceptance/e2-t6-rls/rls-matrix.json');
const repo=path.join(__dirname,'..');
function tmp(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ads-table-t6-'));fs.chmodSync(dir,0o700);return{dir,file:path.join(dir,'state.json')}}
function rows(codes){return codes.map((check_code,i)=>({check_code,actual_count:i,expected_count:i,passed:true}))}
function preflightRows(){return rows(op.PREFLIGHT_CODES)}function postcheckRows(){return rows(op.POSTCHECK_CODES)}
function evidence(){return{operation_code:op.OPERATION,expected_case_count:16,evaluated_case_count:16,passed_case_count:16,failed_case_count:0,unexpected_allow_count:0,fixture_count:2,residue_count:0,dataset_baseline_preserved:true,v1_unchanged:true,snapshots_unchanged:true,oauth_unchanged:true,connected_unchanged:true,encrypted_unchanged:true,missing_encrypted_unchanged:true,orphan_encrypted_unchanged:true,plaintext_unchanged:true,ledger_unchanged:true,overall_passed:true,cases:matrix.map(x=>({case_code:x.case_code,actor:x.actor,operation:x.operation,target:x.target,expected_outcome:x.expected_outcome,actual_outcome:x.expected_outcome,actual_row_count:x.expected_row_count,actual_sqlstate:x.expected_sqlstate_class?'42501':null,passed:true}))}}
function fake(sequence){let calls=0;return{get calls(){return calls},async query(){const value=sequence[calls++];if(value instanceof Error)throw value;return{rows:value}}}}
function binding(){return op.binding(repo)}function state(overrides={}){return{schemaVersion:1,operation:op.OPERATION,version:op.VERSION,approvedMainSha:op.APPROVED_MAIN_SHA,artifactChecksum:binding().artifactChecksum,baselines:{datasetRows:0,v1Rows:1,snapshotRows:2,connectedRows:3,encryptedRows:4},phase:'approval-ready',transactionSent:false,postcheckSent:false,consumed:false,...overrides}}
const verified={verifyRepository(){}};
test('T6 V3 operator binds exact runtime, SQL, fixtures, and approved main',()=>{assert.equal(op.APPROVED_MAIN_SHA,'4960409e3b20d697f75ae2b0d2b4d4872d62ae89');for(const file of ['operator/e2-t6-v3.js','operator/management-api.js','operator/state-store.js','scripts/e2-t6-v3-operator.js','scripts/e2-t6-v3-evidence.js',...Object.values(op.SQL)])assert(op.ARTIFACTS.includes(file));assert.equal(op.PREFLIGHT_CODES.length,21);assert.equal(op.POSTCHECK_CODES.length,19)});
test('T6 V3 CLI accepts only preflight or exact-shaped execute arguments',()=>{assert.deepEqual(parseArgs(['preflight']),{action:'preflight',confirmation:undefined});assert.deepEqual(parseArgs(['execute','--confirm','E2-T6-V3-LIVE']),{action:'execute',confirmation:'E2-T6-V3-LIVE'});for(const args of [[],['preflight','x'],['execute'],['execute','--other','E2-T6-V3-LIVE']])assert.throws(()=>parseArgs(args))});
test('T6 V3 preflight stores five baselines and sends no transaction',async()=>{const t=tmp(),client=fake([preflightRows()]);const report=await op.preflight({repo,stateFile:t.file,client,runTests(){},...verified});assert.equal(report.preflight,'21/21 PASS');assert.equal(client.calls,1);assert.deepEqual(store.readState(t.file,binding(),repo).baselines,{datasetRows:8,v1Rows:6,snapshotRows:20,connectedRows:3,encryptedRows:11})});
test('T6 V3 execute sends transaction and mandatory postcheck exactly once',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const client=fake([[{evidence:evidence()}],postcheckRows()]);const report=await op.execute({repo,stateFile:t.file,client,confirmation:'E2-T6-V3-LIVE',...verified});assert.equal(client.calls,2);assert.equal(report.postcheck,'19/19 PASS');assert.equal(report.transactionRetries,0);assert.equal(store.readState(t.file,binding(),repo).consumed,true)});
test('T6 V3 transaction failure persists a safe terminal outcome after mandatory postcheck',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const client=fake([new Error('ambiguous'),postcheckRows()]);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T6-V3-LIVE',...verified}),error=>error.safeCode==='TRANSACTION_EVIDENCE_FAILED_POSTCHECK_PASS');assert.equal(client.calls,2);assert.equal(store.readState(t.file,binding(),repo).consumed,true);const outcome=JSON.parse(fs.readFileSync(`${t.file}.outcome.json`));assert.deepEqual(outcome,{schemaVersion:1,operation:op.OPERATION,version:op.VERSION,code:'TRANSACTION_EVIDENCE_FAILED_POSTCHECK_PASS'});assert.equal(fs.statSync(`${t.file}.outcome.json`).mode&0o777,0o600)});
test('T6 V3 gates and postcheck placeholders fail closed',()=>{for(const [validator,make] of [[op.validatePreflight,preflightRows],[op.validatePostcheck,postcheckRows]]){assert.doesNotThrow(()=>validator(make()));const bad=make();bad[0].actual_count=-1;assert.throws(()=>validator(bad));const missing=make();missing.pop();assert.throws(()=>validator(missing))}const sql=fs.readFileSync(path.join(repo,op.SQL.postcheck),'utf8');assert.doesNotThrow(()=>op.postcheckSql(sql,state().baselines));assert.throws(()=>op.postcheckSql(sql.replace('(-1)::bigint','0::bigint'),state().baselines),/exactly five/)});

test('T6 V3 preflight reports safe query and gate stages without creating state',async()=>{
  for(const [value,code] of [[new Error('raw transport detail'),'PREFLIGHT_QUERY_FAILED'],[[{check_code:'UNKNOWN',actual_count:0,expected_count:0,passed:false}],'PREFLIGHT_GATES_FAILED']]){
    const t=tmp(),client=fake([value]);
    await assert.rejects(op.preflight({repo,stateFile:t.file,client,runTests(){},...verified}),error=>error.safeCode===code);
    assert.equal(client.calls,1);assert.equal(fs.existsSync(t.file),false);assert.equal(fs.existsSync(`${t.file}.outcome.json`),false);
  }
});
