'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const root=path.join(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const inventory=require('../artifacts/dataset-v2-acceptance/e2-t7-cleanup/fixture-inventory.json');
const contract=require('../artifacts/dataset-v2-acceptance/e2-t7-cleanup/no-change-contract.json');
const {ROW_FIELDS,OUTPUT_FIELDS,CHECK_CODES,buildEvidence}=require('../scripts/e2-t7-cleanup-evidence');
const baseline=read('docs/security/sql/E2_T7_BASELINE.sql'),finalSql=read('docs/security/sql/E2_T7_FINAL_CHECK.sql'),plan=read('codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md');
const files=['artifacts/dataset-v2-acceptance/e2-t7-cleanup/fixture-inventory.json','artifacts/dataset-v2-acceptance/e2-t7-cleanup/no-change-contract.json','docs/security/E2_T7_CLEANUP_NO_CHANGE_RUNBOOK.md','docs/security/sql/E2_T7_BASELINE.sql','docs/security/sql/E2_T7_FINAL_CHECK.sql','scripts/e2-t7-cleanup-evidence.js'];
const expectedKeys=['meta:e2_t3_static_v1_account:paid:none:campaign:e2_t3_static_v1_campaign:ad:e2_t3_static_v1_ad','meta:e2_t4_same_key_v1_account:paid:none:campaign:e2_t4_same_key_v1_campaign:ad:e2_t4_same_key_v1_ad'];
const strip=s=>s.replace(/--.*$/gm,'').trim();
function rows(final=false){return CHECK_CODES.map((check_code,i)=>{let n=['DATASET_V2_BASELINE','DATASET_V1_BASELINE','SNAPSHOT_BASELINE'].includes(check_code)?10+i:0;if(['LEDGER_TOTAL'].includes(check_code))n=37;if(['CONNECTED_CONNECTIONS','ENCRYPTED_TOKEN_ROWS'].includes(check_code))n=7;if(check_code==='DATASET_V2_SCHEMA_STATE')n=26;if(check_code==='DATASET_V2_RLS_POLICY_GRANT_STATE')n=5;return{check_code,actual_count:n,expected_count:n,comparison:final?'eq':(['DATASET_V2_BASELINE','DATASET_V1_BASELINE','SNAPSHOT_BASELINE'].includes(check_code)?'capture':'eq'),passed:true};});}
test('all E2-T7 artifacts exist',()=>files.forEach(f=>assert(fs.existsSync(path.join(root,f)),f)));
test('fixture inventory is exact and rollback-only',()=>{assert.deepEqual(Object.keys(inventory),['evidence_version','namespaces']);assert.equal(inventory.namespaces.length,4);inventory.namespaces.forEach((x,i)=>{assert.deepEqual(Object.keys(x),['task','match_mode','exact_entity_key','escaped_prefix','expected_final_count','normal_cleanup','cleanup_statement_allowed']);assert.equal(x.task,`E2-T${i+3}`);assert.equal(x.expected_final_count,0);assert.equal(x.normal_cleanup,'transaction_rollback');assert.equal(x.cleanup_statement_allowed,false);});assert.deepEqual(inventory.namespaces.slice(0,2).map(x=>x.exact_entity_key),expectedKeys);assert.deepEqual(inventory.namespaces.slice(2).map(x=>x.escaped_prefix),['e2\\_t5\\_rejection\\_v1:','e2\\_t6\\_rls\\_v1:']);});
test('inventory values are reverified in merged source SQL',()=>{for(const key of expectedKeys)assert.match(read(key.includes('t3')?'docs/security/sql/E2_T3_ROUNDTRIP_TRANSACTION.sql':'docs/security/sql/E2_T4_UPSERT_TRANSACTION.sql'),new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(read('docs/security/sql/E2_T5_REJECTION_TRANSACTION.sql'),/e2_t5_rejection_v1/);assert.match(read('docs/security/sql/E2_T6_RLS_TRANSACTION.sql'),/e2_t6_rls_v1/);});
test('no-change contract has exact object allowlists',()=>{assert.deepEqual(Object.keys(contract),['evidence_version','checks']);assert.deepEqual(contract.checks.map(x=>x.check_code),CHECK_CODES);for(const x of contract.checks){assert.deepEqual(Object.keys(x),['check_code','comparison','expected_source','required','safe_output']);assert.equal(x.required,true);assert.equal(x.safe_output,true);}});
test('SQL files are one read-only WITH SELECT statement',()=>{for(const sql of [baseline,finalSql]){const s=strip(sql),syntax=s.replace(/'(?:''|[^'])*'/g,"''");assert.match(s,/^with\b/i);assert.equal((s.match(/;/g)||[]).length,1);assert.doesNotMatch(syntax,/\b(?:insert\s+into|update\s+\w|delete\s+from|truncate|alter|create|drop|grant|revoke|call|execute|perform|do\s+\$|begin\s*;|commit\s*;|rollback\s*;)\b/i);}});
test('SQL selectors are exact or escaped and never broad wildcard',()=>{for(const sql of [baseline,finalSql]){for(const key of expectedKeys)assert.match(sql,new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(sql,/like 'e2\\_t5\\_rejection\\_v1:%' escape '\\'/);assert.match(sql,/like 'e2\\_t6\\_rls\\_v1:%' escape '\\'/);assert.doesNotMatch(sql,/'%e2%'/i);}});
test('final has exactly three scalar negative placeholders',()=>{assert.equal((finalSql.match(/\(-1\)::bigint/g)||[]).length,3);for(const code of ['DATASET_V2_BASELINE','DATASET_V1_BASELINE','SNAPSHOT_BASELINE'])assert.match(finalSql,new RegExp(`'${code}'`));});
test('all contract checks occur in both SQL files',()=>{for(const code of CHECK_CODES){assert.match(baseline,new RegExp(`'${code}'`));assert.match(finalSql,new RegExp(`'${code}'`));}});
test('converter emits only safe allowlisted summary',()=>{const out=buildEvidence(rows(),rows(true));assert.deepEqual(Object.keys(out),OUTPUT_FIELDS);assert.equal(out.status,'PASS');assert.equal(out.fixture_residue_count,0);assert.equal(out.rollback_cleanup_verified,true);});
test('converter rejects missing extra duplicate unknown and failed checks',()=>{for(const mutate of [x=>x.pop(),x=>x.push({...x[0]}),x=>x[0].extra=true,x=>x[0].check_code=x[1].check_code,x=>x[0].passed=false]){const b=rows(),f=rows(true);mutate(f);assert.throws(()=>buildEvidence(b,f),/E2_T7_EVIDENCE_REJECTED/);}});
test('converter rejects residue, baseline drift, negative and fractional counts',()=>{let b=rows(),f=rows(true);f.find(x=>x.check_code==='E2_T5_RESIDUE').actual_count=1;f.find(x=>x.check_code==='E2_T5_RESIDUE').passed=false;assert.throws(()=>buildEvidence(b,f));b=rows();f=rows(true);f.find(x=>x.check_code==='DATASET_V2_BASELINE').actual_count++;f.find(x=>x.check_code==='DATASET_V2_BASELINE').expected_count++;assert.throws(()=>buildEvidence(b,f));for(const bad of [-1,1.5]){b=rows();f=rows(true);f[0].actual_count=bad;assert.throws(()=>buildEvidence(b,f));}});
test('converter rejects credential PII UUID and raw-row patterns without echo',()=>{for(const leak of ['postgresql://host/db','person@example.invalid','123e4567-e89b-42d3-a456-426614174000','raw_row']){const b=rows(),f=rows(true);f[0].unknown=leak;let error;try{buildEvidence(b,f)}catch(e){error=e}assert(error);assert.doesNotMatch(error.message,new RegExp(leak.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}});
test('committed artifacts contain no secrets identities production counts or raw rows',()=>{const text=files.map(read).join('\n');assert.doesNotMatch(text,/postgres(?:ql)?:\/\/|authorization\s*:|bearer\s+|-----BEGIN [A-Z ]*PRIVATE KEY-----|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/i);});
test('execution plan preserves E2 statuses and complete T7 mirror',()=>{for(const n of [1,2])assert.match(plan,new RegExp(`E2-T${n} — `+'`Done`'));for(const n of [3,4,5,6,7,8])assert.match(plan,new RegExp(`E2-T${n} — `+'`Verification`'));for(const heading of ['Amaç','Mevcut durum','Planlanan durum','Kapsam','Kapsam dışı','Bağımlılıklar','Uygulama adımları','Kabul kriterleri','Test planı','Rollback planı','Gözlemlenebilirlik','Güvenlik ve veri etkisi','Planlanan','Gerçekleşen','Sapmalar','Evidence','Durum'])assert.match(plan,new RegExp(`\\*\\*${heading}:`));});
test('service role requires the exact seven independent privileges in both SQL checks',()=>{
  const privileges=['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'];
  for(const sql of [baseline,finalSql]){
    const service=sql.match(/case when\s+([\s\S]*?)\s+then 1 else 0 end service_ok/);
    assert(service,'service_ok case must exist');
    assert.deepEqual([...service[1].matchAll(/has_table_privilege\('service_role','public\.performance_dataset_rows_v2','([^']+)'\)/g)].map(x=>x[1]),privileges);
    assert.equal((service[1].match(/\band\s+has_table_privilege/g)||[]).length,6);
    assert.doesNotMatch(service[1],/has_table_privilege\('service_role','public\.performance_dataset_rows_v2','[^']*,[^']*'\)/);
    for(const omitted of privileges){
      const simulated=privileges.filter(value=>value!==omitted).map(()=>true);
      assert.equal(simulated.length===privileges.length&&simulated.every(Boolean),false);
    }
    assert.match(sql,/case when has_table_privilege\('anon','public\.performance_dataset_rows_v2','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'\) then 0 else 1 end anon_ok/);
    assert.match(sql,/case when has_table_privilege\('authenticated','public\.performance_dataset_rows_v2','SELECT'\) and not has_table_privilege\('authenticated','public\.performance_dataset_rows_v2','INSERT,UPDATE,DELETE,TRUNCATE'\) then 1 else 0 end authenticated_ok/);
    assert.match(sql,/'DATASET_V2_RLS_POLICY_GRANT_STATE',[\s\S]*,5,'eq'/);
  }
});
