'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const root=path.join(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const matrix=require('../artifacts/dataset-v2-acceptance/e2-t6-rls/rls-matrix.json');
const fixture=require('../artifacts/dataset-v2-acceptance/e2-t6-rls/fixture-contract.json');
const recovery=require('../artifacts/dataset-v2-acceptance/e2-t6-rls/recovery-v1.json');
const {TOP_LEVEL_FIELDS,CASE_FIELDS,buildEvidence}=require('../scripts/e2-t6-rls-evidence');
const migration=read('supabase/migrations/20260816101220_create_performance_dataset_rows_v2.sql');const metadata=require('../artifacts/dataset-v2-acceptance/20260824-metadata-acceptance/rls-grants.json');
const preflight=read('docs/security/sql/E2_T6_RLS_PREFLIGHT.sql'),transaction=read('docs/security/sql/E2_T6_RLS_TRANSACTION.sql'),postcheck=read('docs/security/sql/E2_T6_RLS_POSTCHECK.sql'),plan=read('codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md');
const files=['artifacts/dataset-v2-acceptance/e2-t6-rls/rls-matrix.json','artifacts/dataset-v2-acceptance/e2-t6-rls/fixture-contract.json','docs/security/E2_T6_RLS_ACCEPTANCE_RUNBOOK.md','docs/security/sql/E2_T6_RLS_PREFLIGHT.sql','docs/security/sql/E2_T6_RLS_TRANSACTION.sql','docs/security/sql/E2_T6_RLS_POSTCHECK.sql','scripts/e2-t6-rls-evidence.js'];
const codes=['USER_A_READ_OWN','USER_A_READ_USER_B','USER_B_READ_OWN','USER_B_READ_USER_A','ANON_READ_USER_A','ANON_READ_USER_B','USER_A_INSERT','USER_A_UPDATE_OWN','USER_A_DELETE_OWN','USER_B_INSERT','USER_B_UPDATE_OWN','USER_B_DELETE_OWN','SERVICE_ROLE_INSERT_A','SERVICE_ROLE_INSERT_B','SERVICE_ROLE_READ_A','SERVICE_ROLE_READ_B'];
function sample(){const cases=matrix.map(x=>({case_code:x.case_code,actor:x.actor,operation:x.operation,target:x.target,expected_outcome:x.expected_outcome,actual_outcome:x.expected_outcome,actual_row_count:x.expected_row_count,actual_sqlstate:x.expected_sqlstate_class?'42501':null,passed:true}));return{operation_code:'e2_t6_rls_v1',expected_case_count:16,evaluated_case_count:16,passed_case_count:16,failed_case_count:0,unexpected_allow_count:0,fixture_count:2,residue_count:0,dataset_baseline_preserved:true,v1_unchanged:true,snapshots_unchanged:true,oauth_unchanged:true,connected_unchanged:true,encrypted_unchanged:true,missing_encrypted_unchanged:true,orphan_encrypted_unchanged:true,plaintext_unchanged:true,ledger_unchanged:true,overall_passed:true,cases};}
const strip=sql=>sql.replace(/--.*$/gm,'').trim();
test('all artifacts exist and contracts are preparation-only',()=>{for(const f of files)assert(fs.existsSync(path.join(root,f)),f);assert.equal(fixture.operation_code,'e2_t6_rls_v1');assert.equal(fixture.fixture_count,2);assert.equal(fixture.selection.required_distinct_count,2);});
test('matrix is the exact deterministic 16-case allowlist',()=>{assert.deepEqual(matrix.map(x=>x.case_code),codes);assert.equal(new Set(codes).size,16);for(const x of matrix)assert.deepEqual(Object.keys(x),['case_code','actor','operation','target','expected_outcome','expected_row_count','expected_sqlstate_class','evidence_mode']);});
test('matrix exactly reflects committed migration and metadata policy/grants',()=>{assert.match(migration,/enable row level security/i);assert.doesNotMatch(migration,/force row level security/i);assert.match(migration,/for select\s+to authenticated\s+using \(\(select auth\.uid\(\)\) = user_id\)/i);assert.match(migration,/revoke all[^;]+from anon, authenticated/i);assert.match(migration,/grant select[^;]+to authenticated/i);assert.match(migration,/grant all[^;]+to service_role/i);assert.equal(metadata.rls.live_enabled,true);assert.equal(metadata.rls.live_forced,false);assert.deepEqual(metadata.privileges.anon.live,[]);assert.deepEqual(metadata.privileges.authenticated.live,['SELECT']);assert.equal(metadata.privileges.authenticated.mutation_allowed,false);assert(metadata.privileges.service_role.live.includes('INSERT'));});
test('preflight and postcheck are single read-only WITH SELECT statements',()=>{for(const sql of [preflight,postcheck]){const clean=strip(sql);assert.match(clean,/^with\b/i);assert.equal((clean.match(/;/g)||[]).length,1);assert.doesNotMatch(clean,/\b(?:insert\s+into|update\s+\w|delete\s+from|alter\s+table|create\s+table|drop\s+table|truncate\s+table|call\s+|do\s+\$|begin\s*;|commit\s*;|rollback\s*;)\b/i);}for(const gate of ['LEDGER_TOTAL','RLS_ENABLED_NOT_FORCED','EXACT_OWN_SELECT_POLICY','ANON_NO_PRIVILEGE','AUTHENTICATED_SELECT','AUTHENTICATED_NO_MUTATION','SERVICE_ROLE_ACCESS','DISTINCT_ELIGIBLE_USERS','E2_T6_RESIDUE','DATASET_V2_ROWS','DATASET_V1_ROWS','SNAPSHOT_ROWS','OAUTH_ROWS','PLAINTEXT_TOKENS','CONSTRAINT_INDEX_STATE'])assert.match(preflight,new RegExp(`'${gate}'`));assert.match(postcheck,/values \(\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint\)/);});
test('transaction has one BEGIN, final ROLLBACK, no COMMIT, and pg_temp-only DDL',()=>{const clean=strip(transaction);assert.match(clean,/^begin;/i);assert.match(clean,/rollback;$/i);assert.equal((clean.match(/^begin;/gim)||[]).length,1);assert.equal((clean.match(/^rollback;/gim)||[]).length,1);assert.doesNotMatch(clean,/^commit\s*;/im);assert.equal((transaction.match(/create temp table pg_temp\./gi)||[]).length,3);assert.equal((transaction.match(/on commit drop/gi)||[]).length,3);assert.doesNotMatch(transaction,/create\s+(?:table|view|function|schema)\s+(?!pg_temp\.)/i);});

test('temporary grants are closed to the three actors and target no persistent relation',()=>{const grants=[...transaction.matchAll(/^grant\s+([^;]+?)\s+on\s+([^;]+?)\s+to\s+([^;]+);$/gim)].map(x=>({privileges:x[1].trim(),target:x[2].trim(),roles:x[3].split(',').map(y=>y.trim())}));assert.deepEqual(grants,[{privileges:'insert, select',target:'pg_temp.e2_t6_rls_evidence',roles:['authenticated','anon','service_role']},{privileges:'select',target:'pg_temp.e2_t6_rls_actors',roles:['service_role']}]);assert(grants[0].roles.includes('service_role'));for(const grant of grants)assert.match(grant.target,/^pg_temp\.e2_t6_rls_(?:evidence|actors)$/);assert.doesNotMatch(transaction,/^grant[^;]+on\s+(?:public|auth)\./gim);});
test('actor identities are selected once before role switching and isolated from evidence',()=>{const firstSwitch=transaction.indexOf('set local role service_role;');assert(firstSwitch>0);const before=transaction.slice(0,firstSwitch),fixtureSection=transaction.slice(firstSwitch,transaction.indexOf('reset role;',firstSwitch));assert.equal((transaction.match(/auth\.users/gi)||[]).length,1);assert.match(before,/insert into pg_temp\.e2_t6_rls_actors[\s\S]+from public\.users[\s\S]+auth\.users/);assert.doesNotMatch(transaction.slice(firstSwitch),/auth\.users|from public\.users/);assert.doesNotMatch(fixtureSection,/auth\.users|public\.users/);assert.match(transaction,/create temp table pg_temp\.e2_t6_rls_actors[\s\S]+on commit drop/);assert.match(transaction,/count\(\*\)=2 and count\(distinct internal_user_id\)=2[\s\S]+array\['user_a','user_b'\]/);assert.match(transaction,/grant select on pg_temp\.e2_t6_rls_actors to service_role/);const finalProjection=transaction.slice(transaction.indexOf('with summary as ('));assert.doesNotMatch(finalProjection,/internal_user_id|e2_t6_rls_actors/);});
test('SQL overall_passed requires every parity boolean',()=>{const parity=transaction.match(/parity as \(select([\s\S]*?)from pg_temp\.e2_t6_rls_baseline/);assert(parity);for(const field of ['dataset_baseline_preserved','v1_unchanged','snapshots_unchanged','oauth_unchanged','connected_unchanged','encrypted_unchanged','missing_encrypted_unchanged','orphan_encrypted_unchanged','plaintext_unchanged','ledger_unchanged']){assert.match(parity[1],new RegExp(`${field}\\b`));assert.match(transaction,new RegExp(`'overall_passed'[\\s\\S]*p\\.${field}\\b`));}});
test('two distinct eligible users and transaction-local role/claims are fail-closed',()=>{assert.match(transaction,/order by u\.id limit 2/);assert.match(transaction,/count\(\*\)=2 and count\(distinct internal_user_id\)=2/);assert.match(transaction,/STOP/);assert((transaction.match(/set local role authenticated/gi)||[]).length===2);assert((transaction.match(/set_config\('request\.jwt\.claim\.sub'.+true\)/gi)||[]).length>=4);assert((transaction.match(/reset role/gi)||[]).length>=4);assert.doesNotMatch(transaction,/set\s+(?!local\s+role)[^;]*request\.jwt/i);});
test('each denied mutation has a separate nested exception and safe diagnostics only',()=>{for(const code of codes.filter(x=>/^USER_[AB]_(?:INSERT|UPDATE|DELETE)/.test(x)))assert.match(transaction,new RegExp(`\\$case_${code.toLowerCase()}\\$`));assert.equal((transaction.match(/when insufficient_privilege then/gi)||[]).length,8);assert.doesNotMatch(transaction,/SQLERRM|MESSAGE_TEXT|PG_EXCEPTION_DETAIL|PG_EXCEPTION_HINT|PG_EXCEPTION_CONTEXT|on conflict/i);});
test('single final redacted evidence response contains exact allowlists',()=>{assert.equal((transaction.match(/select evidence from payload/gi)||[]).length,1);for(const f of TOP_LEVEL_FIELDS)assert.match(transaction,new RegExp(`'${f}'`));for(const f of CASE_FIELDS)assert.match(transaction,new RegExp(`'${f}'`));assert.match(transaction,/jsonb_agg\([\s\S]*order by array_position/);});
test('converter accepts exact evidence and rejects contract/leakage failures',()=>{assert.equal(buildEvidence(sample()).status,'PASS');const variants=[];let x=sample();x.cases.pop();variants.push(x);x=sample();x.cases[15]={...x.cases[0]};variants.push(x);x=sample();x.extra=true;variants.push(x);x=sample();x.cases[0].actor='user_b';variants.push(x);x=sample();x.cases[1].actual_row_count=1;variants.push(x);x=sample();x.cases[4].actual_row_count=1;variants.push(x);x=sample();x.cases[6].actual_outcome='ALLOWED';variants.push(x);x=sample();x.cases[12].actual_outcome='DENIED_BY_PRIVILEGE';variants.push(x);x=sample();x.residue_count=1;variants.push(x);for(const field of ['dataset_baseline_preserved','v1_unchanged','snapshots_unchanged','oauth_unchanged','connected_unchanged','encrypted_unchanged','missing_encrypted_unchanged','orphan_encrypted_unchanged','plaintext_unchanged','ledger_unchanged']){x=sample();x[field]=false;x.overall_passed=false;variants.push(x);}for(const v of variants)assert.throws(()=>buildEvidence(v));});
test('committed artifacts contain no concrete identity, secret, URI, JWT, or raw errors',()=>{const text=files.map(read).join('\n');assert.doesNotMatch(text,/postgres(?:ql)?:\/\/|authorization\s*:|bearer\s+|-----BEGIN [A-Z ]*PRIVATE KEY-----|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/i);assert.doesNotMatch(transaction,/SQLERRM|MESSAGE_TEXT|PG_EXCEPTION_DETAIL|PG_EXCEPTION_HINT|PG_EXCEPTION_CONTEXT/);});
test('execution plan preserves exact E2 statuses and E2-T6 mirror',()=>{for(const n of [1,2,3,4,5])assert.match(plan,new RegExp(`E2-T${n} — `+'`Done`'));for(const n of [6,7,8])assert.match(plan,new RegExp(`E2-T${n} — `+'`Not started`'));assert.match(plan,/E2-T6 task aynası/);assert.match(plan,/Canlı preflight çalıştırılmadı/);});

test('E2-C1 captured provider-token parity is fail-closed',()=>{for(const sql of [preflight,transaction,postcheck])assert.doesNotMatch(sql,/(?:CONNECTED_CONNECTIONS|ENCRYPTED_TOKEN_ROWS)[^\n]*,\s*7\b/);for(const code of ['MISSING_ENCRYPTED','ORPHAN_ENCRYPTED','PLAINTEXT_TOKENS','CONNECTION_TOKEN_PARITY'])assert.match(preflight,new RegExp(`'${code}'`));assert.match(preflight,/'CONNECTED_CONNECTIONS'[^\n]*'capture'/);assert.match(transaction,/connected_count[\s\S]*encrypted_count/);for(const field of ['connected_unchanged','encrypted_unchanged','missing_encrypted_unchanged','orphan_encrypted_unchanged','plaintext_unchanged'])assert.match(transaction,new RegExp(`'${field}'`));assert.match(postcheck,/connected_rows/);assert.match(postcheck,/encrypted_rows/);assert.match(transaction,/rollback;\s*$/i);assert.throws(()=>buildEvidence({...sample(),connection_count:1}),/counts are forbidden/);});

test('T6 runbook and postcheck use exactly five ordered operator-local baselines',()=>{assert.equal((postcheck.match(/\(-1\)::bigint/g)||[]).length,5);const runbook=read('docs/security/E2_T6_RLS_ACCEPTANCE_RUNBOOK.md');assert.match(runbook,/exactly five operator-local baselines in this order: Dataset V2, V1, snapshot, connected, encrypted/);assert.match(runbook,/replace exactly five `-1` placeholders[\s\S]*in this order: Dataset V2, V1, snapshot, connected, encrypted/);assert.match(runbook,/Actual provider counts are never shared or committed/);});
test('T6 recovery proves no-change without claiming live acceptance',()=>{assert.deepEqual(recovery,{evidence_version:'e2-t6-recovery-v1',operation:'e2_t6_rls_v1',recovery_kind:'distinct_read_only_no_change',approved_main_sha:'8ab5e240e65685545250571128f90e3ccbd8ecaf',transaction_requests:1,transaction_retries:0,postcheck_intent_recorded:true,capsule_state:'CONSUMED',recovery_requests:1,recovery_retries:0,recovery_gates:'19/19 PASS',e2_t6_residue_zero:true,total_e2_residue_zero:true,persistent_evidence_objects_zero:true,protected_baselines_unchanged:true,live_acceptance_claimed:false,contains_production_counts:false,contains_identity_or_row_data:false});assert.match(plan,/E2-C3 — E2-T6 fail-closed recovery kaydı/);assert.match(plan,/16-case RLS acceptance PASS yerine geçmez/);});
