'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { normalizeResponse, createManagementClient } = require('../operator/management-api');
const store = require('../operator/state-store');
const op = require('../operator/e2-t5-v2');
const { buildEvidence } = require('../scripts/e2-t5-v2-evidence');
const matrix = require('../artifacts/dataset-v2-acceptance/e2-t5-rejection/rejection-matrix.json');
const repo = path.join(__dirname, '..');
function tmp() { const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ads-table-')); fs.chmodSync(dir,0o700); return {dir,file:path.join(dir,'state.json')}; }
function gates(count=18) { const codes=['DATASET_ROWS','V1_ROWS','SNAPSHOT_ROWS','CONNECTED_CONNECTIONS','ENCRYPTED_TOKEN_ROWS',...Array.from({length:13},(_,i)=>`GATE_${i}`)]; return codes.slice(0,count).map((check_code,i)=>({check_code,actual_count:i,expected_count:i,passed:true})); }
function evidence() { return {operation_code:op.OPERATION,expected_case_count:35,evaluated_case_count:35,passed_case_count:35,failed_case_count:0,unexpected_accept_count:0,residue_count:0,dataset_unchanged:true,v1_unchanged:true,snapshots_unchanged:true,oauth_unchanged:true,connected_unchanged:true,encrypted_unchanged:true,missing_encrypted_unchanged:true,orphan_encrypted_unchanged:true,plaintext_unchanged:true,ledger_unchanged:true,overall_passed:true,cases:matrix.map(x=>({case_code:x.case_code,expected_sqlstate:x.expected_sqlstate,actual_sqlstate:x.expected_sqlstate,expected_constraints:x.expected_constraints,actual_constraint:x.expected_constraints[0]||null,expected_column:x.expected_column,actual_column:x.expected_column,rejected:true,passed:true}))}; }
function fake(sequence) { let calls=0; return {get calls(){return calls;},async query(){const next=sequence[calls++];if(next instanceof Error)throw next;return {rows:next};}}; }
function binding(){return op.binding(repo);}
function state(overrides={}) { return {schemaVersion:1,operation:op.OPERATION,version:op.VERSION,approvedMainSha:op.APPROVED_MAIN_SHA,artifactChecksum:binding().artifactChecksum,baselines:{datasetRows:0,v1Rows:1,snapshotRows:2,connectedRows:3,encryptedRows:4},phase:'approval-ready',transactionSent:false,postcheckSent:false,consumed:false,...overrides}; }

test('normalizer accepts HTTP 200/201 object and array wrappers and selects only final SELECT',()=>{assert.deepEqual(normalizeResponse(200,JSON.stringify([{command:'BEGIN'},{rows:[{ok:true}]}])).rows,[{ok:true}]);assert.deepEqual(normalizeResponse(201,{result:[{command:'UPDATE'},{result:[{ok:true}]}]}).rows,[{ok:true}]);assert.deepEqual(normalizeResponse(200,[{check_code:'A',passed:true}]).rows,[{check_code:'A',passed:true}]);assert.deepEqual(normalizeResponse(201,{result:[{check_code:'A',passed:true}]}).rows,[{check_code:'A',passed:true}]);});
test('normalizer fails closed for HTTP errors, malformed JSON, missing SELECT, and unknown shapes',()=>{for(const status of [400,401,403,500])assert.throws(()=>normalizeResponse(status,'[]'),new RegExp(String(status)));assert.throws(()=>normalizeResponse(200,'{'),/malformed/);assert.throws(()=>normalizeResponse(200,'[]'),/no result/);assert.throws(()=>normalizeResponse(200,'{}'),/Unknown/);assert.throws(()=>normalizeResponse(200,'[{"command":"ROLLBACK"}]'),/not SELECT/);});
test('client sends once, never retries, counts requests, and applies timeout',async()=>{let options;const client=createManagementClient({token:'secret-token',projectRef:'secret-ref',timeoutMs:10,transport:async(_url,o)=>{options=o;return{status:200,text:async()=>JSON.stringify([{rows:[{ok:true}]}])};}});await client.query('select 1');assert.equal(client.requestCount,1);assert.match(options.headers.authorization,/Bearer/);const timeout=createManagementClient({token:'x',projectRef:'y',timeoutMs:5,transport:(_u,o)=>new Promise((_r,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(new Error(),{name:'AbortError'}))))});await assert.rejects(timeout.query('x'),/timed out/);assert.equal(timeout.requestCount,1);});
test('normalizer errors disclose safe shape metadata, never raw response values',()=>{const secret='https://secret-project.example/token-value';let error;try{normalizeResponse(200,{unexpected:secret});}catch(e){error=e;}assert(error);assert.doesNotMatch(JSON.stringify(error.safeMetadata),/secret-project|token-value|https/);});
test('state roundtrip enforces outside-repo, 700 directory, 600 file, exact schema and binding',()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);assert.equal(fs.statSync(t.dir).mode&0o777,0o700);assert.equal(fs.statSync(t.file).mode&0o777,0o600);assert.equal(store.readState(t.file,binding(),repo).phase,'approval-ready');assert.throws(()=>store.readState(path.join(t.dir,'missing'),binding(),repo),/missing/);fs.chmodSync(t.file,0o644);assert.throws(()=>store.readState(t.file,binding(),repo),/600/);assert.throws(()=>store.writeState(path.join(repo,'bad'),state(),binding(),repo),/outside/);});
test('state rejects missing/extra baseline, malformed state, changed SHA/checksum, and consumed inconsistency',()=>{const good=state();for(const mutate of [s=>{delete s.baselines.datasetRows;},s=>{s.baselines.extra=1;},s=>{s.approvedMainSha='0'.repeat(40);},s=>{s.artifactChecksum='bad';},s=>{s.consumed=true;}]){const value=structuredClone(good);mutate(value);assert.throws(()=>store.validateState(value,binding()));}});
test('preflight success stores five baselines without transaction and failures store nothing',async()=>{const t=tmp(),client=fake([gates()]);const report=await op.preflight({repo,stateFile:t.file,client,runTests(){}});assert.equal(report.status,'APPROVAL_READY');assert.equal(client.calls,1);assert.deepEqual(Object.keys(store.readState(t.file,binding(),repo).baselines),store.BASELINES);const bad=tmp();await assert.rejects(op.preflight({repo,stateFile:bad.file,client:fake([gates(17)]),runTests(){}}),/18/);assert.equal(fs.existsSync(bad.file),false);});
test('execute requires exact confirmation and existing complete approval state before transaction',async()=>{const t=tmp(),client=fake([]);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'}),/missing/);store.writeState(t.file,state(),binding(),repo);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'wrong'}),/confirmation/);assert.equal(client.calls,0);});
test('execute sends transaction and mandatory postcheck exactly once, then rejects state reuse',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const client=fake([[{evidence:evidence()}],Array.from({length:11},(_,i)=>({check_code:`P${i}`,passed:true}))]);const report=await op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'});assert.equal(client.calls,2);assert.equal(report.transactionRetries,0);assert.equal(report.postcheckRetries,0);assert.equal(store.readState(t.file,binding(),repo).consumed,true);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'}),/cannot send/);assert.equal(client.calls,2);});
test('converter failure still performs exactly one postcheck and consumes state',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const bad=evidence();bad.cases.pop();const client=fake([[{evidence:bad}],Array.from({length:11},()=>({passed:true}))]);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'}),/mandatory postcheck completed/);assert.equal(client.calls,2);assert.equal(store.readState(t.file,binding(),repo).consumed,true);});
test('postcheck failure is fail-closed, exact once, and consumed',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const client=fake([[{evidence:evidence()}],[{passed:false}]]);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'}),/postcheck failed/i);assert.equal(client.calls,2);assert.equal(store.readState(t.file,binding(),repo).consumed,true);});
test('transaction transport failure is never retried and mandatory postcheck still runs once',async()=>{const t=tmp();store.writeState(t.file,state(),binding(),repo);const client=fake([new Error('ambiguous'),Array.from({length:11},()=>({passed:true}))]);await assert.rejects(op.execute({repo,stateFile:t.file,client,confirmation:'E2-T5-V2-LIVE'}),/postcheck completed/);assert.equal(client.calls,2);});
test('V2 converter preserves exact 35-case, 32 CHECK + 3 NOT NULL contract',()=>{assert.equal(buildEvidence(evidence()).evidence_version,op.VERSION);assert.equal(matrix.filter(x=>x.expected_sqlstate==='23514').length,32);assert.equal(matrix.filter(x=>x.expected_sqlstate==='23502').length,3);});
