'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),test=require('node:test');
const op=require('../operator/e2-t8-capture'),{parseArgs}=require('../scripts/e2-t8-capture-operator');const repo=path.join(__dirname,'..'),FP='a'.repeat(64);
const inventory=[{object_key:'relation:accounts',object_class:'relation',ownership_class:'application_owned',fingerprint:FP},{object_key:'relation:spatial_ref_sys',object_class:'relation',ownership_class:'managed_extension_owned',fingerprint:'b'.repeat(64)}];
function tmp(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'e2-t8-op-'));return{dir,file:path.join(dir,'state.json')}}
const verified={verifyRepository(){}};
test('E2-T8 capture operator binds approved main and complete artifacts',()=>{assert.equal(op.APPROVED_MAIN_SHA,'a5e0917acf650e753161a97a85baf9e851d967b9');for(const f of [op.SQL,'package.json','scripts/e2-t8-schema-capture.js','security/e2-t8-captured-schema-validator.js'])assert(op.ARTIFACTS.includes(f));assert.equal(op.checksum(repo).length,64)});
test('E2-T8 inventory CLI enables the pinned Node proxy boundary',()=>{const script=require('../package.json').scripts['e2:t8:capture:preflight'];assert.equal(script,'node --use-env-proxy scripts/e2-t8-capture-operator.js preflight');});
test('E2-T8 capture CLI requires exact action and confirmation shape',()=>{assert.deepEqual(parseArgs(['preflight','--confirm',op.INVENTORY_CONFIRMATION]),{action:'preflight',confirmation:op.INVENTORY_CONFIRMATION});assert.deepEqual(parseArgs(['execute','--confirm',op.CAPTURE_CONFIRMATION]),{action:'execute',confirmation:op.CAPTURE_CONFIRMATION});for(const args of [[],['preflight'],['execute','x',op.CAPTURE_CONFIRMATION]])assert.throws(()=>parseArgs(args))});
test('ownership diagnostic quarantines identities and returns only count and checksum',async()=>{const t=tmp(),unknown={object_key:'relation:review_only',object_class:'relation',ownership_class:'unclassified',fingerprint:FP};const report=await op.diagnoseOwnership({repo,stateFile:t.file,client:{query:async()=>({rows:[...inventory,unknown]})},confirmation:op.OWNERSHIP_DIAGNOSTIC_CONFIRMATION,...verified});assert.equal(report.status,'OWNERSHIP_REVIEW_REQUIRED');assert.equal(report.unclassifiedCount,1);assert.match(report.diagnosticSha256,/^[0-9a-f]{64}$/);assert.doesNotMatch(JSON.stringify(report),/review_only/);assert.equal(fs.statSync(`${t.file}.ownership.json`).mode&0o777,0o600);assert.match(fs.readFileSync(`${t.file}.ownership.json`,'utf8'),/review_only/);});
test('source inventory contract classifies failures without exposing rows',()=>{assert.deepEqual(op.validateInventory(inventory),inventory);for(const [rows,code] of [[[...inventory.slice(0,1),{...inventory[0],ownership_class:'unclassified'}],'SOURCE_INVENTORY_OWNERSHIP_UNCLASSIFIED'],[[{...inventory[0],fingerprint:'bad'}],'SOURCE_INVENTORY_FINGERPRINT_INVALID'],[[inventory[0],inventory[0]],'SOURCE_INVENTORY_DUPLICATE_IDENTITY']])assert.throws(()=>op.validateInventory(rows),error=>error.safeCode===code&&!JSON.stringify(error).includes('relation:accounts'));});
test('preflight sends one read-only inventory request and creates a sealed capsule',async()=>{const t=tmp(),client={calls:0,async query(sql){this.calls++;assert.match(sql,/^-- E2-T8 normalized/);return{rows:inventory}}},report=await op.preflight({repo,stateFile:t.file,client,confirmation:op.INVENTORY_CONFIRMATION,...verified});assert.equal(client.calls,1);assert.equal(report.status,'CAPTURE_APPROVAL_READY');assert.equal(report.productionRowsRead,false);assert.equal(fs.statSync(t.file).mode&0o777,0o600);assert.equal(fs.statSync(`${t.file}.inventory.json`).mode&0o777,0o600);assert.equal(op.readCaptureState(t.file,repo).consumed,false)});
test('preflight preserves only allowlisted management failure classifications',async()=>{for(const [input,expected] of [['MANAGEMENT_QUERY_REJECTED','SOURCE_INVENTORY_MANAGEMENT_QUERY_REJECTED'],['RAW_SECRET','SOURCE_INVENTORY_QUERY_FAILED']]){const t=tmp();await assert.rejects(op.preflight({repo,stateFile:t.file,client:{async query(){throw Object.assign(new Error('secret'),{safeCode:input})}},confirmation:op.INVENTORY_CONFIRMATION,...verified}),error=>error.safeCode===expected&&!error.message.includes('secret'));}});
test('capture executes once into quarantine and emits checksums without raw SQL',async()=>{const t=tmp();await op.preflight({repo,stateFile:t.file,client:{query:async()=>({rows:inventory})},confirmation:op.INVENTORY_CONFIRMATION,...verified});let calls=0;const report=op.execute({repo,stateFile:t.file,confirmation:op.CAPTURE_CONFIRMATION,runCapture(args,options){calls++;assert.deepEqual(args,['--execute','--confirm','E2_T8_SCHEMA_ONLY_CAPTURE']);assert.deepEqual(options.validationInputs.approvedSourceInventory,inventory);return{status:'CAPTURE_QUARANTINED_CONTRACT_PASS',artifact_checksum:'c'.repeat(64)}},env:{},...verified});assert.equal(calls,1);assert.equal(report.status,'CAPTURE_QUARANTINED_CONTRACT_PASS');assert.equal(report.repositoryArtifactWritten,false);assert.doesNotMatch(JSON.stringify(report),/CREATE TABLE|object_key|database_url/i);assert.equal(op.readCaptureState(t.file,repo).consumed,true);assert.throws(()=>op.execute({repo,stateFile:t.file,confirmation:op.CAPTURE_CONFIRMATION,runCapture(){calls++},env:{},...verified}));assert.equal(calls,1)});
test('capture failure is consumed and never retried',async()=>{const t=tmp();await op.preflight({repo,stateFile:t.file,client:{query:async()=>({rows:inventory})},confirmation:op.INVENTORY_CONFIRMATION,...verified});assert.throws(()=>op.execute({repo,stateFile:t.file,confirmation:op.CAPTURE_CONFIRMATION,runCapture:()=>({status:'CAPTURE_COMMAND_FAILED'}),env:{},...verified}),e=>e.safeCode==='SCHEMA_CAPTURE_CONTRACT_FAILED');assert.equal(op.readCaptureState(t.file,repo).consumed,true)});
