'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const root=path.join(__dirname,'..');
const dir=path.join(root,'artifacts/dataset-v2-acceptance/e2-t4-upsert');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const initial=require(path.join(dir,'expected-initial-canonical.json'));
const updated=require(path.join(dir,'expected-updated-canonical.json'));
const physical=require(path.join(dir,'expected-updated-physical.json'));
const {validateCanonicalRow,RAW_METRICS}=require('../funnel-core/canonical-contract');
const {validateEntityHierarchy}=require('../funnel-core/entity-hierarchy');
const {canonicalUniqueKey}=require('../funnel-core/dataset-repository');
const {canonicalToDbRow}=require('../funnel-core/supabase-dataset-repository');
const {ALLOWED,buildEvidence}=require('../scripts/e2-t4-upsert-evidence');
const preflight=read('docs/security/sql/E2_T4_UPSERT_PREFLIGHT.sql');
const transaction=read('docs/security/sql/E2_T4_UPSERT_TRANSACTION.sql');
const postcheck=read('docs/security/sql/E2_T4_UPSERT_POSTCHECK.sql');
const migration=read('supabase/migrations/20260816101220_create_performance_dataset_rows_v2.sql');
const strip=(sql)=>sql.replace(/--.*$/gm,'').trim();
const files=['artifacts/dataset-v2-acceptance/e2-t4-upsert/expected-initial-canonical.json','artifacts/dataset-v2-acceptance/e2-t4-upsert/expected-updated-canonical.json','artifacts/dataset-v2-acceptance/e2-t4-upsert/expected-updated-physical.json','docs/security/E2_T4_UPSERT_RUNBOOK.md','docs/security/sql/E2_T4_UPSERT_PREFLIGHT.sql','docs/security/sql/E2_T4_UPSERT_TRANSACTION.sql','docs/security/sql/E2_T4_UPSERT_POSTCHECK.sql','scripts/e2-t4-upsert-evidence.js'];

function sample(){return{initial_operation_count:1,upsert_operation_count:1,fixture_row_count:1,duplicate_group_count:0,duplicate_excess_row_count:0,updated_contract_match_count:1,dataset_before:0,v1_before:96,v1_after:96,snapshot_before:4,snapshot_after:4,identity_unchanged:true,hierarchy_unchanged:true,unsupported_null_preserved:true,supported_zero_preserved:true,oauth_unchanged:true,connected_unchanged:true,encrypted_unchanged:true,missing_encrypted_unchanged:true,orphan_encrypted_unchanged:true,plaintext_unchanged:true};}
function changedPaths(a,b,prefix=''){const keys=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);const out=[];for(const k of keys){const p=prefix?`${prefix}.${k}`:k;const x=a?.[k],y=b?.[k];if(x&&y&&typeof x==='object'&&typeof y==='object'&&!Array.isArray(x)&&!Array.isArray(y))out.push(...changedPaths(x,y,p));else if(JSON.stringify(x)!==JSON.stringify(y))out.push(p);}return out;}
function splitTopLevel(text){const out=[];let depth=0,start=0;for(let i=0;i<text.length;i+=1){if(text[i]==='(')depth+=1;else if(text[i]===')')depth-=1;else if(text[i]===','&&depth===0){out.push(text.slice(start,i).trim());start=i+1;}}out.push(text.slice(start).trim());return out;}

test('all E2-T4 artifacts exist',()=>{for(const f of files)assert.equal(fs.existsSync(path.join(root,f)),true,f);});
test('A and B validate and share the exact canonical key, identity, and hierarchy',()=>{for(const row of [initial,updated]){validateCanonicalRow(row);validateEntityHierarchy(row.identity,row.entity);assert.match(JSON.stringify(row),/e2_t4_same_key_v2/);assert.doesNotMatch(JSON.stringify(row),/e2_t3_/);}assert.equal(canonicalUniqueKey(initial),canonicalUniqueKey(updated));assert.deepEqual(initial.identity,updated.identity);assert.deepEqual(initial.entity,updated.entity);});
test('A and B differ only in planned mutable facts and redacted provenance revision',()=>{const paths=changedPaths(initial,updated);assert(paths.length>2);for(const p of paths)assert.match(p,/^(raw_metrics\.|provenance\.adapter_version$|provenance\.raw_reference\.revision$)/,p);assert.equal(initial.raw_metrics.session,null);assert.equal(updated.raw_metrics.session,null);assert.equal(initial.raw_metrics.add_to_cart,0);assert.equal(updated.raw_metrics.add_to_cart,0);assert.deepEqual(Object.keys(initial.metric_support).sort(),[...RAW_METRICS].sort());});
test('updated physical fixture is exact mapper output after runtime redaction',()=>{const mapped=canonicalToDbRow(updated);mapped.user_id='<runtime_user_redacted>';mapped.updated_at='<runtime_timestamp>';assert.deepEqual(mapped,physical);});
test('conflict target exactly matches migration canonical unique index order',()=>{const expected=['user_id','platform','platform_account_id','business_date','traffic_type','entity_key'];const index=migration.match(/create unique index performance_dataset_rows_v2_canonical_uidx[\s\S]*?\(([^;]+?)\);/i);assert(index);const migrationColumns=index[1].split(',').map(x=>x.trim());assert.deepEqual(migrationColumns,expected);const conflict=transaction.match(/on conflict\s*\(([^)]+)\)\s*do update/i);assert(conflict);assert.deepEqual(conflict[1].split(',').map(x=>x.trim()),expected);assert.notDeepEqual(expected,['entity_key']);assert.doesNotMatch(transaction,/on conflict on constraint/i);});
test('upsert uses two PostgreSQL inserts and never select-then-update emulation',()=>{const sql=strip(transaction);assert.equal((sql.match(/insert\s+into\s+public\.performance_dataset_rows_v2/gi)||[]).length,2);assert.equal((sql.match(/on conflict[\s\S]*?do update/gi)||[]).length,1);assert.doesNotMatch(sql,/\bupdate\s+public\.performance_dataset_rows_v2\b/i);});
test('preflight and postcheck are one read-only WITH SELECT each',()=>{for(const sql of [preflight,postcheck]){const clean=strip(sql);assert.match(clean,/^with\b/i);assert.equal((clean.match(/;/g)||[]).length,1);assert.doesNotMatch(clean,/\b(?:insert|update|delete|alter|create|drop|grant|revoke|truncate|call|do|begin|commit|rollback)\b/i);}});
test('transaction is intact, rollback-only, and mutates only Dataset V2',()=>{const clean=strip(transaction);assert.match(clean,/^begin\s*;/i);assert.match(clean,/rollback\s*;$/i);assert.equal((clean.match(/\bbegin\s*;/gi)||[]).length,1);assert.equal((clean.match(/\brollback\s*;/gi)||[]).length,1);assert.doesNotMatch(clean,/\bcommit\b/i);assert.match(clean,/lock table public\.performance_dataset_rows_v2 in share row exclusive mode/i);for(const r of ['performance_dataset_rows','dashboard_snapshots','oauth_transactions','platform_connection_tokens','platform_connections','schema_migrations','auth.users','public.users'])assert.doesNotMatch(clean,new RegExp(`(?:insert\\s+into|update|delete\\s+from|truncate)\\s+(?:public\\.)?${r.replace('.','\\.') }\\b`,'i'));assert.doesNotMatch(clean,/\b(?:alter|drop|grant|revoke|call)\b/i);assert.doesNotMatch(clean,/create\s+(?!temp table pg_temp\.)/i);assert.doesNotMatch(clean,/\bdo\s+(?!update\b)/i);});
test('transaction exposes all count, duplicate, semantic, and parity guards',()=>{for(const token of ['initial_operation_count','upsert_operation_count','fixture_row_count','duplicate_group_count','duplicate_excess_row_count','updated_contract_match_count','identity_unchanged','hierarchy_unchanged','unsupported_null_preserved','supported_zero_preserved','v1_before','v1_after','snapshot_before','snapshot_after','oauth_unchanged','encrypted_unchanged','plaintext_unchanged'])assert.match(transaction,new RegExp(`\\b${token}\\b`),token);});
test('preflight and postcheck cover canonical index, baselines, residue, and security state',()=>{for(const code of ['LEDGER_TOTAL','FIXTURE_ROWS','ELIGIBLE_USERS','V1_ROWS','SNAPSHOT_ROWS','OAUTH_ROWS','CONNECTED_CONNECTIONS','ENCRYPTED_TOKEN_ROWS','MISSING_ENCRYPTED','PLAINTEXT_TOKENS'])assert.match(preflight,new RegExp(`'${code}'`));assert.match(preflight,/'CANONICAL_UNIQUE_INDEX'/);assert.match(postcheck,/values \(\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint,\(-1\)::bigint\)/);for(const code of ['FIXTURE_ROWS','DUPLICATE_GROUPS','SCHEMA_RLS_INDEX_STATE'])assert.match(postcheck,new RegExp(`'${code}'`));});
test('transaction has one evidence-producing SELECT with the exact converter projection',()=>{const statements=strip(transaction).split(';').map(x=>x.trim()).filter(Boolean);assert.equal(statements.length,8);assert.match(statements[4],/^with[\s\S]*insert into public\.performance_dataset_rows_v2/i);assert.match(statements[5],/^with[\s\S]*on conflict[\s\S]*do update/i);assert.match(statements[6],/^with[\s\S]*select[\s\S]*from state s$/i);assert.equal(statements.filter(x=>/^select\b/i.test(x)).length,0);const projection=statements[6].slice(statements[6].lastIndexOf('\nselect\n')+8,statements[6].lastIndexOf('\nfrom state s'));const fields=splitTopLevel(projection).map(x=>{const alias=x.match(/\s([a-z0-9_]+)$/i);if(alias)return alias[1];const direct=x.match(/s\.([a-z0-9_]+)$/i);assert(direct,x);return direct[1];});assert.deepEqual(fields,[...ALLOWED]);});
test('postcheck uses scalar bigint actual and expected counts without invalid aggregate projection',()=>{const codes=[...postcheck.matchAll(/(?:select|union all select)\s+'([A-Z0-9_]+)'/g)].map(x=>x[1]);assert.deepEqual(codes,['DATASET_ROWS','FIXTURE_ROWS','DUPLICATE_GROUPS','V1_ROWS','SNAPSHOT_ROWS','OAUTH_ROWS','CONNECTED_CONNECTIONS','ENCRYPTED_TOKEN_ROWS','MISSING_ENCRYPTED','ORPHAN_ENCRYPTED','CONNECTION_TOKEN_PARITY','PLAINTEXT_TOKENS','LEDGER_TOTAL','SCHEMA_RLS_INDEX_STATE']);for(const block of postcheck.split(/union all select/i)){if(!/'[A-Z0-9_]+'/.test(block))continue;assert.match(block,/\(select[\s\S]+?\)|::bigint/);assert.match(block,/::bigint/);}assert.equal((postcheck.match(/count\(\*\)::bigint/g)||[]).length,13);assert.doesNotMatch(postcheck,/select\s+'[A-Z0-9_]+'\s*,\s*(?:coalesce\s*\(\s*)?(?:sum|count)\s*\(/i);assert.match(postcheck,/select check_code,actual_count::bigint as actual_count,expected_count::bigint as expected_count,\(actual_count=expected_count\)::boolean as passed/);});
test('runbook documents the PostgreSQL same-statement limitation and forbids manual merging',()=>{const runbook=read('docs/security/E2_T4_UPSERT_RUNBOOK.md');assert.match(runbook,/share one snapshot/i);assert.match(runbook,/modify the same row twice in one statement is not supported/i);assert.match(runbook,/must not manually merge multiple SQL result sets/i);assert.match(runbook,/Static repository checks validate structure.*not live PostgreSQL execution acceptance/i);});
test('second upsert is bound to the current transaction initial write',()=>{const statements=strip(transaction).split(';').map(x=>x.trim()).filter(Boolean);const initialWrite=statements[4],upsertWrite=statements[5],finalEvidence=statements[6];assert.match(initialWrite,/jsonb_build_object\([\s\S]*'fixture_namespace'\s*,\s*'e2_t4_same_key_v2'[\s\S]*'revision'\s*,\s*'initial'[\s\S]*'transaction_marker'\s*,\s*pg_current_xact_id\(\)::text[\s\S]*\)/i);const eligibility=upsertWrite.slice(upsertWrite.indexOf('where ('),upsertWrite.indexOf('on conflict'));for(const contract of [/d\.user_id=u\.id/i,/d\.entity_key=k\.entity_key/i,/d\.adapter_version='e2-t4-meta-v2-initial'/i,/d\.raw->>'revision'='initial'/i,/d\.raw->>'transaction_marker'=pg_current_xact_id\(\)::text/i])assert.match(eligibility,contract);assert.doesNotMatch(eligibility,/\bor\b/i);const updatedRaw=upsertWrite.match(/'(\{"fixture_namespace":"e2_t4_same_key_v2","revision":"updated"\})'::jsonb/i);assert(updatedRaw);assert.deepEqual(Object.keys(JSON.parse(updatedRaw[1])).sort(),['fixture_namespace','revision']);assert.doesNotMatch(finalEvidence,/pg_current_xact_id|transaction_marker/i);assert.equal(ALLOWED.some(x=>/transaction|marker/i.test(x)),false);});
test('false gates or residue cannot independently authorize the upsert',()=>{const statements=strip(transaction).split(';').map(x=>x.trim()).filter(Boolean);const gates=statements[4],upsert=statements[5];for(const gate of ['ledger_ok','fixture_absent','user_ok','oauth_ok','population_parity_ok','missing_ok','orphan_ok','plaintext_ok'])assert.match(gates,new RegExp(`g\\.${gate}`));assert.match(upsert,/where \(select count\(\*\)[\s\S]*transaction_marker[\s\S]*\)=1\s+on conflict/i);assert.doesNotMatch(upsert,/where \(select count\(\*\)[\s\S]*adapter_version='e2-t4-meta-v2-initial'\)=1\s+on conflict/i);});
test('evidence v2 accepts only integer zero duplicate excess and stays fail-closed',()=>{const evidence=buildEvidence(sample(),initial,updated);assert.equal(evidence.evidence_version,'e2-t4-upsert-v2');assert.equal(evidence.namespace,'e2_t4_same_key_v2');assert.equal(evidence.status,'PASS');assert.equal(evidence.final_fixture_row_count,1);assert.equal(evidence.duplicate_excess_row_count,0);assert.equal(evidence.rollback_required,true);assert.throws(()=>buildEvidence({...sample(),extra:true},initial,updated),/allowlist/);assert.throws(()=>buildEvidence({...sample(),fixture_row_count:2},initial,updated),/equal one/);assert.throws(()=>buildEvidence({...sample(),duplicate_group_count:1},initial,updated),/equal zero/);for(const value of ['0',-1,0.5,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>buildEvidence({...sample(),duplicate_excess_row_count:value},initial,updated),/safe integer zero/);});
test('artifacts contain no UUID, PII, credential, URI, JWT, or private key',()=>{const text=files.map(read).join('\n');assert.doesNotMatch(text,/postgres(?:ql)?:\/\/|authorization\s*:|bearer\s+|-----BEGIN [A-Z ]*PRIVATE KEY-----|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/i);});
test('execution plan retains exact current E2 states',()=>{const plan=read('codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md');for(const n of [1,2,3,4])assert.match(plan,new RegExp(`E2-T${n} — `+'`Done`'));assert.match(plan,/E2-T5 — `Verification`/);for(const n of [6,7,8])assert.match(plan,new RegExp(`E2-T${n} — `+'`Not started`'));});

test('E2-C1 captured provider-token parity is fail-closed',()=>{for(const sql of [preflight,transaction,postcheck])assert.doesNotMatch(sql,/(?:CONNECTED_CONNECTIONS|ENCRYPTED_TOKEN_ROWS)[^\n]*,\s*7\b/);for(const code of ['MISSING_ENCRYPTED','ORPHAN_ENCRYPTED','PLAINTEXT_TOKENS','CONNECTION_TOKEN_PARITY'])assert.match(preflight,new RegExp(`'${code}'`));assert.match(preflight,/'CONNECTED_CONNECTIONS'[^\n]*'capture'/);assert.match(transaction,/connected_count[\s\S]*encrypted_count/);for(const field of ['connected_unchanged','encrypted_unchanged','missing_encrypted_unchanged','orphan_encrypted_unchanged','plaintext_unchanged'])assert.match(transaction,new RegExp(`\\b${field}\\b`));assert.match(postcheck,/connected_rows/);assert.match(postcheck,/encrypted_rows/);assert.match(transaction,/rollback;\s*$/i);assert.throws(()=>buildEvidence({...sample(),token_count:1},initial,updated),/counts are forbidden/);});

test('T4 postcheck and runbook define five baselines and the pg_temp lifecycle',()=>{assert.equal((postcheck.match(/\(-1\)::bigint/g)||[]).length,5);const runbook=read('docs/security/E2_T4_UPSERT_RUNBOOK.md');assert.match(runbook,/exact order: Dataset V2, V1, snapshot, connected, encrypted/);assert.match(runbook,/pg_temp\.e2_t4_security_baseline/);assert.match(runbook,/mandatory final `ROLLBACK` removes that transaction-local temporary table/);assert.doesNotMatch(runbook,/without a temporary table|temporary table kullanılmaz/i);assert.match(runbook,/Actual provider counts remain operator-local, are never shared, and are never committed/);});

test('V2 operation contract removes the old active namespace',()=>{const active=[preflight,transaction,postcheck,JSON.stringify(initial),JSON.stringify(updated),JSON.stringify(physical),read('scripts/e2-t4-upsert-evidence.js')].join('\n');assert.doesNotMatch(active,/e2_t4_same_key_v1/);assert.equal((active.match(/e2_t4_same_key_v2/g)||[]).length>7,true);assert.match(transaction,/E2_T4_TRANSACTION_V2/);assert.match(transaction,/coalesce\(sum\(\(row_count-1\)::bigint\),0::bigint\)::bigint/);assert.match(transaction,/s\.duplicate_excess_row_count::bigint as duplicate_excess_row_count/);});
test('postcheck has one ordered five-bigint placeholder row',()=>{assert.match(postcheck,/expected\(dataset_rows,v1_rows,snapshot_rows,connected_rows,encrypted_rows\)/);assert.equal((postcheck.match(/\(-1\)::bigint/g)||[]).length,5);assert.equal((strip(postcheck).match(/;/g)||[]).length,1);});
test('runbook and plan record recovery/no-change facts and current Done state',()=>{const text=read('docs/security/E2_T4_UPSERT_RUNBOOK.md')+'\n'+read('codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md');for(const pattern of [/v1 preflight.*16\/16 PASS/i,/v1 transaction.*HTTP 201/i,/duplicate-excess evidence contract.*FAIL/i,/v1 postcheck.*HTTP 400/i,/transaction retry.*no/i,/read-only recovery.*HTTP 201/i,/recovery.*11\/11 PASS/i,/fixture residue.*zero/i,/Dataset V2.*zero/i,/production no-change/i,/v2 corrective preparation/i,/production counts.*identities.*not shared/i,/E2-T4.*Done/i])assert.match(text,pattern);});
