"use strict";
const assert=require("node:assert/strict");const{test}=require("node:test");
const{createOrganicOAuthHandlers}=require("../src/oauth/organic-handlers");const{createKlaviyoOAuthHandlers}=require("../src/oauth/klaviyo-handlers");const{createTikTokOAuthHandlers}=require("../src/oauth/tiktok-handlers");
function res(){return{body:null,location:null,code:200,status(v){this.code=v;return this},send(v){this.body=v;return this},json(v){this.body=v;return this},redirect(v){this.location=v;return this}}}
function organic(overrides={}){return createOrganicOAuthHandlers({scopes:["analytics"],requireConnectAccess:async()=>({userId:"verified"}),createTransaction:async()=>({state:"state"}),consumeTransaction:async()=>({user_id:"verified",created_at:"earlier"}),sendAuthorizationResponse:(_q,r,url)=>r.json({url}),getRedirectUri:()=>"https://app/auth/organic/callback",createClient:()=>({generateAuthUrl:({state})=>`https://google/auth?state=${state}`,getToken:async()=>({tokens:{access_token:"access"}})}),getConnection:async()=>null,saveConnection:async()=>{},now:()=>"now",...overrides})}
function klaviyo(overrides={}){return createKlaviyoOAuthHandlers({config:{clientId:"id",clientSecret:"secret",redirectUri:"https://app/callback",scopes:"accounts:read",authorizationBase:"https://klaviyo"},requireConnectAccess:async()=>({userId:"verified"}),createTransaction:async()=>({state:"state"}),consumeTransaction:async()=>({user_id:"verified",pkce_verifier:"verifier"}),sendAuthorizationResponse:(_q,r,url)=>r.json({url}),createPkce:()=>({verifier:"verifier",challenge:"challenge"}),exchangeToken:async()=>({access_token:"access"}),saveConnection:async()=>{},getConnection:async()=>({}),resolveAccount:async()=>({platform_account_id:"account",account_name:"Account",raw_account:{}}),parseExpiry:()=>null,...overrides})}
function tiktok(overrides={}){return createTikTokOAuthHandlers({config:{clientId:"id",clientSecret:"secret",redirectUri:"https://app/callback",authorizationBase:"https://tiktok/auth"},requireConnectAccess:async()=>({userId:"verified"}),createTransaction:async()=>({state:"state"}),consumeTransaction:async()=>({user_id:"verified"}),sendAuthorizationResponse:(_q,r,url)=>r.json({url}),getConnection:async()=>null,normalizeAccountId:value=>value,exchangeToken:async()=>({access_token:"access"}),saveConnection:async()=>{},parseExpiry:()=>null,...overrides})}
test("Organic uses verified transaction identity and rejects invalid state before exchange",async()=>{const writes=[],ok=res();await organic({saveConnection:async(...args)=>writes.push(args)}).callback({query:{code:"code",state:"state"}},ok);assert.equal(writes[0][0],"verified");assert.equal(ok.location,"/dashboard?organic_connected=1&account_selection_required=1");let exchanged=false;const bad=res();await organic({consumeTransaction:async()=>null,createClient:()=>({getToken:async()=>{exchanged=true}})}).callback({query:{code:"code",state:"bad"}},bad);assert.equal(exchanged,false);assert.equal(bad.location,"/dashboard?organic_error=invalid_state")});
test("Klaviyo binds PKCE to transaction and persists discovered account as unselected",async()=>{let exchange,writes=[];const response=res();await klaviyo({exchangeToken:async input=>(exchange=input,{access_token:"access"}),saveConnection:async(...args)=>writes.push(args)}).callback({query:{code:"code",state:"state"}},response);assert.equal(exchange.verifier,"verifier");assert.equal(writes[0][0],"verified");assert.equal(writes[1][2].metadata.lastDiscoveredPlatformAccountId,"account");assert.equal(response.location,"/dashboard?klaviyo_connected=1&account_selection_required=1")});
test("TikTok preserves already-connected guard and transaction identity",async()=>{let created=false;const guarded=res();await tiktok({getConnection:async()=>({access_token:"access",account_id:"account"}),createTransaction:async()=>{created=true}}).start({query:{}},guarded);assert.equal(created,false);assert.equal(guarded.location,"/dashboard?tiktok_already_connected=1");const writes=[],response=res();await tiktok({saveConnection:async(...args)=>writes.push(args)}).callback({query:{auth_code:"code",state:"state"}},response);assert.equal(writes[0][0],"verified")});
test("provider handler factories fail closed for missing dependencies",()=>{assert.throws(()=>createOrganicOAuthHandlers({}),/must be a function/);assert.throws(()=>createKlaviyoOAuthHandlers({}),/config is required/);assert.throws(()=>createTikTokOAuthHandlers({}),/config is required/) });
