'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {createMetaClient}=require('../src/providers/meta/client');
const {backfillRange,createMetaLiveRefresh}=require('../src/providers/meta/live-refresh');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
function supabaseHarness(){const writes=[];return{writes,from(table){assert.equal(table,'performance_dataset_rows_v2');return{upsert(payload,options){writes.push({payload,options});return{select:async()=>({data:payload.map(row=>({...row,id:'v2_fixture'})),error:null})};}}}};}
function response(data,paging=null){return{ok:true,status:200,json:async()=>paging?{data,paging}:{data}};}

test('Meta client follows cursor pagination without accepting provider next URLs',async()=>{const seen=[],client=createMetaClient({accessToken:'token-fixture',transport:async url=>{seen.push(String(url));return seen.length===1?response([{ad_id:'a'}],{next:'https://host/path?access_token=must-not-follow',cursors:{after:'cursor-1'}}):response([{ad_id:'b'}]);}}),result=await client.fetchAdInsights({accountId:'act_fixture',since:'2026-08-29',until:'2026-08-29'});assert.deepEqual(result.data,[{ad_id:'a'},{ad_id:'b'}]);assert.deepEqual(client.getLastInsightsEvidence(),{data_is_array:true,page_count:2,row_count:2,has_next_page:false});assert.equal(new URL(seen[1]).searchParams.get('after'),'cursor-1');assert.equal(seen.some(url=>url.includes('must-not-follow')),false);});
test('30-day range is inclusive and bounded',()=>{assert.deepEqual(backfillRange('2026-08-30'),{since:'2026-08-01',until:'2026-08-30',dayCount:30});assert.throws(()=>backfillRange('2026-08-30',31),/between 1 and 30/);assert.throws(()=>backfillRange('2026-02-30'),/YYYY-MM-DD/);});
test('live Meta refresh writes daily provider rows to Dataset V2 with per-day FX and redacted evidence',async()=>{const db=supabaseHarness(),fxDates=[];const original=global.fetch,second={...fixture.insight,date_start:'2026-08-30',date_stop:'2026-08-30',ad_id:'ad_fixture_2'};global.fetch=async url=>String(url).includes('/me/adaccounts')?response([fixture.account]):response([fixture.insight,second]);try{const live=createMetaLiveRefresh({supabaseClient:db,graphVersion:'v23.0',resolveTargetCurrency:async()=> 'TRY',resolveFxRate:async(_source,_target,{rateDate})=>{fxDates.push(rateDate);return{fx_rate:rateDate.endsWith('29')?32:33,fx_rate_date:rateDate,fx_provider:'approved-live-test'};}}),result=await live.run({userId:'user-fixture',accessToken:'token-fixture',accountId:fixture.account.id,until:'2026-08-30',dayCount:2,sourceJobId:'job-fixture'});assert.equal(result.mode,'v2_upsert');assert.deepEqual(result.dataset_v2,{attempted:2,persisted:2,empty_provider_result:false});assert.deepEqual(fxDates,['2026-08-29','2026-08-30']);assert.equal(db.writes.length,1);assert.equal(db.writes[0].payload[0].purchase_value,15360);assert.equal(db.writes[0].payload[1].purchase_value,15840);assert.equal(db.writes[0].payload[0].source_job_id,'job-fixture');assert.equal(result.meta_v2_evidence.provider_request.day_count,2);assert.equal(result.meta_v2_evidence.provider_request.time_increment,1);assert.deepEqual(result.meta_v2_evidence.provider_response,{data_is_array:true,page_count:1,row_count:2,has_next_page:false});assert.deepEqual(result.meta_v2_evidence.mapping,{accepted_row_count:2,rejected_row_count:0,rejection_codes:[]});assert.equal(JSON.stringify(result.meta_v2_evidence).includes('ad_fixture'),false);assert.equal(db.writes[0].options.onConflict,'user_id,platform,platform_account_id,business_date,traffic_type,entity_key');}finally{global.fetch=original;}});
test('empty Meta insights are a successful evidenced zero-row V2 refresh and never create fake data',async()=>{const db=supabaseHarness(),original=global.fetch;global.fetch=async url=>String(url).includes('/me/adaccounts')?response([fixture.account]):response([]);try{const live=createMetaLiveRefresh({supabaseClient:db,resolveTargetCurrency:async()=> 'USD',resolveFxRate:async()=>{throw new Error('FX must not run for empty data');}}),result=await live.run({userId:'user-fixture',accessToken:'token-fixture',accountId:fixture.account.id,until:'2026-08-29',dayCount:1});assert.deepEqual(result.dataset_v2,{attempted:0,persisted:0,empty_provider_result:true});assert.deepEqual(result.meta_v2_evidence.provider_response,{data_is_array:true,page_count:1,row_count:0,has_next_page:false});assert.equal(db.writes.length,0);}finally{global.fetch=original;}});
