'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {createMetaClient}=require('../src/providers/meta/client');
const {createMetaLiveRefresh}=require('../src/providers/meta/live-refresh');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
function supabaseHarness(){const writes=[];return{writes,from(table){assert.equal(table,'performance_dataset_rows_v2');return{upsert(payload,options){writes.push({payload,options});return{select:async()=>({data:payload.map(row=>({...row,id:'v2_fixture'})),error:null})};}}}};}
function response(data,paging=null){return{ok:true,status:200,json:async()=>paging?{data,paging}:{data}};}

test('Meta client follows cursor pagination without accepting provider next URLs',async()=>{const seen=[],client=createMetaClient({accessToken:'token-fixture',transport:async url=>{seen.push(String(url));return seen.length===1?response([{ad_id:'a'}],{next:'https://host/path?access_token=must-not-follow',cursors:{after:'cursor-1'}}):response([{ad_id:'b'}]);}}),result=await client.fetchAdInsights({accountId:'act_fixture',since:'2026-08-29',until:'2026-08-29'});assert.deepEqual(result.data,[{ad_id:'a'},{ad_id:'b'}]);assert.equal(new URL(seen[1]).searchParams.get('after'),'cursor-1');assert.equal(seen.some(url=>url.includes('must-not-follow')),false);});
test('live Meta refresh writes real provider rows directly to Dataset V2',async()=>{const db=supabaseHarness(),calls=[];const original=global.fetch;global.fetch=async url=>{calls.push(String(url));return String(url).includes('/me/adaccounts')?response([fixture.account]):response([fixture.insight]);};try{const live=createMetaLiveRefresh({supabaseClient:db,graphVersion:'v23.0',resolveTargetCurrency:async()=> 'TRY',resolveFxRate:async()=>({fx_rate:32,fx_rate_date:'2026-08-29',fx_provider:'approved-live-test'})}),result=await live.run({userId:'user-fixture',accessToken:'token-fixture',accountId:fixture.account.id,since:'2026-08-29',until:'2026-08-29',sourceJobId:'job-fixture'});assert.equal(result.mode,'v2_upsert');assert.deepEqual(result.dataset_v2,{attempted:1,persisted:1,empty_provider_result:false});assert.equal(db.writes.length,1);assert.equal(db.writes[0].payload[0].purchase_value,15360);assert.equal(db.writes[0].payload[0].source_job_id,'job-fixture');assert.equal(db.writes[0].options.onConflict,'user_id,platform,platform_account_id,business_date,traffic_type,entity_key');}finally{global.fetch=original;}});
test('empty Meta insights are a successful zero-row V2 refresh and never create fake data',async()=>{const db=supabaseHarness(),original=global.fetch;global.fetch=async url=>String(url).includes('/me/adaccounts')?response([fixture.account]):response([]);try{const live=createMetaLiveRefresh({supabaseClient:db,resolveTargetCurrency:async()=> 'USD',resolveFxRate:async()=>({fx_rate:1,fx_rate_date:'2026-08-29',fx_provider:'same_currency'})}),result=await live.run({userId:'user-fixture',accessToken:'token-fixture',accountId:fixture.account.id,since:'2026-08-29',until:'2026-08-29'});assert.deepEqual(result.dataset_v2,{attempted:0,persisted:0,empty_provider_result:true});assert.equal(db.writes.length,0);}finally{global.fetch=original;}});
