'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {CanonicalWriteBoundary}=require('../funnel-core/canonical-write-boundary');
const {InMemoryDatasetRepository}=require('../funnel-core/dataset-repository');
const {FunnelQueryService}=require('../funnel-core/funnel-query-service');
const {createMetaAdapter}=require('../src/providers/meta/adapter');
const {createMetaDatasetWriter}=require('../src/providers/meta/dataset-writer');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8')),expected=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t8-expected-parity.json'),'utf8'));
const input={accountId:fixture.account.id,since:fixture.insight.date_start,until:fixture.insight.date_stop,context:{userId:'user-fixture',account:fixture.account,targetCurrency:expected.target_currency,fxRate:expected.fx_rate,fxRateDate:fixture.insight.date_start,fxProvider:'e4-t8-approved-fixture'}};
function close(actual,wanted,label){assert.equal(typeof actual,'number',`${label} must be numeric`);assert.ok(Math.abs(actual-wanted)<=1e-9,`${label}: ${actual} != ${wanted}`);}
function harness(){const repository=new InMemoryDatasetRepository(),adapter=createMetaAdapter({client:{async fetchAdInsights(){return{data:[fixture.insight]}}}}),writer=createMetaDatasetWriter({adapter,writeBoundary:new CanonicalWriteBoundary({repository})});return{repository,writer,query:new FunnelQueryService({repository})};}

test('provider to canonical to FX to Dataset V2 preserves every expected raw fact',async()=>{const {repository,writer}=harness(),write=await writer.ingest(input),rows=await repository.readCanonicalRawFacts({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',platform:'meta',platform_account_id:fixture.account.id});assert.equal(write.persisted,1);assert.equal(rows.length,1);assert.deepEqual(rows[0].raw_metrics,expected.expected_raw_metrics);assert.equal(rows[0].currency.target_currency,'TRY');assert.equal(rows[0].currency.fx_rate,32);assert.equal(rows[0].time.business_date,'2026-08-29');assert.equal(rows[0].provenance.raw_reference.metric_sources.purchase.action_type,'purchase');});
test('Dataset V2 query and Formula Engine reconcile to the frozen expected totals',async()=>{const {writer,query}=harness();await writer.ingest(input);const result=await query.query({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',platform:'meta',platform_account_id:fixture.account.id,analysis_scope:'paid'});for(const [key,value] of Object.entries(expected.expected_funnel_totals))close(result.totals[key],value,`totals.${key}`);for(const [key,value] of Object.entries(expected.expected_intent))close(result.intent[key],value,`intent.${key}`);assert.equal(result.meta.currency,'TRY');assert.equal(result.meta.formula_engine_version,'v1');assert.equal(result.rows.length,1);});
test('replaying the complete chain remains one row with identical expected totals',async()=>{const {repository,writer,query}=harness();await writer.ingest(input);await writer.ingest(input);const rows=await repository.readCanonicalRawFacts({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29'}),result=await query.query({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',analysis_scope:'paid'});assert.equal(rows.length,1);assert.deepEqual(rows[0].raw_metrics,expected.expected_raw_metrics);close(result.totals.funnel_sales,expected.expected_funnel_totals.funnel_sales,'retry.sales');});
test('parity fails visibly when any expected business total drifts',async()=>{const {writer,query}=harness();await writer.ingest(input);const result=await query.query({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',analysis_scope:'paid'});assert.throws(()=>close(result.totals.funnel_sales,expected.expected_funnel_totals.funnel_sales+1,'drift.sales'),/drift.sales/);assert.equal(expected.synthetic,true);assert.equal(expected.evidence_version,'e4-t8-meta-parity-v1');});
