'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {mapMetaInsight}=require('../src/providers/meta/mapper');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
const context={userId:'user-fixture',accountId:fixture.account.id,businessDate:fixture.insight.date_start,sourceTimezone:fixture.account.timezone_name,sourceCurrency:'USD',targetCurrency:'USD',fxRate:1,fxRateDate:fixture.insight.date_start,fxProvider:'same_currency',fxEngineVersion:'v1',timeEngineVersion:'v1'};
const map=insight=>mapMetaInsight(insight,context).row;

test('every canonical fact carries source-only provenance with no duplicated values',()=>{const row=map(fixture.insight),sources=row.provenance.raw_reference.metric_sources;assert.deepEqual(Object.keys(sources),Object.keys(row.raw_metrics));for(const source of Object.values(sources)){assert.deepEqual(Object.keys(source).sort(),['action_type','fallback_used','source_field']);assert.equal(Object.hasOwn(source,'value'),false);}assert.equal(row.provenance.source_confidence,'real');});
test('standard conversion actions win and aliases are never summed',()=>{const row=map(fixture.insight),sources=row.provenance.raw_reference.metric_sources;assert.equal(row.raw_metrics.add_to_cart,12);assert.equal(sources.add_to_cart.action_type,'add_to_cart');assert.equal(sources.add_to_cart.fallback_used,false);assert.equal(row.raw_metrics.checkout,7);assert.equal(sources.checkout.action_type,'initiate_checkout');assert.equal(row.raw_metrics.purchase,4);assert.equal(sources.purchase.action_type,'purchase');});
test('omni fallback is explicit for count and value',()=>{const omitStandard=list=>list.filter(item=>!['add_to_cart','initiate_checkout','checkout','purchase'].includes(item.action_type));const row=map({...fixture.insight,actions:omitStandard(fixture.insight.actions),action_values:omitStandard(fixture.insight.action_values)}),sources=row.provenance.raw_reference.metric_sources;for(const key of ['add_to_cart','add_to_cart_value','checkout','checkout_value','purchase','purchase_value'])assert.equal(sources[key].fallback_used,true,key);assert.equal(sources.purchase.action_type,'omni_purchase');assert.equal(sources.purchase_value.source_field,'action_values');assert.equal(row.provenance.source_confidence,'fallback');});
test('missing purchase is partial and records an explicit unknown source decision',()=>{const withoutPurchase=list=>list.filter(item=>!['purchase','omni_purchase'].includes(item.action_type));const row=map({...fixture.insight,actions:withoutPurchase(fixture.insight.actions),action_values:withoutPurchase(fixture.insight.action_values)}),sources=row.provenance.raw_reference.metric_sources;assert.equal(row.raw_metrics.purchase,null);assert.equal(row.metric_support.purchase,'unknown');assert.deepEqual(sources.purchase,{source_field:'actions',action_type:null,fallback_used:false});assert.equal(row.provenance.source_confidence,'partial');});
test('count and monetary value provenance remain independently reviewable',()=>{const actions=fixture.insight.actions.filter(item=>item.action_type!=='purchase'),values=fixture.insight.action_values.filter(item=>item.action_type!=='omni_purchase');const row=map({...fixture.insight,actions,action_values:values}),sources=row.provenance.raw_reference.metric_sources;assert.equal(sources.purchase.action_type,'omni_purchase');assert.equal(sources.purchase.fallback_used,true);assert.equal(sources.purchase_value.action_type,'purchase');assert.equal(sources.purchase_value.fallback_used,false);});
