'use strict';
const assert=require('node:assert/strict'),test=require('node:test');
const {createMetaClient}=require('../src/providers/meta/client');
const {createMetaRefreshRunner}=require('../src/providers/meta/refresh-runner');
const input={accountId:'act_fixture',context:{userId:'user_fixture'}};
function boundary(){const calls=[];return{calls,async run(spec){calls.push(spec);const result=await spec.work({jobId:'job_fixture'});return{job:{id:'job_fixture'},result,completed:spec.completed(result)};}};}
function failure(code,message='secret raw provider detail'){const error=new Error(message);error.safeCode=code;return error;}

test('transient Meta failure retries with bounded backoff and completes one refresh job',async()=>{let calls=0;const jobs=boundary(),events=[],delays=[],runner=createMetaRefreshRunner({datasetWriter:{async ingest(){calls+=1;if(calls<3)throw failure('META_SERVICE_UNAVAILABLE');return{persisted:2};}},jobBoundary:jobs,telemetry:event=>events.push(event),sleep:async ms=>delays.push(ms)}),result=await runner.run(input);assert.equal(jobs.calls.length,1);assert.equal(calls,3);assert.deepEqual(delays,[100,200]);assert.equal(result.result.attempts,3);assert.deepEqual(result.completed,{metadata:{job_type:'meta_v2_refresh',attempts:3,rows_written:2}});assert.deepEqual(events.map(event=>event.event),['meta_refresh_attempt','meta_refresh_retry','meta_refresh_attempt','meta_refresh_retry','meta_refresh_attempt','meta_refresh_completed']);});
test('contract and authorization failures never retry and expose no raw provider message',async()=>{for(const code of ['META_AUTH_REJECTED','META_REQUEST_REJECTED']){let calls=0;const events=[],runner=createMetaRefreshRunner({datasetWriter:{async ingest(){calls+=1;throw failure(code);}},jobBoundary:boundary(),telemetry:event=>events.push(event),sleep:async()=>assert.fail('must not sleep')});await assert.rejects(runner.run(input),error=>error.message==='Meta refresh failed'&&error.safeCode==='META_REFRESH_FAILED'&&!error.message.includes('secret'));assert.equal(calls,1);assert.equal(events.at(-1).safe_code,'META_REFRESH_FAILED');}});
test('transient retry exhaustion is bounded and reports only the allowlisted safe code',async()=>{let calls=0;const delays=[],runner=createMetaRefreshRunner({maxAttempts:2,datasetWriter:{async ingest(){calls+=1;throw failure('META_RATE_LIMITED');}},jobBoundary:boundary(),sleep:async ms=>delays.push(ms)});await assert.rejects(runner.run(input),error=>error.message==='Meta refresh failed'&&error.safeCode==='META_RATE_LIMITED');assert.equal(calls,2);assert.deepEqual(delays,[100]);});
test('Meta client classifies retryable and permanent HTTP failures without response bodies',async()=>{for(const [status,code] of [[429,'META_RATE_LIMITED'],[503,'META_SERVICE_UNAVAILABLE'],[401,'META_AUTH_REJECTED'],[400,'META_REQUEST_REJECTED']]){const client=createMetaClient({accessToken:'fixture',transport:async()=>({ok:false,status,json:async()=>({secret:'must-not-leak'})})});await assert.rejects(client.fetchAdInsights({accountId:'act_fixture',since:'2026-08-29',until:'2026-08-29'}),error=>error.safeCode===code&&!error.message.includes('must-not-leak'));}});
test('runner configuration and ownership inputs fail closed before a job starts',async()=>{assert.throws(()=>createMetaRefreshRunner({datasetWriter:{ingest(){}},jobBoundary:boundary(),maxAttempts:6}),/between 1 and 5/);const jobs=boundary(),runner=createMetaRefreshRunner({datasetWriter:{ingest(){}},jobBoundary:jobs});await assert.rejects(runner.run({accountId:'',context:{userId:'user'}}),/accountId is required/);assert.equal(jobs.calls.length,0);});
