'use strict';
const assert=require('node:assert/strict'),test=require('node:test');
const {createMetaDualWriteCoordinator}=require('../src/providers/meta/dual-write');
const pair={userId:'user_fixture',accountId:'act_fixture'},v2Input={accountId:'act_fixture',context:{userId:'user_fixture'}};
function setup(options={}){const calls=[],events=[],legacy={snapshot:{id:'legacy_fixture'},kpis:{spend:125.5}};const coordinator=createMetaDualWriteCoordinator({enabled:false,allowlist:[],v2Refresh:{async run(input){calls.push(input);return{result:{attempts:1,write:{persisted:2}}};}},telemetry:event=>events.push(event),...options});return{calls,coordinator,events,legacy};}

test('dual-write is disabled and empty by default while the legacy result remains exact',async()=>{const h=setup(),result=await h.coordinator.run({...pair,v2Input,legacyWrite:async()=>h.legacy});assert.strictEqual(result,h.legacy);assert.equal(h.calls.length,0);assert.deepEqual(h.events,[{event:'meta_dual_write_skipped',reason:'disabled'}]);});
test('enabled dual-write still skips every user/account pair outside the exact allowlist',async()=>{const h=setup({enabled:true,allowlist:[{userId:'other',accountId:'act_fixture'}]}),result=await h.coordinator.run({...pair,v2Input,legacyWrite:async()=>h.legacy});assert.strictEqual(result,h.legacy);assert.equal(h.calls.length,0);assert.equal(h.events[0].reason,'not_allowlisted');});
test('an exact allowlisted pair writes V1 first, then V2, without changing the V1 contract',async()=>{const order=[],h=setup({enabled:true,allowlist:[pair],v2Refresh:{async run(input){order.push('v2');h.calls.push(input);return{result:{attempts:1,write:{persisted:2}}};}}}),result=await h.coordinator.run({...pair,v2Input,legacyWrite:async()=>{order.push('v1');return h.legacy;}});assert.deepEqual(order,['v1','v2']);assert.strictEqual(result,h.legacy);assert.deepEqual(h.events,[{event:'meta_dual_write_completed',attempts:1,rows_written:2}]);});
test('V2 failure never changes or fails the already successful legacy result and leaks no raw error',async()=>{const h=setup({enabled:true,allowlist:[pair],v2Refresh:{async run(){const error=new Error('secret provider body');error.safeCode='META_SERVICE_UNAVAILABLE';throw error;}}}),result=await h.coordinator.run({...pair,v2Input,legacyWrite:async()=>h.legacy});assert.strictEqual(result,h.legacy);assert.deepEqual(h.events,[{event:'meta_dual_write_failed',safe_code:'META_SERVICE_UNAVAILABLE'}]);assert.equal(JSON.stringify(h.events).includes('secret'),false);const unknown=setup({enabled:true,allowlist:[pair],v2Refresh:{async run(){const error=new Error('secret');error.safeCode='RAW_PROVIDER_SECRET';throw error;}}});await unknown.coordinator.run({...pair,v2Input,legacyWrite:async()=>unknown.legacy});assert.equal(unknown.events[0].safe_code,'META_DUAL_WRITE_FAILED');});
test('ownership mismatch skips V2 and malformed allowlists fail closed before any write',async()=>{const h=setup({enabled:true,allowlist:[pair]}),result=await h.coordinator.run({...pair,v2Input:{...v2Input,accountId:'act_other'},legacyWrite:async()=>h.legacy});assert.strictEqual(result,h.legacy);assert.equal(h.calls.length,0);assert.equal(h.events[0].reason,'ownership_mismatch');for(const allowlist of [[{userId:'u',accountId:'a',extra:true}],[pair,pair],['invalid']])assert.throws(()=>setup({allowlist}),/fields|duplicate|object/);});
test('repeated allowlisted runs delegate twice while retaining the same legacy response contract',async()=>{const h=setup({enabled:true,allowlist:[pair]});for(let i=0;i<2;i+=1)assert.strictEqual(await h.coordinator.run({...pair,v2Input,legacyWrite:async()=>h.legacy}),h.legacy);assert.equal(h.calls.length,2);});
