'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {validateCanonicalRow}=require('../funnel-core/canonical-contract');
const {validateEntityHierarchy,buildEntityKey}=require('../funnel-core/entity-hierarchy');
const {META_CAPABILITIES}=require('../src/providers/meta/capabilities');
const {ACCOUNT_FIELDS,AD_INSIGHT_FIELDS,createMetaClient}=require('../src/providers/meta/client');
const {mapMetaInsight}=require('../src/providers/meta/mapper');
const {createMetaAdapter}=require('../src/providers/meta/adapter');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
const context={userId:'user-fixture',account:fixture.account,accountId:fixture.account.id,businessDate:fixture.insight.date_start,sourceTimezone:fixture.account.timezone_name,sourceCurrency:'USD',targetCurrency:'USD',fxRate:1,fxRateDate:fixture.insight.date_start,fxProvider:'same_currency',fxEngineVersion:'v1',timeEngineVersion:'v1'};

test('Meta capabilities freeze Ad lineage and approved fact roles',()=>{assert.deepEqual(META_CAPABILITIES.hierarchy,{root:'campaign',parent:'adset',leaf:'ad'});assert.deepEqual(META_CAPABILITIES.actionPriority.ad_click,['link_click']);assert(META_CAPABILITIES.evidenceOnlyFields.includes('clicks'));assert.deepEqual(META_CAPABILITIES.unsupportedFacts,['session']);});
test('Meta client requests one daily Ad-level DTO without putting token in URL',async()=>{let seen;const client=createMetaClient({accessToken:'token-fixture',transport:async(url,options)=>{seen={url:String(url),options};return{ok:true,status:200,json:async()=>({data:[]})}}});await client.fetchAdInsights({accountId:'act_fixture',since:'2026-08-29',until:'2026-08-29'});const url=new URL(seen.url);assert.equal(url.pathname,'/v23.0/act_fixture/insights');assert.equal(url.searchParams.get('level'),'ad');assert.equal(url.searchParams.get('time_increment'),'1');assert.deepEqual(url.searchParams.get('fields').split(','),AD_INSIGHT_FIELDS);assert(!url.searchParams.has('access_token'));assert.equal(seen.options.headers.authorization,'Bearer token-fixture');assert.deepEqual(ACCOUNT_FIELDS,['id','name','account_status','currency','timezone_name']);});
test('Meta mapper emits the seven-block canonical envelope and deterministic lineage key',()=>{const first=mapMetaInsight(fixture.insight,context),second=mapMetaInsight(fixture.insight,context);assert.deepEqual(Object.keys(first.row),['identity','entity','raw_metrics','metric_support','currency','time','provenance']);validateCanonicalRow(first.row);validateEntityHierarchy(first.row.identity,first.row.entity);assert.equal(first.entityKey,second.entityKey);assert.equal(first.entityKey,buildEntityKey(first.row.identity,first.row.entity));assert.equal(first.row.entity.root_entity_id,'cmp_fixture');assert.equal(first.row.entity.parent_entity_id,'set_fixture');assert.equal(first.row.entity.entity_id,'ad_fixture');});
test('approved click and conversion aliases map once without derived KPI leakage',()=>{const {row}=mapMetaInsight(fixture.insight,context);assert.equal(row.raw_metrics.ad_click,60);assert.equal(row.raw_metrics.add_to_cart,12);assert.equal(row.raw_metrics.checkout,7);assert.equal(row.raw_metrics.purchase,4);assert.equal(row.raw_metrics.purchase_value,480);assert.equal(row.raw_metrics.session,null);assert.equal(row.metric_support.session,'unsupported');for(const key of ['clicks','ctr','cpc','roas','sales','revenue','abandoned'])assert.equal(Object.hasOwn(row.raw_metrics,key),false);});
test('missing metrics are unknown null while measured zero stays supported zero',()=>{const missing={...fixture.insight,impressions:'0',actions:[],action_values:[]};const {row}=mapMetaInsight(missing,context);assert.equal(row.raw_metrics.impression,0);assert.equal(row.metric_support.impression,'supported');for(const key of ['ad_click','add_to_cart','checkout','purchase','purchase_value']){assert.equal(row.raw_metrics[key],null);assert.equal(row.metric_support[key],'unknown');}});
test('Meta mapper rejects incomplete or synthetic hierarchy instead of inventing names',()=>{for(const patch of [{adset_id:null},{ad_name:''},{campaign_id:null}])assert.throws(()=>mapMetaInsight({...fixture.insight,...patch},context),/required/);assert.throws(()=>mapMetaInsight({...fixture.insight,spend:'-1'},context),/non-negative/);});
test('cross-currency output stops until E4-T4 binds the FX service',()=>{assert.throws(()=>mapMetaInsight(fixture.insight,{...context,targetCurrency:'TRY',fxRate:32}),/E4-T4 FX binding/);});
test('Meta adapter returns only mapped canonical rows',async()=>{const client={async fetchAdInsights(input){assert.equal(input.accountId,'act_meta_fixture');return{data:[fixture.insight]}}};const adapter=createMetaAdapter({client});const rows=await adapter.fetchCanonicalRows({accountId:'act_meta_fixture',since:'2026-08-29',until:'2026-08-29',context});assert.equal(rows.length,1);assert.equal(rows[0].row.identity.platform,'meta');assert.equal(rows[0].row.provenance.adapter_version,'meta-v1');});
