'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const fixture=JSON.parse(read('artifacts/e4-meta/e4-t1-provider-fixture.json')),server=read('server.js'),plan=read('codex-input/AdsTable_EXECUTION_PLAN_V4_2026-08-17_TR.md'),doc=read('docs/E4_T1_META_CHARACTERIZATION.md');

test('fixture is synthetic, secret-free, and preserves Meta ad lineage',()=>{assert.equal(fixture.synthetic,true);assert.equal(fixture.purpose,'contract characterization only; not production evidence');assert.deepEqual(fixture.characterization.lineage,['campaign','adset','ad']);for(const key of ['campaign_id','campaign_name','adset_id','adset_name','ad_id','ad_name'])assert.equal(typeof fixture.insight[key],'string');assert.doesNotMatch(JSON.stringify(fixture),/access_token|authorization|bearer|secret|@|https?:\/\//i);});
test('fixture covers account time currency and ten canonical metric decisions',()=>{assert.deepEqual(Object.keys(fixture.account).sort(),['account_status','currency','id','name','timezone_name']);for(const key of ['impressions','clicks','spend','actions','action_values','date_start','date_stop','account_currency'])assert.ok(Object.hasOwn(fixture.insight,key));assert.equal(fixture.characterization.conversion_rule,'standard action first, omni fallback, never sum aliases');assert.equal(fixture.characterization.ad_click_decision,'pending_business_definition');assert.equal(fixture.characterization.ad_click_recommendation,'link_click');});
test('fixture proves conversion aliases must not be summed',()=>{const value=(list,type)=>Number(list.find(x=>x.action_type===type).value);assert.equal(value(fixture.insight.actions,'add_to_cart'),value(fixture.insight.actions,'omni_add_to_cart'));assert.equal(value(fixture.insight.actions,'initiate_checkout'),value(fixture.insight.actions,'omni_initiated_checkout'));assert.equal(value(fixture.insight.actions,'purchase'),value(fixture.insight.actions,'omni_purchase'));});
test('current Meta fetch characterization remains executable baseline',()=>{for(const field of ['campaign_id','campaign_name','account_currency','impressions','reach','clicks','ctr','cpc','spend','actions','action_values','cost_per_action_type','conversion_rate_ranking'])assert.match(server,new RegExp(`fields=\\[[^\\]]*"${field}"`));for(const level of ['campaign','adset','ad'])assert.match(server,new RegExp(`e2aFetchMetaInsightsForLevel\\(conn,platformAccountId,"${level}"`));for(const action of ['add_to_cart','omni_add_to_cart','initiate_checkout','omni_initiated_checkout','purchase','omni_purchase'])assert.match(server,new RegExp(`"${action}"`));});
test('characterization forbids old derived and synthetic fallback facts from V2',()=>{assert.deepEqual(fixture.characterization.derived_fields_forbidden_in_dataset_v2,['ctr','cpc','roas','sales','revenue','abandoned']);assert.match(server,/entity_fallback:true/);assert.match(doc,/Bu satır Dataset V2 production fact'i olamaz/);assert.match(doc,/ad_click = link_click/);});
test('execution plan starts E4 and keeps E4-T1 at review gate',()=>{assert.match(plan,/## 8\. E4 — Meta referans vertical slice[\s\S]*\*\*Durum:\*\* `In progress`/);assert.match(plan,/E4-T1 — `Verification`/);assert.match(plan,/ad_click.*iş kararı/i);});
