'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {createMetaAdapter}=require('../src/providers/meta/adapter');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
const client={async fetchAdInsights(){return{data:[fixture.insight]}}};
const input=(patch={})=>({accountId:fixture.account.id,since:fixture.insight.date_start,until:fixture.insight.date_stop,context:{userId:'user-fixture',account:fixture.account,targetCurrency:'USD',...patch}});

test('Meta account metadata drives the canonical business date and same-currency facts',async()=>{const [result]=await createMetaAdapter({client}).fetchCanonicalRows(input({sourceTimezone:'UTC',sourceCurrency:'EUR'}));assert.equal(result.row.identity.date,'2026-08-29');assert.deepEqual(result.row.time,{source_timezone:'America/New_York',business_date:'2026-08-29',time_engine_version:'v1'});assert.deepEqual(result.row.currency,{source_currency:'USD',target_currency:'USD',fx_rate:1,fx_rate_date:'2026-08-29',fx_provider:'same_currency',fx_engine_version:'v1'});assert.equal(result.row.raw_metrics.spend_value,125.5);assert.equal(result.row.raw_metrics.purchase_value,480);});
test('cross-currency normalization converts every supported monetary fact exactly once',async()=>{const [result]=await createMetaAdapter({client}).fetchCanonicalRows(input({targetCurrency:'TRY',fxRate:32,fxRateDate:'2026-08-29',fxProvider:'approved-fixture'}));assert.equal(result.row.raw_metrics.spend_value,4016);assert.equal(result.row.raw_metrics.add_to_cart_value,28800);assert.equal(result.row.raw_metrics.checkout_value,20800);assert.equal(result.row.raw_metrics.purchase_value,15360);assert.deepEqual(result.row.currency,{source_currency:'USD',target_currency:'TRY',fx_rate:32,fx_rate_date:'2026-08-29',fx_provider:'approved-fixture',fx_engine_version:'v1'});});
test('account identity, currency, timezone and daily boundaries fail closed',async()=>{const adapter=createMetaAdapter({client});await assert.rejects(adapter.fetchCanonicalRows({...input(),accountId:'act_other'}),/identity mismatch/);await assert.rejects(adapter.fetchCanonicalRows(input({account:{...fixture.account,currency:'EUR'}})),/currency mismatch/);await assert.rejects(adapter.fetchCanonicalRows(input({account:{...fixture.account,timezone_name:'Not\/A_Zone'}})),/Invalid IANA timezone/);const spanning={...client,async fetchAdInsights(){return{data:[{...fixture.insight,date_stop:'2026-08-30'}]}}};await assert.rejects(createMetaAdapter({client:spanning}).fetchCanonicalRows(input()),/one business day/);});
test('cross-currency output requires an explicit positive rate and named provider',async()=>{const adapter=createMetaAdapter({client});await assert.rejects(adapter.fetchCanonicalRows(input({targetCurrency:'TRY',fxProvider:'approved'})),/positive fx_rate/);await assert.rejects(adapter.fetchCanonicalRows(input({targetCurrency:'TRY',fxRate:32})),/context.fxProvider is required/);});
