'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {CanonicalWriteBoundary}=require('../funnel-core/canonical-write-boundary');
const {InMemoryDatasetRepository}=require('../funnel-core/dataset-repository');
const {createMetaAdapter}=require('../src/providers/meta/adapter');
const {createMetaDatasetWriter}=require('../src/providers/meta/dataset-writer');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e4-meta/e4-t1-provider-fixture.json'),'utf8'));
const input={accountId:fixture.account.id,since:fixture.insight.date_start,until:fixture.insight.date_stop,context:{userId:'user-fixture',account:fixture.account,targetCurrency:'USD'}};
function harness(insight=fixture.insight){const repository=new InMemoryDatasetRepository(),adapter=createMetaAdapter({client:{async fetchAdInsights(){return{data:[insight]}}}}),writer=createMetaDatasetWriter({adapter,writeBoundary:new CanonicalWriteBoundary({repository})});return{repository,writer};}

test('Meta canonical rows write through the canonical boundary into Dataset V2 semantics',async()=>{const {repository,writer}=harness(),result=await writer.ingest(input),rows=await repository.readCanonicalRawFacts({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',platform:'meta',platform_account_id:fixture.account.id});assert.equal(result.attempted,1);assert.equal(result.persisted,1);assert.equal(rows.length,1);assert.equal(rows[0].raw_metrics.purchase,4);assert.equal(rows[0].raw_metrics.purchase_value,480);});
test('retrying the same Meta period replaces the same canonical identity instead of duplicating',async()=>{const {repository,writer}=harness();await writer.ingest(input);await writer.ingest(input);const rows=await repository.readCanonicalRawFacts({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29',platform:'meta'});assert.equal(rows.length,1);});
test('a corrected Meta result updates facts on the same identity',async()=>{let insight=fixture.insight;const repository=new InMemoryDatasetRepository(),adapter=createMetaAdapter({client:{async fetchAdInsights(){return{data:[insight]}}}}),writer=createMetaDatasetWriter({adapter,writeBoundary:new CanonicalWriteBoundary({repository})});await writer.ingest(input);insight={...fixture.insight,actions:fixture.insight.actions.map(item=>item.action_type==='purchase'?{...item,value:'5'}:item),action_values:fixture.insight.action_values.map(item=>item.action_type==='purchase'?{...item,value:'600'}:item)};await writer.ingest(input);const rows=await repository.readCanonicalRawFacts({user_id:'user-fixture',from:'2026-08-29',to:'2026-08-29'});assert.equal(rows.length,1);assert.equal(rows[0].raw_metrics.purchase,5);assert.equal(rows[0].raw_metrics.purchase_value,600);});
test('ownership, canonical shape, entity key and write cardinality fail before success is reported',async()=>{const boundary={calls:0,async write(rows){this.calls+=1;return rows;}};const valid=(await createMetaAdapter({client:{async fetchAdInsights(){return{data:[fixture.insight]}}}}).fetchCanonicalRows(input))[0];for(const result of [{...valid,row:{...valid.row,identity:{...valid.row.identity,user_id:'other'}}},{...valid,entityKey:'wrong'},{}]){const writer=createMetaDatasetWriter({adapter:{async fetchCanonicalRows(){return[result]}},writeBoundary:boundary});await assert.rejects(writer.ingest(input),/ownership mismatch|entity key mismatch|canonical row|identity/);}assert.equal(boundary.calls,0);const writer=createMetaDatasetWriter({adapter:{async fetchCanonicalRows(){return[valid]}},writeBoundary:{async write(){return[];}}});await assert.rejects(writer.ingest(input),/cardinality mismatch/);await assert.rejects(createMetaDatasetWriter({adapter:{fetchCanonicalRows(){}},writeBoundary:boundary}).ingest({...input,accountId:'act_other'}),/account ownership mismatch/);});
