'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {createGoogleLiveRefresh,sourceJobIdentity,uuidIdentity}=require('../src/providers/google/live-refresh');
const standard=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e5-google/e5-t3-standard-ad-fixture.json'),'utf8'));
const pmax=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e5-google/e5-t4-pmax-asset-group-fixture.json'),'utf8'));
function dbHarness(){const writes=[];return{writes,from(table){assert.equal(table,'performance_dataset_rows_v2');return{upsert(payload){writes.push(payload);return{select:async()=>({data:payload,error:null})};}}}};}
function conversionRows(fixture,type){return fixture.row.conversion_actions.map(action=>({campaign:{id:fixture.row.campaign.id},...(type==='standard'?{adGroupAd:{ad:{id:fixture.row.adGroupAd.ad.id}}}:{assetGroup:{id:fixture.row.assetGroup.id}}),segments:{conversionActionCategory:action.category,conversionActionName:action.name||null},metrics:{conversions:action.conversions,conversionsValue:action.conversions_value}}));}
function searchHarness({empty=false}={}){const queries=[];return{queries,search:async({query})=>{queries.push(query);if(query.includes('FROM customer'))return{results:[{customer:{id:standard.customer.id,currencyCode:'USD',timeZone:'America/Los_Angeles'}}]};if(empty)return{results:[]};const isPmax=query.includes('FROM asset_group'),isConversions=query.includes('conversion_action_category'),fixture=isPmax?pmax:standard;return{results:isConversions?conversionRows(fixture,isPmax?'performance_max':'standard'):[fixture.row]};}};}
function live(db,search){return createGoogleLiveRefresh({supabaseClient:db,search,resolveTargetCurrency:async()=> 'TRY',resolveFxRate:async(_source,_target,{rateDate})=>({fx_rate:32,fx_rate_date:rateDate,fx_provider:'approved-live-test'}),now:()=>new Date('2026-08-31T02:30:00.000Z')});}
test('live Google refresh writes Standard and PMax directly to V2 for one customer business date',async()=>{const db=dbHarness(),h=searchHarness(),userId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',jobId='11111111-1111-4111-8111-111111111111',result=await live(db,h.search).run({userId:{id:userId},customerId:standard.customer.id,loginCustomerId:'999',sourceJobId:{id:jobId}});assert.equal(result.mode,'v2_primary');assert.equal(result.legacy_v1_written,false);assert.deepEqual(result.dataset_v2,{attempted:2,persisted:2,empty_provider_result:false});assert.equal(db.writes.length,2);assert.deepEqual(db.writes.map(write=>write[0].campaign_type),['standard','performance_max']);assert.equal(db.writes.every(write=>write[0].source_job_id===jobId&&write[0].user_id===userId),true);assert.equal(db.writes[0][0].purchase_value,11520);assert.equal(db.writes[1][0].purchase_value,22400);const dataQueries=h.queries.slice(1);assert.equal(dataQueries.length,4);assert.equal(dataQueries.every(query=>query.includes("segments.date = '2026-08-30'")&&!/DURING|LAST_30/i.test(query)),true);});
test('live Google zero-row result is complete and creates no fake V2 rows',async()=>{const db=dbHarness(),h=searchHarness({empty:true}),result=await live(db,h.search).run({userId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',customerId:standard.customer.id,loginCustomerId:'999'});assert.deepEqual(result.dataset_v2,{attempted:0,persisted:0,empty_provider_result:true});assert.deepEqual(db.writes,[]);assert.equal(result.google_v2_evidence.all_branches_complete,true);});
test('live Google evidence excludes customer, login customer and raw provider rows',async()=>{const db=dbHarness(),h=searchHarness({empty:true}),userId='cccccccc-cccc-4ccc-8ccc-cccccccccccc',result=await live(db,h.search).run({userId,customerId:standard.customer.id,loginCustomerId:'secret-login'}),evidence=JSON.stringify(result.google_v2_evidence);assert.equal(evidence.includes(standard.customer.id),false);assert.equal(evidence.includes(userId),false);assert.equal(evidence.includes('secret-login'),false);assert.equal(evidence.includes('raw_metrics'),false);assert.equal(evidence.includes('campaign_name'),false);});
test('source job UUID extraction rejects object stringification before Dataset V2',()=>{const id='22222222-2222-4222-8222-222222222222';assert.equal(sourceJobIdentity(id),id);assert.equal(sourceJobIdentity({sourceJobId:id}),id);assert.throws(()=>sourceJobIdentity({}),/identity is invalid/);assert.throws(()=>sourceJobIdentity('[object Object]'),/identity is invalid/);});
test('user UUID extraction prevents object values in currency lookup and Dataset V2',()=>{const id='33333333-3333-4333-8333-333333333333';assert.equal(uuidIdentity({id},'Google user'),id);assert.throws(()=>uuidIdentity({email:'hidden'},'Google user'),/Google user identity is invalid/);});
