'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {CONVERSION_MAPPING_VERSION,mapGoogleConversions,selectConversion}=require('../src/providers/google/conversion-mapping');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e5-google/e5-t1-conversion-fixture.json'),'utf8'));

test('Google conversion categories produce exact count/value with redacted provenance',()=>{const mapped=mapGoogleConversions(fixture.actions);for(const [kind,expected] of Object.entries(fixture.expected)){assert.equal(mapped[kind].count,expected.count);assert.equal(mapped[kind].value,expected.value);assert.equal(mapped[kind].provenance.mapping_version,CONVERSION_MAPPING_VERSION);assert.equal(mapped[kind].provenance.match_basis,expected.match_basis);assert.equal(mapped[kind].provenance.matched_action_count,expected.matched_action_count);assert.equal(JSON.stringify(mapped[kind].provenance).includes('Primary Sale'),false);}});
test('category wins and exact name fallback never double counts',()=>{const result=selectConversion([{name:'purchase',category:'SUBMIT_LEAD_FORM',conversions:50,conversions_value:500},{name:'Other',category:'PURCHASE',conversions:2,conversions_value:40}],'purchase');assert.equal(result.count,2);assert.equal(result.value,40);assert.equal(result.provenance.match_basis,'category');assert.equal(result.provenance.fallback_used,false);});
test('broad names and generic lead value cannot become purchase',()=>{for(const name of ['sale campaign','order complete','cart purchase intent']){const result=selectConversion([{name,category:'SUBMIT_LEAD_FORM',conversions:9,conversions_value:999}],'purchase');assert.equal(result.count,null);assert.equal(result.value,null);assert.equal(result.provenance.match_basis,null);}});
test('missing conversion remains null while measured zero remains supported zero',()=>{assert.equal(selectConversion([],'checkout').count,null);const zero=selectConversion([{name:'Checkout',category:'BEGIN_CHECKOUT',conversions:0,conversions_value:0}],'checkout');assert.equal(zero.count,0);assert.equal(zero.value,0);assert.throws(()=>selectConversion([{category:'PURCHASE',conversions:-1}],'purchase'),/non-negative/);});
test('fixture is synthetic, versioned, and contains no credential material',()=>{assert.equal(fixture.synthetic,true);assert.match(fixture.fixture_version,/^e5-t1-/);assert.doesNotMatch(JSON.stringify(fixture),/access[_-]?token|developer[_-]?token|client[_-]?secret|refresh[_-]?token/i);});
