'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const {GOOGLE_CUSTOMER_METADATA_QUERY,googleCustomerMetadataEvidence,normalizeGoogleCustomerMetadata}=require('../src/providers/google/account-metadata');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../artifacts/e5-google/e5-t2-customer-metadata-fixture.json'),'utf8'));

test('Google customer metadata binds exact identity, currency, timezone and business date',()=>{const result=normalizeGoogleCustomerMetadata(fixture.response,{requestedCustomerId:fixture.requested_customer_id,observedAt:fixture.observed_at});assert.equal(result.source_currency,fixture.expected.source_currency);assert.equal(result.source_timezone,fixture.expected.source_timezone);assert.equal(result.business_date,fixture.expected.business_date);assert.equal(result.id,fixture.requested_customer_id);});
test('metadata query requests only exact customer identity, currency and timezone',()=>{assert.equal(GOOGLE_CUSTOMER_METADATA_QUERY,'SELECT customer.id, customer.currency_code, customer.time_zone FROM customer LIMIT 1');assert.doesNotMatch(GOOGLE_CUSTOMER_METADATA_QUERY,/metrics\.|segments\.|descriptive_name/i);});
test('wrong customer and missing or invalid provider metadata fail closed',()=>{assert.throws(()=>normalizeGoogleCustomerMetadata(fixture.response,{requestedCustomerId:'9999999999',observedAt:fixture.observed_at}),/identity mismatch/);for(const patch of [{currencyCode:null},{currencyCode:'US'},{timeZone:null},{timeZone:'UTC+3'}]){const response={results:[{customer:{...fixture.response.results[0].customer,...patch}}]};assert.throws(()=>normalizeGoogleCustomerMetadata(response,{requestedCustomerId:fixture.requested_customer_id,observedAt:fixture.observed_at}));}assert.throws(()=>normalizeGoogleCustomerMetadata({results:[]},{requestedCustomerId:fixture.requested_customer_id}),/exactly one row/);});
test('redacted evidence contains no customer identity or raw response',()=>{const normalized=normalizeGoogleCustomerMetadata(fixture.response,{requestedCustomerId:fixture.requested_customer_id,observedAt:fixture.observed_at}),evidence=googleCustomerMetadataEvidence(normalized);assert.deepEqual(evidence,{currency_present:true,timezone_present:true,business_date:'2026-08-30',time_engine_version:'v1',identity_verified:true});assert.equal(JSON.stringify(evidence).includes(fixture.requested_customer_id),false);assert.equal(JSON.stringify(evidence).includes('America/Los_Angeles'),false);});
test('fixture is synthetic, versioned and secret-free',()=>{assert.equal(fixture.synthetic,true);assert.match(fixture.fixture_version,/^e5-t2-/);assert.doesNotMatch(JSON.stringify(fixture),/access[_-]?token|developer[_-]?token|client[_-]?secret|refresh[_-]?token/i);});
