'use strict';

const assert=require('node:assert/strict');const test=require('node:test');
const {createKlaviyoDatasetWriter,createKlaviyoShadowDualWrite,evaluateKlaviyoParity,normalizeKlaviyoTimeFxMessage}=require('../src/providers/klaviyo/runtime');

const base={branch:'campaign',channel:'email',root:{id:'campaign-1',name:'Campaign'},message:{id:'message-1',name:'Message'},metrics:{delivered:100,unique_clicks:10,add_to_cart:2,add_to_cart_value:4,checkout:1,checkout_value:3,purchase:1,purchase_value:2},metric_support:{},spend_allocation:{monthlyPlanCost:100,dailySentCount:100,monthlySentCount:1000,periodClosed:true}};
const context={userId:'11111111-1111-4111-8111-111111111111',accountId:'account-1',account:{id:'account-1',currency:'USD',timezone:'America/New_York'},providerDate:'2026-09-07',targetCurrency:'TRY',sourceJobId:'22222222-2222-4222-8222-222222222222'};
const normalized=(input=base)=>normalizeKlaviyoTimeFxMessage(input,{...context,fxRate:40,fxRateDate:'2026-09-07',fxProvider:'test_fx'}).row;

test('E7 T8 binds account business date and converts every supported monetary fact once',()=>{const row=normalized();assert.equal(row.identity.date,'2026-09-07');assert.equal(row.time.source_timezone,'America/New_York');assert.equal(row.currency.fx_rate,40);assert.equal(row.raw_metrics.spend_value,400);assert.equal(row.raw_metrics.purchase_value,80)});
test('Dataset V2 writer handles Campaign/Flow and Email/SMS through one boundary',async()=>{let written;const writer=createKlaviyoDatasetWriter({resolveFxRate:async()=>({fx_rate:1,fx_rate_date:'2026-09-07',fx_provider:'same_currency'}),writeBoundary:{write:async rows=>(written=rows)}});const flow={...base,branch:'flow',channel:'sms',root:{id:'flow-1',name:'Flow'},message:{id:'message-1',name:'SMS'},metrics:{...base.metrics,provider_spend:3},spend_allocation:{}};const result=await writer.ingest({accountId:'account-1',rows:[base,flow],context:{...context,targetCurrency:'USD'}});assert.equal(result.persisted,2);assert.equal(written[0].entity.entity_type,'campaign_message');assert.equal(written[1].entity.entity_type,'flow_message');assert.notEqual(written[0].entity.root_entity_id,written[1].entity.root_entity_id)});
test('zero-row input writes no fake facts',async()=>{let written;const writer=createKlaviyoDatasetWriter({resolveFxRate:async()=>({fx_rate:1,fx_rate_date:'2026-09-07',fx_provider:'same_currency'}),writeBoundary:{write:async rows=>(written=rows)}});const result=await writer.ingest({accountId:'account-1',rows:[],context:{...context,targetCurrency:'USD'}});assert.deepEqual(written,[]);assert.equal(result.empty_provider_result,true)});
test('parity requires non-empty exact branch, channel, support, facts, time and FX',()=>{const row=normalized();assert.equal(evaluateKlaviyoParity({legacyRows:[row],v2Rows:[structuredClone(row)]}).status,'PASS');assert.equal(evaluateKlaviyoParity({legacyRows:[],v2Rows:[]}).status,'FAIL');const drift=structuredClone(row);drift.raw_metrics.ad_click=11;assert.equal(evaluateKlaviyoParity({legacyRows:[row],v2Rows:[drift]}).facts_match,false);const wrongDate=structuredClone(row);wrongDate.identity.date='2026-09-06';wrongDate.time.business_date='2026-09-06';assert.equal(evaluateKlaviyoParity({legacyRows:[row],v2Rows:[wrongDate]}).normalization_match,false)});
test('writer rejects duplicate and ownership mismatch with safe stages',async()=>{const writer=createKlaviyoDatasetWriter({resolveFxRate:async()=>({fx_rate:1,fx_rate_date:'2026-09-07',fx_provider:'same_currency'}),writeBoundary:{write:async rows=>rows}});await assert.rejects(()=>writer.ingest({accountId:'account-1',rows:[base,base],context:{...context,targetCurrency:'USD'}}),error=>error.safe_stage==='KLAVIYO_ADAPTER');await assert.rejects(()=>writer.ingest({accountId:'other',rows:[base],context:{...context,targetCurrency:'USD'}}),/ownership mismatch/)});
test('shadow failure never changes successful legacy output or activates production',async()=>{const legacy={id:'legacy'};const shadow=createKlaviyoShadowDualWrite({legacyWrite:async()=>legacy,v2Run:async()=>{const error=new Error('db');error.safe_stage='KLAVIYO_DATASET_V2_WRITE';throw error},loadLegacyRows:async()=>[],loadV2Rows:async()=>[]});const result=await shadow.run({accountId:'account-1'});assert.equal(result.legacy_result,legacy);assert.equal(result.shadow_evidence.status,'FAIL');assert.equal(result.shadow_evidence.failure_stage,'KLAVIYO_DATASET_V2_WRITE');assert.equal(result.shadow_evidence.production_activation,false)});
