"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const{createOnboardingBackfillPlan}=require("../src/backfill/onboarding-scope");
const active=(platform,id)=>({platform,platform_account_id:id,ownership_status:"active",connected:true});

test("E9 T1 plans yesterday finalized before today provisional",()=>{const plan=createOnboardingBackfillPlan({accounts:[active("meta","m1")]});assert.deepEqual(plan.units,[{platform:"meta",platform_account_id:"m1",date_key:"yesterday",finality:"finalized",priority:1},{platform:"meta",platform_account_id:"m1",date_key:"today",finality:"provisional",priority:2}]);assert.equal(plan.older_history_automatic,false);assert.equal(plan.day_14_behavior,"continue_daily_accumulation")});
test("E9 T1 includes approved providers and up to three active owned accounts each",()=>{const accounts=[];for(const platform of ["meta","google","tiktok","klaviyo"])for(let i=1;i<=4;i++)accounts.push(active(platform,`${platform}-${i}`));const plan=createOnboardingBackfillPlan({accounts});assert.equal(plan.units.length,4*3*2);assert.equal(plan.excluded.filter(row=>row.reason==="account_limit").length,4)});
test("E9 T1 never schedules parked inactive unowned or unsupported accounts",()=>{const plan=createOnboardingBackfillPlan({accounts:[active("pinterest","p1"),active("organic","o1"),active("other","x1"),{...active("meta","m1"),connected:false},{...active("google","g1"),ownership_status:"disconnected"}]});assert.equal(plan.units.length,0);assert.deepEqual(plan.excluded.map(row=>row.reason),["parked","parked","unsupported","inactive_or_unowned","inactive_or_unowned"])});
test("E9 T1 deduplicates account identities and returns immutable policy",()=>{const plan=createOnboardingBackfillPlan({accounts:[active("meta","m1"),active("meta","m1")]});assert.equal(plan.units.length,2);assert.equal(Object.isFrozen(plan),true);assert.equal(Object.isFrozen(plan.units),true);assert.throws(()=>createOnboardingBackfillPlan({accounts:{}}),/accounts must be an array/)});
