"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fixtures=require("../funnel-core/fixtures");
const {createIdempotentBackfillBatchWriter}=require("../src/backfill/idempotent-batch");
function checkpoint(row,overrides={}){return{user_id:row.identity.user_id,platform:row.identity.platform,platform_account_id:row.identity.platform_account_id,business_date:row.time.business_date,status:"running",...overrides}}
test("E9 T4 delegates one scoped batch through the canonical boundary",async()=>{const row=fixtures.metaPaid(),calls=[],writer=createIdempotentBackfillBatchWriter({writeBoundary:{async write(rows){calls.push(rows);return structuredClone(rows)}}});const result=await writer.write({checkpoint:checkpoint(row),rows:[row]});assert.equal(calls.length,1);assert.equal(result.attempted,1);assert.equal(result.persisted,1);assert.match(result.idempotency_conflict,/entity_key/)});
test("E9 T4 accepts an empty canonical batch without inventing facts",async()=>{let calls=0;const row=fixtures.googleStandard(),writer=createIdempotentBackfillBatchWriter({writeBoundary:{async write(rows){calls++;return rows}}});const result=await writer.write({checkpoint:checkpoint(row),rows:[]});assert.equal(calls,1);assert.equal(result.persisted,0)});
test("E9 T4 rejects rows outside the claimed checkpoint",async()=>{const row=fixtures.metaPaid(),writer=createIdempotentBackfillBatchWriter({writeBoundary:{write(){throw new Error("must not write")}}});await assert.rejects(writer.write({checkpoint:checkpoint(row,{platform_account_id:"other"}),rows:[row]}),/outside checkpoint scope/)});
test("E9 T4 requires a currently claimed checkpoint",async()=>{const row=fixtures.metaPaid(),writer=createIdempotentBackfillBatchWriter({writeBoundary:{write(){throw new Error("must not write")}}});await assert.rejects(writer.write({checkpoint:checkpoint(row,{status:"failed"}),rows:[row]}),/must be claimed/)});
test("E9 T4 rejects duplicate canonical identities before persistence",async()=>{const row=fixtures.metaPaid(),writer=createIdempotentBackfillBatchWriter({writeBoundary:{write(){throw new Error("must not write")}}});await assert.rejects(writer.write({checkpoint:checkpoint(row),rows:[row,structuredClone(row)]}),/duplicate canonical identity/)});
test("E9 T4 fails closed when persistence changes batch cardinality or identity",async()=>{const row=fixtures.metaPaid();let writer=createIdempotentBackfillBatchWriter({writeBoundary:{async write(){return[]}}});await assert.rejects(writer.write({checkpoint:checkpoint(row),rows:[row]}),/cardinality/);writer=createIdempotentBackfillBatchWriter({writeBoundary:{async write(rows){const changed=structuredClone(rows);changed[0].entity.entity_id="changed";return changed}}});await assert.rejects(writer.write({checkpoint:checkpoint(row),rows:[row]}),/identity mismatch/)});
