"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {PROVIDERS,buildProviderReadinessDashboard}=require("../src/backfill/readiness-dashboard");
function ready(platform,status="PASS",overrides={}){return{platform,status,expected_checkpoints:2,completed_checkpoints:2,canonical_rows:4,duplicate_rows:0,...overrides}}
test("E9 T6 presents provider readiness and parity without account identities",()=>{const result=buildProviderReadinessDashboard({readiness_evidence:[ready("meta"),ready("google")],parity_evidence:[{platform:"meta",status:"PASS"},{platform:"google",status:"PASS"}]});assert.equal(result.status,"READY");assert.equal(result.providers_ready,2);assert.deepEqual(result.providers.map(item=>item.platform),["meta","google"]);assert.equal(JSON.stringify(result).includes("platform_account_id"),false)});
test("E9 T6 keeps readiness separate from missing parity",()=>{const result=buildProviderReadinessDashboard({readiness_evidence:[ready("tiktok")],parity_evidence:[]});assert.equal(result.status,"BLOCKED");assert.equal(result.providers[0].status,"PARITY_PENDING");assert.equal(result.providers[0].readiness_passed,1)});
test("E9 T6 blocks a provider on readiness or parity failure",()=>{let result=buildProviderReadinessDashboard({readiness_evidence:[ready("meta","FAIL")],parity_evidence:[{platform:"meta",status:"PASS"}]});assert.equal(result.providers[0].status,"BLOCKED");result=buildProviderReadinessDashboard({readiness_evidence:[ready("klaviyo")],parity_evidence:[{platform:"klaviyo",status:"FAIL"}]});assert.equal(result.providers[0].status,"BLOCKED")});
test("E9 T6 aggregates counts by provider deterministically",()=>{const result=buildProviderReadinessDashboard({readiness_evidence:[ready("google"),ready("google","PASS",{expected_checkpoints:2,completed_checkpoints:1,canonical_rows:3,duplicate_rows:1})],parity_evidence:[{platform:"google",status:"PASS"},{platform:"google",status:"NOT_AVAILABLE"}]});assert.deepEqual(result.providers[0],{platform:"google",status:"PARITY_PENDING",account_evidence:2,readiness_passed:2,expected_checkpoints:4,completed_checkpoints:3,canonical_rows:7,duplicate_rows:1,parity_evidence:2,parity_passed:1})});
test("E9 T6 rejects parked unknown malformed and empty evidence",()=>{assert.deepEqual(PROVIDERS,["meta","google","tiktok","klaviyo"]);assert.throws(()=>buildProviderReadinessDashboard(),/requires readiness evidence/);assert.throws(()=>buildProviderReadinessDashboard({readiness_evidence:[ready("pinterest")]}),/unsupported/);assert.throws(()=>buildProviderReadinessDashboard({readiness_evidence:[ready("meta","UNKNOWN")]}),/invalid readiness/);assert.throws(()=>buildProviderReadinessDashboard({readiness_evidence:[ready("meta","PASS",{canonical_rows:-1})]}),/non-negative integer/)});
