"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fixtures=require("../funnel-core/fixtures");
const {evaluateBackfillDataReadiness}=require("../src/backfill/data-readiness");
function point(row,date_key="today",status="completed"){return{user_id:row.identity.user_id,platform:row.identity.platform,platform_account_id:row.identity.platform_account_id,business_date:row.time.business_date,date_key,status}}
test("E9 T5 passes complete fresh canonical evidence",()=>{const row=fixtures.metaPaid(),expected=[point(row)],result=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:expected,rows:[row],as_of_business_date:row.time.business_date});assert.equal(result.status,"PASS");assert.deepEqual(result.gates,{completeness:true,duplicates:true,metric_support:true,timezone:true,fx:true,freshness:true})});
test("E9 T5 treats completed provider zero-row as complete without synthetic facts",()=>{const row=fixtures.googleStandard(),expected=[point(row)],result=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:expected,rows:[],as_of_business_date:row.time.business_date});assert.equal(result.status,"PASS");assert.equal(result.canonical_rows,0)});
test("E9 T5 fails incomplete or stale checkpoint coverage",()=>{const row=fixtures.metaPaid(),expected=[point(row)],incomplete=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:[],rows:[],as_of_business_date:row.time.business_date});assert.equal(incomplete.gates.completeness,false);assert.equal(incomplete.gates.freshness,false);const stale=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:expected,rows:[row],as_of_business_date:"2026-08-19"});assert.equal(stale.gates.freshness,false)});
test("E9 T5 detects duplicate canonical identities",()=>{const row=fixtures.metaPaid(),expected=[point(row)],result=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:expected,rows:[row,structuredClone(row)],as_of_business_date:row.time.business_date});assert.equal(result.status,"FAIL");assert.equal(result.duplicate_rows,1);assert.equal(result.gates.duplicates,false)});
test("E9 T5 reports malformed support timezone and FX without leaking row values",()=>{const row=fixtures.metaPaid(),expected=[point(row)],bad=structuredClone(row);bad.metric_support.impression="bad";bad.time.source_timezone="";bad.currency.fx_rate=0;const result=evaluateBackfillDataReadiness({expected_checkpoints:expected,checkpoints:expected,rows:[bad],as_of_business_date:row.time.business_date});assert.equal(result.status,"FAIL");assert.equal(result.gates.metric_support,false);assert.equal(result.gates.timezone,false);assert.equal(result.gates.fx,false);assert.equal(JSON.stringify(result).includes("bad"),false)});
test("E9 T5 rejects duplicate expected and observed checkpoint identities",()=>{const row=fixtures.metaPaid(),pointValue=point(row);assert.throws(()=>evaluateBackfillDataReadiness({expected_checkpoints:[pointValue,pointValue],as_of_business_date:row.time.business_date}),/duplicate expected/);assert.throws(()=>evaluateBackfillDataReadiness({expected_checkpoints:[pointValue],checkpoints:[pointValue,pointValue],as_of_business_date:row.time.business_date}),/duplicate checkpoint/) });
