"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const{createPinterestOAuthHandlers}=require("../src/oauth/pinterest-handlers");
const{discoverPinterestAdAccounts}=require("../src/providers/pinterest/account-discovery");
const{createPinterestClient}=require("../src/providers/pinterest/client");
const fs=require("node:fs"),path=require("node:path"),server=fs.readFileSync(path.join(__dirname,"..","server.js"),"utf8");
function response(){return{code:200,body:null,location:null,status(v){this.code=v;return this},send(v){this.body=v;return this},json(v){this.body=v;return this},redirect(v){this.location=v;return this}}}
function handlers(overrides={}){return createPinterestOAuthHandlers({config:{clientId:"client",clientSecret:"secret",redirectUri:"https://app/auth/pinterest/callback",scopes:"ads:read,user_accounts:read",authorizationBase:"https://www.pinterest.com/oauth/"},requireConnectAccess:async()=>({userId:"verified-user"}),createTransaction:async()=>({state:"state"}),consumeTransaction:async()=>({user_id:"verified-user"}),sendAuthorizationResponse:(_req,res,url)=>res.json({authorization_url:url}),exchangeToken:async()=>({access_token:"access",refresh_token:"refresh",expires_in:3600}),saveConnection:async()=>{},parseExpiry:()=>"expiry",...overrides})}
test("Pinterest OAuth binds state and persistence to verified transaction identity",async()=>{let transaction,write;const start=response(),callback=response(),h=handlers({createTransaction:async(...args)=>(transaction=args,{state:"state"}),saveConnection:async(...args)=>{write=args}});await h.start({query:{}},start);assert.deepEqual(transaction,["verified-user","pinterest","https://app/auth/pinterest/callback"]);assert.match(start.body.authorization_url,/scope=ads%3Aread%2Cuser_accounts%3Aread/);await h.callback({query:{code:"code",state:"state"}},callback);assert.equal(write[0],"verified-user");assert.equal(write[2].metadata.accountSelectionRequired,true);assert.equal(callback.location,"/dashboard?pinterest_connected=1&account_selection_required=1")});
test("Pinterest callback rejects invalid state before token exchange",async()=>{let exchanged=false;const res=response();await handlers({consumeTransaction:async()=>null,exchangeToken:async()=>{exchanged=true}}).callback({query:{code:"code",state:"bad"}},res);assert.equal(exchanged,false);assert.equal(res.location,"/dashboard?pinterest_error=invalid_state")});
test("Pinterest account discovery requires real identity currency and timezone",()=>{const accounts=discoverPinterestAdAccounts({items:[{id:"a1",name:"Store",currency:"usd",timezone:"Europe/Istanbul"},{id:"a1",name:"duplicate",currency:"USD",timezone:"UTC"},{id:"missing",name:"Incomplete"},null]});assert.deepEqual(accounts,[{platform:"pinterest",platform_account_id:"a1",account_name:"Store",currency:"USD",timezone:"Europe/Istanbul"}]);assert.equal(Object.isFrozen(accounts),true)});
test("Pinterest factories and malformed provider shapes fail closed",()=>{assert.throws(()=>createPinterestOAuthHandlers({}),/config is required/);assert.deepEqual(discoverPinterestAdAccounts({items:{}}),[])});
test("Pinterest client renews an expired token once and never exposes provider bodies",async()=>{const calls=[],writes=[];const fetchImpl=async(url,options)=>{calls.push({url,authorization:options.headers.Authorization});if(url.endsWith("/oauth/token"))return{ok:true,status:200,json:async()=>({access_token:"new",refresh_token:"new-refresh",expires_in:3600})};return{ok:true,status:200,text:async()=>JSON.stringify({items:[]})}};const client=createPinterestClient({apiBase:"https://api.pinterest.com/v5",clientCredentials:"credentials",saveConnection:async(...args)=>writes.push(args),getConnection:async()=>({user_id:"user",access_token:"new",refresh_token:"new-refresh",token_expires_at:"2099-01-01"}),parseExpiry:()=>"2099-01-01",fetchImpl,now:()=>Date.parse("2026-01-01")});assert.deepEqual(await client.request({user_id:"user",access_token:"old",refresh_token:"refresh",token_expires_at:"2025-01-01"},"/ad_accounts"),{items:[]});assert.equal(writes.length,1);assert.equal(calls[1].authorization,"Bearer new")});
test("Pinterest client rejects HTML and redacts provider error content",async()=>{const client=createPinterestClient({apiBase:"https://api.pinterest.com/v5",clientCredentials:"credentials",saveConnection:async()=>{},getConnection:async()=>null,parseExpiry:()=>null,fetchImpl:async()=>({ok:false,status:502,text:async()=>"<html>secret upstream error</html>"})});await assert.rejects(()=>client.request({access_token:"access"},"/ad_accounts"),error=>error.message==="Pinterest request failed (502)."&&!error.message.includes("secret"))});
test("Pinterest status and dashboard require explicit account selection",()=>{assert.match(server,/normalizePlatformAccountId\(conn\.account_id\|\|conn\.metadata\?\.selectedPlatformAccountId\)/);assert.match(server,/conn\.metadata\?\.accountSelectionRequired!==true/);for(const file of ["dashboard.html","dashboard-patch17H-fixed.html","dashboard-patch17H-fixed-v2.html"]){const html=fs.readFileSync(path.join(__dirname,"..","public",file),"utf8");assert.match(html,/id="pinterestConnectButton"/);assert.match(html,/pinterest:"pinterest_connected"/);assert.match(html,/pinterest:"\/api\/pinterest\/adaccounts"/)}});
