"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const path=require("node:path");
const {spawnSync}=require("node:child_process");

const modulePath=path.join(__dirname,"../security/provider-token-backfill-write-operator.js");
const {CONFIRMATION,parseWriteArguments,assertRuntime,runWriteOperator}=require(modulePath);
const key=crypto.createHash("sha256").update("write-test-key").digest("base64");
const reference=crypto.createHash("sha256").update("write-reference-key").digest("base64");
const project="abcdefghijklmnopqrst";
const env={GITHUB_ACTIONS:"true",GITHUB_REF:"refs/heads/main",GITHUB_RUN_ID:"123",GITHUB_SHA:"a".repeat(40),SUPABASE_URL:`https://${project}.supabase.co`,SUPABASE_PROJECT_REF:project,SUPABASE_SERVICE_ROLE_KEY:"role",PROVIDER_TOKEN_ACTIVE_KEY_ID:"current",PROVIDER_TOKEN_ENCRYPTION_KEYS:JSON.stringify({current:key}),PROVIDER_TOKEN_BACKFILL_REFERENCE_SECRET:reference};
const result=(values={})=>({scanned:9,eligible:9,written:0,alreadyEncrypted:0,rotationCandidates:0,empty:0,failed:0,nextCursor:null,failures:[],...values});
function injected(results){const calls=[];return {calls,deps:{createVault(){return {};},createClient(){return {from(){}};},createStore(){return {resolve(){},write(){}};},createBackfill(){return async options=>{calls.push(options);const next=results.shift();if(next instanceof Error)throw next;return next;};}}};}
const argv=["--expected-total","9","--confirm",CONFIRMATION];

test("import is side-effect-free",()=>{const child=spawnSync(process.execPath,["-e",`require(${JSON.stringify(modulePath)}); process.stdout.write("imported")`],{encoding:"utf8",env:{}});assert.equal(child.status,0);assert.equal(child.stdout,"imported");assert.equal(child.stderr,"");});
test("runtime guard rejects local, branch, run ID, and SHA errors",()=>{for(const change of [{GITHUB_ACTIONS:"false"},{GITHUB_REF:"refs/heads/dev"},{GITHUB_RUN_ID:""},{GITHUB_SHA:"bad"}])assert.throws(()=>assertRuntime({...env,...change}),{code:"BACKFILL_WRITE_RUNTIME_FORBIDDEN"});});
test("arguments require exact confirmation and bounded integer",()=>{assert.equal(parseWriteArguments(argv).expectedTotal,9);for(const args of [[],["--expected-total","9","--confirm","wrong"],["--expected-total","0","--confirm",CONFIRMATION],["--expected-total","26","--confirm",CONFIRMATION],["--expected-total","1.5","--confirm",CONFIRMATION],["--expected-total","garbage","--confirm",CONFIRMATION]])assert.throws(()=>parseWriteArguments(args));});
test("cursor, batch size, mode, and unknown arguments are rejected",()=>{for(const option of ["--cursor","--batch-size","--mode"])assert.throws(()=>parseWriteArguments([...argv,option,"x"]),{code:"BACKFILL_WRITE_ARGUMENT_INVALID"});});
test("runtime and config fail before dependencies are composed",async()=>{let composed=false;const deps={createClient(){composed=true;}};await assert.rejects(runWriteOperator({argv,env:{...env,GITHUB_REF:"bad"},dependencies:deps}),{stage:"runtime"});await assert.rejects(runWriteOperator({argv,env:{...env,SUPABASE_URL:"bad"},dependencies:deps}),{stage:"config"});assert.equal(composed,false);});
test("successful first write runs preflight, write, verification exactly once",async()=>{const x=injected([result(),result({written:9}),result({eligible:0,alreadyEncrypted:9})]);const output=await runWriteOperator({argv,env,dependencies:x.deps});assert.deepEqual(x.calls,[{dryRun:true,batchSize:25,cursor:null},{dryRun:false,batchSize:25,cursor:null},{dryRun:true,batchSize:25,cursor:null}]);assert.deepEqual(Object.keys(output),["ok","mode","contractVersion","expectedTotal","preflight","write","verification"]);assert.equal(output.verification.alreadyEncrypted,9);assert.doesNotMatch(JSON.stringify(output),/failures|nextCursor|supabase|reference|token|user/i);});
test("idempotent no-op succeeds without a redundant write count",async()=>{const x=injected([result({eligible:0,alreadyEncrypted:9}),result({eligible:0,alreadyEncrypted:9}),result({eligible:0,alreadyEncrypted:9})]);const output=await runWriteOperator({argv,env,dependencies:x.deps});assert.equal(output.write.written,0);assert.equal(output.write.alreadyEncrypted,9);});
test("every preflight invariant fails closed before write",async()=>{const bad=[result({written:1}),result({failed:1,failures:[{userRef:"b".repeat(64),platform:"meta",code:"FAIL"}]}),result({nextCursor:"opaque"}),result({scanned:8,eligible:8}),result({eligible:8})];for(const preflight of bad){const x=injected([preflight]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{stage:"preflight"});assert.equal(x.calls.length,1);assert.equal(x.calls[0].dryRun,true);}});
test("invalid write stops verification",async()=>{const x=injected([result(),result({written:8})]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{code:"BACKFILL_WRITE_INVARIANT_FAILED"});assert.equal(x.calls.length,2);});
test("partial write reports redacted actual counters and failures",async()=>{const failure={userRef:"c".repeat(64),platform:"google_ads",code:"TOKEN_WRITE_FAILED",message:"raw secret",userId:"raw-user"};const x=injected([result(),result({written:4,failed:1,failures:[failure]})]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.code==="BACKFILL_WRITE_PARTIAL_FAILURE"&&error.evidence.written===4&&error.evidence.failed===1&&JSON.stringify(error.evidence).includes("c".repeat(64))&&!JSON.stringify(error.evidence).includes("raw secret")&&!JSON.stringify(error.evidence).includes("raw-user"));assert.equal(x.calls.length,2);});
test("verification requires decryptable active encrypted state",async()=>{for(const verify of [result({eligible:1,alreadyEncrypted:8}),result({eligible:0,alreadyEncrypted:8,scanned:8}),result({eligible:0,alreadyEncrypted:9,failed:1,failures:[{userRef:"d".repeat(64),platform:"meta",code:"TOKEN_DECRYPTION_FAILED"}]})]){const x=injected([result(),result({written:9}),verify]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{code:"BACKFILL_WRITE_VERIFICATION_FAILED"});}});
test("raw thrown errors and secret values never reach operator errors",async()=>{const x=injected([new Error(`raw ${key} ${env.SUPABASE_URL}`)]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.stage==="preflight"&&!JSON.stringify(error).includes(key)&&!JSON.stringify(error).includes(env.SUPABASE_URL));});
