"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const path=require("node:path");
const {spawnSync}=require("node:child_process");

const modulePath=path.join(__dirname,"../security/provider-token-backfill-write-operator.js");
const {CONFIRMATION,ACCEPTED_DRY_RUN_EVIDENCE_ID,parseWriteArguments,assertRuntime,runWriteOperator}=require(modulePath);
const key=crypto.createHash("sha256").update("write-test-key").digest("base64");
const reference=crypto.createHash("sha256").update("write-reference-key").digest("base64");
const project="abcdefghijklmnopqrst";
const env={GITHUB_ACTIONS:"true",GITHUB_REF:"refs/heads/main",GITHUB_RUN_ID:"123",GITHUB_SHA:"a".repeat(40),SUPABASE_URL:`https://${project}.supabase.co`,SUPABASE_PROJECT_REF:project,SUPABASE_SERVICE_ROLE_KEY:"role",PROVIDER_TOKEN_ACTIVE_KEY_ID:"current",PROVIDER_TOKEN_ENCRYPTION_KEYS:JSON.stringify({current:key}),PROVIDER_TOKEN_BACKFILL_REFERENCE_SECRET:reference};
const result=(values={})=>({scanned:9,eligible:9,written:0,alreadyEncrypted:0,rotationCandidates:0,empty:0,failed:0,nextCursor:null,failures:[],...values});
function injected(results){const calls=[];return {calls,deps:{createVault(){return {};},createClient(){return {from(){}};},createStore(){return {resolve(){},write(){}};},createBackfill(){return async options=>{calls.push(options);const next=results.shift();if(next instanceof Error)throw next;return next;};}}};}
const argv=["--expected-total","9","--confirm",CONFIRMATION,"--dry-run-evidence-id",ACCEPTED_DRY_RUN_EVIDENCE_ID];

test("import is side-effect-free",()=>{const child=spawnSync(process.execPath,["-e",`require(${JSON.stringify(modulePath)}); process.stdout.write("imported")`],{encoding:"utf8",env:{}});assert.equal(child.status,0);assert.equal(child.stdout,"imported");assert.equal(child.stderr,"");});
test("runtime guard rejects local, branch, run ID, and SHA errors",()=>{for(const change of [{GITHUB_ACTIONS:"false"},{GITHUB_REF:"refs/heads/dev"},{GITHUB_RUN_ID:""},{GITHUB_SHA:"bad"}])assert.throws(()=>assertRuntime({...env,...change}),{code:"BACKFILL_WRITE_RUNTIME_FORBIDDEN"});});
test("arguments require exact confirmation and bounded integer",()=>{assert.equal(parseWriteArguments(argv).expectedTotal,9);for(const args of [[],["--expected-total","9","--confirm","wrong"],["--expected-total","0","--confirm",CONFIRMATION],["--expected-total","26","--confirm",CONFIRMATION],["--expected-total","1.5","--confirm",CONFIRMATION],["--expected-total","garbage","--confirm",CONFIRMATION]])assert.throws(()=>parseWriteArguments(args));});
test("accepted dry-run evidence ID is exact and mandatory",()=>{assert.equal(parseWriteArguments(argv).dryRunEvidenceId,"32245732566");for(const value of [undefined,"","123","text","32245732566.0"]){const args=["--expected-total","9","--confirm",CONFIRMATION];if(value!==undefined)args.push("--dry-run-evidence-id",value);assert.throws(()=>parseWriteArguments(args),{code:"BACKFILL_WRITE_EVIDENCE_ID_INVALID"});}});
test("wrong evidence ID is rejected before Supabase composition",async()=>{let composed=false;await assert.rejects(runWriteOperator({argv:["--expected-total","9","--confirm",CONFIRMATION,"--dry-run-evidence-id","123"],env,dependencies:{createClient(){composed=true;}}}),{code:"BACKFILL_WRITE_EVIDENCE_ID_INVALID"});assert.equal(composed,false);});
test("cursor, batch size, mode, and unknown arguments are rejected",()=>{for(const option of ["--cursor","--batch-size","--mode"])assert.throws(()=>parseWriteArguments([...argv,option,"x"]),{code:"BACKFILL_WRITE_ARGUMENT_INVALID"});});
test("runtime and config fail before dependencies are composed",async()=>{let composed=false;const deps={createClient(){composed=true;}};await assert.rejects(runWriteOperator({argv,env:{...env,GITHUB_REF:"bad"},dependencies:deps}),{stage:"runtime"});await assert.rejects(runWriteOperator({argv,env:{...env,SUPABASE_URL:"bad"},dependencies:deps}),{stage:"config"});assert.equal(composed,false);});
test("successful first write runs preflight, write, verification exactly once",async()=>{const x=injected([result(),result({written:9}),result({eligible:0,alreadyEncrypted:9})]);const output=await runWriteOperator({argv,env,dependencies:x.deps});assert.deepEqual(x.calls,[{dryRun:true,batchSize:25,cursor:null},{dryRun:false,batchSize:25,cursor:null},{dryRun:true,batchSize:25,cursor:null}]);assert.deepEqual(Object.keys(output),["ok","mode","contractVersion","expectedTotal","dryRunEvidenceId","preflight","write","verification"]);assert.equal(output.dryRunEvidenceId,ACCEPTED_DRY_RUN_EVIDENCE_ID);assert.equal(output.verification.alreadyEncrypted,9);assert.doesNotMatch(JSON.stringify(output),/failures|nextCursor|supabase|reference|token|user/i);});
test("idempotent no-op succeeds without a redundant write count",async()=>{const x=injected([result({eligible:0,alreadyEncrypted:9}),result({eligible:0,alreadyEncrypted:9}),result({eligible:0,alreadyEncrypted:9})]);const output=await runWriteOperator({argv,env,dependencies:x.deps});assert.equal(output.write.written,0);assert.equal(output.write.alreadyEncrypted,9);});
test("every preflight invariant fails closed before write",async()=>{const bad=[result({written:1}),result({failed:1,failures:[{userRef:"b".repeat(64),platform:"meta",code:"FAIL"}]}),result({nextCursor:"opaque"}),result({scanned:8,eligible:8}),result({eligible:8})];for(const preflight of bad){const x=injected([preflight]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{stage:"preflight"});assert.equal(x.calls.length,1);assert.equal(x.calls[0].dryRun,true);}});
test("invalid write stops verification",async()=>{const x=injected([result(),result({written:8})]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{code:"BACKFILL_WRITE_INVARIANT_FAILED"});assert.equal(x.calls.length,2);});
test("partial write reports redacted actual counters and failures",async()=>{const failure={userRef:"c".repeat(64),platform:"google_ads",code:"TOKEN_WRITE_FAILED",message:"raw secret",userId:"raw-user"};const x=injected([result(),result({written:4,failed:1,failures:[failure]})]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.code==="BACKFILL_WRITE_PARTIAL_FAILURE"&&error.evidence.written===4&&error.evidence.failed===1&&JSON.stringify(error.evidence).includes("c".repeat(64))&&!JSON.stringify(error.evidence).includes("raw secret")&&!JSON.stringify(error.evidence).includes("raw-user"));assert.equal(x.calls.length,2);});
test("invalid partial failure contracts fail closed without verification or raw fields",async()=>{for(const write of [result({written:4,failed:1,failures:[]}),result({written:4,failed:1,failures:[{userRef:"RAW-USER",platform:"meta",code:"FAIL",raw:"secret"}]}),result({written:4,failed:1,failures:undefined})]){const x=injected([result(),write]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.code==="BACKFILL_WRITE_RESULT_INVALID"&&error.evidence.scanned===9&&error.evidence.written===4&&error.evidence.alreadyEncrypted===0&&error.evidence.failed===1&&!JSON.stringify(error).includes("RAW-USER")&&!JSON.stringify(error).includes("secret"));assert.equal(x.calls.length,2);}});
test("verification requires decryptable active encrypted state",async()=>{for(const verify of [result({eligible:1,alreadyEncrypted:8}),result({eligible:0,alreadyEncrypted:8,scanned:8}),result({eligible:0,alreadyEncrypted:9,failed:1,failures:[{userRef:"d".repeat(64),platform:"meta",code:"TOKEN_DECRYPTION_FAILED"}]})]){const x=injected([result(),result({written:9}),verify]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),{code:"BACKFILL_WRITE_VERIFICATION_FAILED"});}});
test("verification failures preserve safe completed-write evidence",async()=>{for(const verify of [new Error("raw database secret"),result({eligible:1,alreadyEncrypted:8})]){const x=injected([result(),result({written:9}),verify]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.stage==="verification"&&error.evidence.writeCompleted===true&&error.evidence.preflight.eligible===9&&error.evidence.write.written===9&&!JSON.stringify(error.evidence).includes("raw database secret"));}});
test("CLI emits completed-write failure evidence and exits non-zero",()=>{const cli=path.join(__dirname,"../scripts/provider-token-backfill-write.js");const evidence={writeCompleted:true,preflight:{scanned:9},write:{written:9}};const program=`const p=${JSON.stringify(modulePath)};require.cache[p]={exports:{runWriteOperator:async()=>{const e=new Error('raw secret');e.code='BACKFILL_WRITE_VERIFICATION_FAILED';e.stage='verification';e.evidence=${JSON.stringify(evidence)};throw e;}}};process.argv=['node','cli'];require(${JSON.stringify(cli)});`;const child=spawnSync(process.execPath,["-e",program],{encoding:"utf8"});assert.equal(child.status,1);assert.equal(child.stdout,"");assert.deepEqual(JSON.parse(child.stderr),{ok:false,code:"BACKFILL_WRITE_VERIFICATION_FAILED",stage:"verification",evidence});assert.doesNotMatch(child.stderr,/raw secret/);});
test("raw thrown errors and secret values never reach operator errors",async()=>{const x=injected([new Error(`raw ${key} ${env.SUPABASE_URL}`)]);await assert.rejects(runWriteOperator({argv,env,dependencies:x.deps}),error=>error.stage==="preflight"&&!JSON.stringify(error).includes(key)&&!JSON.stringify(error).includes(env.SUPABASE_URL));});
