"use strict";
const assert=require("node:assert/strict");
const test=require("node:test");
const {createProviderTokenBackfill,decodeCursor,redactUserId}=require("../security/provider-token-backfill");

function fakeClient(rows){return {from(table){assert.equal(table,"platform_connections");let start=0,end=rows.length-1;const builder={select(){return builder;},eq(){return builder;},order(){return builder;},range(from,to){start=from;end=to;return Promise.resolve({data:rows.slice(start,end+1),error:null});}};return builder;}};}
function fakeStore(states={}){const writes=[];return {writes,async resolve({userId,platform,legacyAccessToken,legacyRefreshToken}){const value=states[`${userId}:${platform}`];if(value instanceof Error)throw value;return value||{accessToken:legacyAccessToken,refreshToken:legacyRefreshToken,source:"legacy",needsRotation:false};},async write(value){writes.push(value);}};}
const rows=[{user_id:"user-a",platform:"google",access_token:"access-a",refresh_token:"refresh-a"},{user_id:"user-b",platform:"meta",access_token:"access-b",refresh_token:null},{user_id:"user-c",platform:"tiktok",access_token:null,refresh_token:null}];

test("dry-run is resumable and never writes or returns plaintext",async()=>{const store=fakeStore();const backfill=createProviderTokenBackfill({client:fakeClient(rows),tokenStore:store});const first=await backfill.runBatch({batchSize:2,dryRun:true});assert.deepEqual(first.summary,{scanned:2,eligible:2,written:0,alreadyEncrypted:0,rotationCandidates:0,empty:0,failed:0});assert.equal(decodeCursor(first.nextCursor),2);assert.equal(store.writes.length,0);assert.doesNotMatch(JSON.stringify(first),/access-a|refresh-a|access-b/);const second=await backfill.runBatch({cursor:first.nextCursor,batchSize:2,dryRun:true});assert.equal(second.summary.empty,1);assert.equal(second.nextCursor,null);});
test("write mode migrates legacy tokens and is idempotent for current envelopes",async()=>{const store=fakeStore({"user-b:meta":{accessToken:"encrypted",refreshToken:null,source:"encrypted",needsRotation:false}});const result=await createProviderTokenBackfill({client:fakeClient(rows.slice(0,2)),tokenStore:store}).runBatch({dryRun:false});assert.equal(result.summary.written,1);assert.equal(result.summary.alreadyEncrypted,1);assert.deepEqual(store.writes[0],{userId:"user-a",platform:"google",accessToken:"access-a",refreshToken:"refresh-a"});});
test("old-key envelopes are rewritten and counted as rotation candidates",async()=>{const store=fakeStore({"user-a:google":{accessToken:"access",refreshToken:"refresh",source:"encrypted",needsRotation:true}});const result=await createProviderTokenBackfill({client:fakeClient(rows.slice(0,1)),tokenStore:store}).runBatch({dryRun:false});assert.equal(result.summary.rotationCandidates,1);assert.equal(result.summary.written,1);});
test("row failures redact user identity and do not stop later rows",async()=>{const secret="do-not-report";const failure=Object.assign(new Error(secret),{code:"TOKEN_DECRYPTION_FAILED"});const store=fakeStore({"user-a:google":failure});const result=await createProviderTokenBackfill({client:fakeClient(rows.slice(0,2)),tokenStore:store}).runBatch({dryRun:false});assert.equal(result.summary.failed,1);assert.equal(result.summary.written,1);assert.deepEqual(result.failures,[{userRef:redactUserId("user-a"),platform:"google",code:"TOKEN_DECRYPTION_FAILED"}]);assert.doesNotMatch(JSON.stringify(result),new RegExp(`${secret}|user-a`));});
test("invalid cursors and unsafe batch sizes are rejected",async()=>{const backfill=createProviderTokenBackfill({client:fakeClient([]),tokenStore:fakeStore()});await assert.rejects(()=>backfill.runBatch({cursor:"broken"}),error=>error.code==="INVALID_BACKFILL_CURSOR");await assert.rejects(()=>backfill.runBatch({batchSize:101}),RangeError);});
