"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const workflow=fs.readFileSync(path.join(__dirname,"../.github/workflows/supabase-production-schema-audit.yml"),"utf8");
test("manual-only and immutable official actions",()=>{assert.match(workflow,/on:\n  workflow_dispatch:/);assert.doesNotMatch(workflow,/^\s{2}(?:push|pull_request|schedule|workflow_call):/m);const uses=[...workflow.matchAll(/uses:\s*([^\s]+)/g)].map(x=>x[1]);assert.ok(uses.length>=5);for(const value of uses)assert.match(value,/^actions\/(?:checkout|setup-node|upload-artifact)@[0-9a-f]{40}$/);assert.match(workflow,/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd/);assert.match(workflow,/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903/);assert.match(workflow,/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02/)});
test("branch environment permissions and concurrency fail closed",()=>{assert.match(workflow,/permissions:\n  contents: read/);assert.doesNotMatch(workflow,/(?:contents|actions|checks|deployments|id-token|issues|pull-requests|packages|security-events): write/);assert.match(workflow,/GITHUB_REF.*refs\/heads\/main/);assert.match(workflow,/needs: validation/);assert.match(workflow,/if: github\.ref == 'refs\/heads\/main'/);assert.match(workflow,/environment: production-db-audit/);assert.match(workflow,/group: supabase-production-schema-audit/);assert.match(workflow,/cancel-in-progress: false/)});
test("checkout and installs are hardened",()=>{assert.equal((workflow.match(/persist-credentials: false/g)||[]).length,2);assert.equal((workflow.match(/fetch-depth: 1/g)||[]).length,2);assert.equal((workflow.match(/npm ci --ignore-scripts --no-audit --no-fund/g)||[]).length,2);assert.match(workflow,/node --test tests\/supabase-schema-audit\.test\.js/);assert.match(workflow,/node --test tests\/supabase-schema-audit-workflow\.test\.js/);assert.match(workflow,/npm test/)});
test("only connection step receives only production secret",()=>{assert.equal((workflow.match(/secrets\.SUPABASE_AUDIT_DATABASE_URL/g)||[]).length,1);assert.equal((workflow.match(/^\s{10}SUPABASE_AUDIT_DATABASE_URL:/gm)||[]).length,1);assert.doesNotMatch(workflow,/SUPABASE_(?:SERVICE_ROLE_KEY|ACCESS_TOKEN|DB_PASSWORD)|VERCEL_TOKEN|GITHUB_PAT/);assert.doesNotMatch(workflow,/set -x|echo.*SUPABASE_AUDIT_DATABASE_URL/)});
test("artifact and summary contain fixed redacted reports only",()=>{assert.match(workflow,/db-execution-plan-drift-report\.json/);assert.match(workflow,/db-execution-plan-drift-report\.md/);assert.match(workflow,/retention-days: 7/);assert.match(workflow,/overwrite: false/);assert.match(workflow,/GITHUB_STEP_SUMMARY/);const upload=workflow.slice(workflow.indexOf("name: Upload redacted reports"));assert.doesNotMatch(upload,/raw_dir|audit\.json/);assert.match(workflow,/supabase-schema-audit\.js validate/)});
test("workflow has no mutation deployment or self-trigger",()=>{assert.doesNotMatch(workflow,/\b(?:supabase db push|supabase migration|vercel deploy|psql[^\n]*(?:INSERT|UPDATE|DELETE|ALTER|CREATE|DROP|GRANT|REVOKE))\b/i);assert.doesNotMatch(workflow,/gh workflow run|workflow_dispatch.*curl/)});
