"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { assertAcceptance, sanitizeMetadata, validateReport } = require("../security/supabase-audit-contract");
const { DATASET_V2_COLUMNS, DATASET_V2_CONSTRAINTS, DATASET_V2_CONSTRAINT_TOKENS, DATASET_V2_INDEXES, buildReport, markdown, parseSql, privilegeDrifts, repositoryInventory } = require("../scripts/supabase-schema-audit");

const fixture = () => JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/supabase-audit/compliant.json"),"utf8"));
const repo={migrations:[{version:"20260816101220",filename:"20260816101220_create_dataset_v2.sql",targets:[{operation:"create",target:"performance_dataset_rows_v2"}]}],operationalSql:[],runtimePublicTables:[],unclassifiedRepositorySql:[]};
const policy=()=>({identity:"performance_dataset_rows_v2.performance_dataset_rows_v2_select_own",table:"performance_dataset_rows_v2",name:"performance_dataset_rows_v2_select_own",roles:["authenticated"],command:"SELECT",permissive:"PERMISSIVE",using:"(( SELECT auth.uid() AS uid) = user_id)",withCheck:null});
function dataset(){return {name:"performance_dataset_rows_v2",objectType:"table",owner:"owner",rlsEnabled:true,rlsForced:false,estimatedRows:0,columnCount:Object.keys(DATASET_V2_COLUMNS).length,pkCount:1,fkCount:1,uniqueCount:0,checkCount:19,indexCount:5,policyCount:1,triggerCount:0,anonPrivileges:[],authenticatedPrivileges:["SELECT"],serviceRolePrivileges:["DELETE","INSERT","REFERENCES","SELECT","TRIGGER","TRUNCATE","UPDATE"],auditorPrivileges:["SELECT"],columns:Object.entries(DATASET_V2_COLUMNS).map(([name,[type,nullable]],i)=>({name,ordinal:i+1,type,nullable,default:null})),constraints:DATASET_V2_CONSTRAINTS.map(name=>({name,type:name.endsWith("pkey")?"p":"c",definition:(DATASET_V2_CONSTRAINT_TOKENS[name]||[]).join(" "),referencedSchema:null,referencedTable:null,validated:true,deferrable:false})),indexes:DATASET_V2_INDEXES.map(name=>({name,unique:name.includes("pkey")||name.includes("canonical"),primary:name.includes("pkey"),definition:name.includes("canonical")?"CREATE UNIQUE INDEX x ON public.performance_dataset_rows_v2 (user_id, platform, platform_account_id, business_date, traffic_type, entity_key)":`CREATE INDEX ${name} ON public.performance_dataset_rows_v2 (id)`}))};}
function raw(){const value=fixture();value.relations=[dataset()];value.policies=[policy()];return value;}
const options={generatedAt:"2026-01-01T00:00:00.000Z",repositoryCommit:"abc"};

test("connection acceptance fails closed",()=>{const accepted={currentUser:"codex_auditor",readOnly:true,databaseConnect:true,datasetSelect:true,datasetInsert:false,datasetUpdate:false,datasetDelete:false,datasetTruncate:false,tokenTableSelect:false,accessEnvelopeSelect:false,refreshEnvelopeSelect:false,legacyAccessSelect:false,legacyRefreshSelect:false,authUsersSelect:false,oauthTransactionsSelect:false,migrationLedgerSelect:true};assert.equal(assertAcceptance(accepted),true);assert.throws(()=>assertAcceptance({...accepted,currentUser:"postgres"}),/AUDIT_ROLE_INVALID/);assert.throws(()=>assertAcceptance({...accepted,readOnly:false}),/AUDIT_READ_ONLY_REQUIRED/);for(const key of ["datasetInsert","tokenTableSelect","accessEnvelopeSelect","authUsersSelect","oauthTransactionsSelect"])assert.throws(()=>assertAcceptance({...accepted,[key]:true}),/AUDIT_PRIVILEGE_CONTRACT_FAILED/);assert.throws(()=>assertAcceptance({...accepted,migrationLedgerSelect:false}),/AUDIT_PRIVILEGE_CONTRACT_FAILED/)});

test("SQL uses pg_catalog for restricted-column and fixed-role visibility",()=>{const sql=fs.readFileSync(path.join(__dirname,"../docs/security/sql/DB_EXECUTION_PLAN_AUDIT.sql"),"utf8"),code=sql.replace(/'(?:''|[^'])*'/g,"''");assert.match(sql,/^BEGIN READ ONLY;/);assert.match(sql,/pg_catalog\.pg_attribute/);assert.match(sql,/pg_catalog\.pg_attrdef/);assert.match(sql,/pg_catalog\.format_type/);assert.doesNotMatch(sql,/information_schema\.columns|role_table_grants/);for(const role of ["anon","authenticated","service_role","codex_auditor"])assert.match(sql,new RegExp(`has_table_privilege\\('${role}',r\\.oid,p\\)`));assert.match(sql,/attnum > 0 AND NOT (?:x\.)?attisdropped/);assert.doesNotMatch(code,/\b(?:INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM|TRUNCATE\s+|ALTER\s+(?:TABLE|FUNCTION)|CREATE\s+(?:TABLE|FUNCTION)|DROP\s+|GRANT\s+|REVOKE\s+)\b/i);assert.doesNotMatch(code,/\bstatements\b|\bprosrc\b|SELECT\s+\*\s+FROM\s+(?:public|auth)\./i)});

test("catalog result retains columns despite absence from auditor value privileges",()=>{const restricted=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/supabase-audit/restricted-metadata.json"),"utf8")),value=raw();value.relations[0].auditorPrivileges=restricted.auditorPrivileges;for(const [i,name] of restricted.columnsVisibleFromCatalog.entries())value.relations[0].columns.push({name,ordinal:99+i,type:"text",nullable:true,default:null});value.relations[0].columnCount+=restricted.columnsVisibleFromCatalog.length;const safe=sanitizeMetadata(value);for(const name of restricted.columnsVisibleFromCatalog)assert.ok(safe.relations[0].columns.some(c=>c.name===name));assert.deepEqual(safe.relations[0].auditorPrivileges,[])});

test("another-role ACLs remain in allowlisted metadata",()=>{const value=raw();value.relations[0].anonPrivileges=["SELECT"];value.relations[0].authenticatedPrivileges=["INSERT","SELECT"];value.relations[0].serviceRolePrivileges=["DELETE","SELECT"];const safe=sanitizeMetadata(value).relations[0];assert.deepEqual(safe.anonPrivileges,["SELECT"]);assert.deepEqual(safe.authenticatedPrivileges,["INSERT","SELECT"]);assert.deepEqual(safe.serviceRolePrivileges,["DELETE","SELECT"])});

test("privilege classification is contract-aware",()=>{assert.deepEqual(privilegeDrifts(dataset()),[]);const mutation={...dataset(),authenticatedPrivileges:["INSERT","SELECT"]};assert.equal(privilegeDrifts(mutation)[0].classification,"SECURITY_CORRECTIVE");for(const name of ["platform_connection_tokens","oauth_transactions"]){const relation={...dataset(),name,authenticatedPrivileges:["SELECT"]};assert.equal(privilegeDrifts(relation)[0].classification,"SECURITY_CORRECTIVE")}for(const privilege of ["TRUNCATE","TRIGGER","REFERENCES"]){const relation={...dataset(),name:"legacy_table",authenticatedPrivileges:[privilege]};assert.equal(privilegeDrifts(relation)[0].classification,"SECURITY_CORRECTIVE")}assert.equal(privilegeDrifts({...dataset(),name:"legacy_table",authenticatedPrivileges:["SELECT"]})[0].classification,"REVIEW_REQUIRED")});

test("Dataset V2 compliant schema reports schema-level readiness PASS",()=>{const report=buildReport(raw(),repo,options);assert.equal(report.summary.datasetV2SchemaReady,true);assert.doesNotMatch(markdown(report),/dataset-v2-(?:column|constraint|index|policy)/);assert.match(markdown(report),/Schema-level PASS/)});
for(const [label,mutate,id] of [["column",r=>r.columns.pop(),"dataset-v2-column"],["constraint",r=>{r.constraints.find(x=>x.name==="performance_dataset_rows_v2_platform_chk").definition="CHECK (false)"},"dataset-v2-constraint-definition"],["index",r=>r.indexes.pop(),"dataset-v2-index"]])test(`Dataset V2 ${label} drift is E2_BLOCKER`,()=>{const value=raw();mutate(value.relations[0]);const report=buildReport(value,repo,options);assert.ok(report.drifts.some(d=>d.id.startsWith(id)&&d.classification==="E2_BLOCKER"));assert.equal(report.summary.datasetV2SchemaReady,false)});
test("Dataset V2 policy and grant drift are E2 blockers",()=>{const value=raw();value.policies[0].command="ALL";value.relations[0].authenticatedPrivileges.push("INSERT");const report=buildReport(value,repo,options);assert.ok(report.drifts.some(d=>d.id==="dataset-v2-policy"));assert.ok(report.drifts.some(d=>d.id==="dataset-v2-privileges"))});

test("schema names are distinct from sensitive values",()=>{const value=raw();value.relations[0].columns.push(...["access_token","refresh_token","access_token_envelope","refresh_token_envelope","ciphertext"].map((name,i)=>({name,ordinal:100+i,type:"text",nullable:true,default:null})));value.relations[0].columnCount+=5;value.relations[0].constraints.push({name:"safe",type:"c",definition:"CHECK (access_token IS NULL)",referencedSchema:null,referencedTable:null,validated:true,deferrable:false});const report=buildReport(value,repo,options);assert.equal(validateReport(report),true);for(const secret of ["raw-access-token: abcdefghijklmnop","raw-refresh-token: abcdefghijklmnop","{\"ciphertext\":\"abcdefghijklmnop\"}","postgresql://u:p@host/db","eyJabcdefgh.abcdefgh.abcdefgh","-----BEGIN PRIVATE KEY-----"]){const copy=structuredClone(report);copy.limitations.push(secret);assert.throws(()=>validateReport(copy),/AUDIT_REPORT_INVALID/)}});

test("validator rejects malformed raw metadata and raw report row objects",()=>{assert.throws(()=>sanitizeMetadata({relations:[]}),/AUDIT_REPORT_INVALID/);const report=buildReport(raw(),repo,options);report.relations[0].row={email:"fixture@example.invalid"};assert.throws(()=>validateReport(report),/AUDIT_REPORT_INVALID/)});
test("missing required Dataset metadata is REVIEW_REQUIRED",()=>{const value=raw();value.relations[0].columnCount=null;const report=buildReport(value,repo,options);assert.ok(report.drifts.some(d=>d.id==="dataset-v2-metadata-incomplete"&&d.classification==="REVIEW_REQUIRED"))});

test("recommended package order is populated and deterministic",()=>{const value=raw();value.relations.push({...dataset(),name:"users",authenticatedPrivileges:["SELECT"]});value.migrations.push({version:"20260101000000",name:"ledger_only"});const changed={...repo,migrations:[...repo.migrations,{version:"20270101000000",filename:"20270101000000_future.sql",targets:[]} ]};const md=markdown(buildReport(value,changed,options));const positions=["E2_BLOCKER","REPOSITORY_BASELINE","PLAN_DRIFT","REVIEW_REQUIRED"].map(x=>md.lastIndexOf(`${x}:`));assert.ok(positions.every(x=>x>0));assert.deepEqual([...positions].sort((a,b)=>a-b),positions);assert.match(md,/`repository-only-20270101000000`/)});

test("reports are deterministic and repository SQL is classified",()=>{const a=buildReport(raw(),repo,options),b=buildReport(raw(),repo,options);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(markdown(a),markdown(b));const root=fs.mkdtempSync(path.join(os.tmpdir(),"audit-repo-"));fs.mkdirSync(path.join(root,"supabase/migrations"),{recursive:true});fs.mkdirSync(path.join(root,"docs/security/sql"),{recursive:true});fs.writeFileSync(path.join(root,"supabase/migrations/20260101000000_fixture.sql"),"CREATE TABLE public.safe_table(id bigint);\nVACUUM public.safe_table;\n");fs.writeFileSync(path.join(root,"docs/security/sql/operator.sql"),"SELECT 1;");const inventory=repositoryInventory(root);assert.equal(inventory.migrations.length,1);assert.equal(inventory.operationalSql.length,1);assert.equal(inventory.unclassifiedRepositorySql.length,1);assert.deepEqual(parseSql("ALTER TABLE public.x ADD COLUMN y text;").targets,[{operation:"alter",target:"x"}])});
