'use strict';
const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const {readState,writeState}=require('./state-store');const evidence=require('../scripts/e2-t7-cleanup-evidence');
const APPROVED_MAIN_SHA='ba298aa8e9ac5701d5609d48770f13909951bdb2',OPERATION='e2_t7_no_change_v2',VERSION='e2-t7-no-change-v2',CONFIRMATION='E2-T7-FINAL-NO-CHANGE';
const SQL=Object.freeze({baseline:'docs/security/sql/E2_T7_BASELINE.sql',final:'docs/security/sql/E2_T7_FINAL_CHECK.sql'});
const ARTIFACTS=Object.freeze([...Object.values(SQL),'operator/e2-t7-v2.js','operator/management-api.js','operator/state-store.js','scripts/e2-t7-v2-operator.js','scripts/e2-t7-cleanup-evidence.js','artifacts/dataset-v2-acceptance/e2-t7-cleanup/fixture-inventory.json','artifacts/dataset-v2-acceptance/e2-t7-cleanup/no-change-contract.json']);
const BASELINE_CODES=Object.freeze(['DATASET_V2_BASELINE','DATASET_V1_BASELINE','SNAPSHOT_BASELINE','CONNECTED_CONNECTIONS','ENCRYPTED_TOKEN_ROWS']);
function checksum(repo){const h=crypto.createHash('sha256');for(const f of ARTIFACTS)h.update(f).update('\0').update(fs.readFileSync(path.join(repo,f))).update('\0');return h.digest('hex')}
function binding(repo){return{operation:OPERATION,version:VERSION,approvedMainSha:APPROVED_MAIN_SHA,artifactChecksum:checksum(repo)}}
function verifyGit(repo,exec=cp.execFileSync){const approved=exec('git',['rev-parse',`${APPROVED_MAIN_SHA}^{commit}`],{cwd:repo,encoding:'utf8'}).trim(),base=exec('git',['merge-base','HEAD',APPROVED_MAIN_SHA],{cwd:repo,encoding:'utf8'}).trim();if(approved!==APPROVED_MAIN_SHA||base!==APPROVED_MAIN_SHA)throw new Error('HEAD is not based on approved main SHA')}
function validateBaseline(rows){if(!Array.isArray(rows)||rows.length!==evidence.CHECK_CODES.length)throw new Error('Baseline check count mismatch');const seen=new Map();for(const row of rows){if(!row||!evidence.CHECK_CODES.includes(row.check_code)||seen.has(row.check_code)||!Number.isSafeInteger(row.actual_count)||row.actual_count<0||!Number.isSafeInteger(row.expected_count)||row.expected_count<0||row.passed!==true)throw new Error('Baseline gate failed');seen.set(row.check_code,row)}for(const code of evidence.CHECK_CODES)if(!seen.has(code))throw new Error('Baseline gate missing');const names={DATASET_V2_BASELINE:'datasetRows',DATASET_V1_BASELINE:'v1Rows',SNAPSHOT_BASELINE:'snapshotRows',CONNECTED_CONNECTIONS:'connectedRows',ENCRYPTED_TOKEN_ROWS:'encryptedRows'},baselines={};for(const [code,key] of Object.entries(names)){if(seen.get(code).comparison!=='capture')throw new Error('Baseline capture mismatch');baselines[key]=seen.get(code).actual_count}return baselines}
function finalSql(template,baselines){let sql=template;for(const key of ['datasetRows','v1Rows','snapshotRows','connectedRows','encryptedRows'])sql=sql.replace('(-1)::bigint',`(${baselines[key]})::bigint`);if((template.match(/\(-1\)::bigint/g)||[]).length!==5||sql.includes('(-1)::bigint'))throw new Error('Final baseline substitution failed');return sql}
function safeError(code){const e=new Error('E2-T7 stopped fail-closed');e.safeCode=code;return e}
async function preflight({repo,stateFile,client,runTests=()=>cp.execFileSync('npm',['test'],{cwd:repo,stdio:'inherit'}),verifyRepository=verifyGit}){verifyRepository(repo);const baselineFile=`${stateFile}.baseline.json`;if(fs.existsSync(stateFile)||fs.existsSync(baselineFile)||fs.existsSync(`${stateFile}.outcome.json`))throw new Error('Operator state already exists');runTests();let result;try{result=await client.query(fs.readFileSync(path.join(repo,SQL.baseline),'utf8'))}catch{throw safeError('BASELINE_QUERY_FAILED')}let baselines;try{baselines=validateBaseline(result.rows)}catch{throw safeError('BASELINE_GATES_FAILED')}fs.mkdirSync(path.dirname(stateFile),{recursive:true,mode:0o700});fs.writeFileSync(baselineFile,JSON.stringify(result.rows),{flag:'wx',mode:0o600});const b=binding(repo),state={schemaVersion:1,operation:OPERATION,version:VERSION,approvedMainSha:APPROVED_MAIN_SHA,artifactChecksum:b.artifactChecksum,baselines,phase:'approval-ready',transactionSent:false,postcheckSent:false,consumed:false};writeState(stateFile,state,b,repo,{create:true});return Object.freeze({operation:OPERATION,status:'APPROVAL_READY',baseline:'19/19 PASS',baselineCount:5,finalRequests:0})}
async function execute({repo,stateFile,client,confirmation,verifyRepository=verifyGit}){if(confirmation!==CONFIRMATION)throw new Error('Exact human confirmation is required');verifyRepository(repo);const b=binding(repo),state=readState(stateFile,b,repo),baselineFile=`${stateFile}.baseline.json`;if(state.phase!=='approval-ready'||state.transactionSent||state.postcheckSent||state.consumed)throw new Error('Approval-ready state required');let baselineRows;try{baselineRows=JSON.parse(fs.readFileSync(baselineFile,'utf8'));validateBaseline(baselineRows)}catch{throw safeError('BASELINE_CAPSULE_INVALID')}writeState(stateFile,{...state,phase:'consumed',transactionSent:true,postcheckSent:true,consumed:true},b,repo);let result;try{result=await client.query(finalSql(fs.readFileSync(path.join(repo,SQL.final),'utf8'),state.baselines))}catch{throw safeError('FINAL_QUERY_FAILED')}let report;try{report=evidence.buildEvidence(baselineRows,result.rows)}catch{throw safeError('FINAL_EVIDENCE_FAILED')}fs.writeFileSync(`${stateFile}.outcome.json`,JSON.stringify({schemaVersion:1,operation:OPERATION,version:VERSION,code:'PASS'})+'\n',{flag:'wx',mode:0o600});return Object.freeze({...report,operation:OPERATION,baselineRequests:1,finalRequests:1,retries:0,state:'CONSUMED',productionCountsExposed:false,productionIdentitiesExposed:false})}
module.exports=Object.freeze({APPROVED_MAIN_SHA,ARTIFACTS,BASELINE_CODES,CONFIRMATION,OPERATION,SQL,VERSION,binding,checksum,execute,finalSql,preflight,validateBaseline,verifyGit});
